ICT397 Game Engine: C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/EngineAPI.cpp File Reference
EngineAPI.cpp File Reference
#include "EngineAPI.h"
#include "DXEngine.h"
#include "GLEngine.h"
#include "ShaderLibrary.h"
#include "ModelLibrary.h"
#include "InputManager.h"
Functions
static void CreateShader (string const &name, string const &vertFilePath, string const &fragFilePath, std::vector< string > const &attributes, std::vector< string > const &uniforms)
static void Initialise (int screenWidth, int screenHeight)
static bool BeginUpdate ()
static void EndUpdate ()
Function Documentation
static bool BeginUpdate () static
Definition at line 39 of file EngineAPI.cpp.
References IEngine::BeginUpdate(), and EngineAPI::GetEngine().
 {
   return EngineAPI::GetEngine()->BeginUpdate();
 }
static void CreateShader (string const & name, string const & vertFilePath, string const & fragFilePath, std::vector< string > const & attributes, std::vector< string > const & uniforms) static
Definition at line 25 of file EngineAPI.cpp.
 {
   EngineAPI::GetEngine()->CreateShader(name, vertFilePath, fragFilePath, attributes, uniforms);
 }
static void EndUpdate () static
Definition at line 44 of file EngineAPI.cpp.
References IEngine::EndUpdate(), and EngineAPI::GetEngine().
 {
   EngineAPI::GetEngine()->EndUpdate();
 }
static void Initialise (int screenWidth, int screenHeight) static
Definition at line 30 of file EngineAPI.cpp.
References EngineAPI::GetEngine(), ModelLibrary::Initialise(), IEngine::Initialise(), and ShaderLibrary::InitShaderLibrary().
 {
   EngineAPI::GetEngine()->Initialise(screenWidth, screenHeight);
   ShaderLibrary::InitShaderLibrary(EngineAPI::GetEngine());
   ModelLibrary::Initialise(EngineAPI::GetEngine());
   InputManager::GetInstance().Initialise(EngineAPI::GetEngine()->CreateInputHandler());
 }