ICT397 Game Engine: C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/MathAPI.cpp File Reference
MathAPI.cpp File Reference
#include "MathAPI.h"
Functions
static void ExposeVec3 (LuaContext *pContext, string const &luaAPIName)
LuaRef ToLuaTable (vec3 value, LuaContextHandle contextHandle)
LuaRef ToLuaTable (std::vector< float > data, int width, int height, LuaContextHandle contextHandle)
Converts vector of floats to 2D lua table
LuaRef ToLuaTable (mat4 value, LuaContextHandle contextHandle)
Converts mat4 to lua table
template<>
vec3 FromLuaTable< vec3 > (LuaRef value)
Gets vec3 return from the lua table.
template<>
mat4 FromLuaTable< mat4 > (LuaRef value)
Gets mat4 return from the lua table.
Function Documentation
static void ExposeVec3 (LuaContext * pContext, string const & luaAPIName) static
Definition at line 5 of file MathAPI.cpp.
 {
   pContext->AddClass<vec3>(luaAPIName, "vec3");
   pContext->AddClassDataMember<vec3>(luaAPIName, "vec3", "x", &vec3::x);
   pContext->AddClassDataMember<vec3>(luaAPIName, "vec3", "y", &vec3::y);
   pContext->AddClassDataMember<vec3>(luaAPIName, "vec3", "z", &vec3::z);
   pContext->AddClassConstructor<vec3, void(*) (void)>(luaAPIName, "vec3");
 }
template<> mat4 FromLuaTable< mat4 > (LuaRef value)
Gets mat4 return from the lua table.
Parameters
value The value.
Returns
mat4
Definition at line 70 of file MathAPI.cpp.
 {
   float result[16];
   for (int i = 1; i <= 16; i++)
   {
     result[i - 1] = value[i];
   }
   return glm::make_mat4(result);
 }
template<> vec3 FromLuaTable< vec3 > (LuaRef value)
Gets vec3 return from the lua table.
Parameters
value The value.
Returns
vec3
Definition at line 59 of file MathAPI.cpp.
 {
     vec3 result;
     result.x = value["x"];
     result.y = value["y"];
     result.z = value["z"];
     return result;
 }
LuaRef ToLuaTable (vec3 value, LuaContextHandle contextHandle)
Definition at line 14 of file MathAPI.cpp.
 {
   LuaRef table = newTable(LuaManager::GetInstance().GetContext(contextHandle)->GetLuaState());
   table["x"] = value.x;
   table["y"] = value.y;
   table["z"] = value.z;
   return table;
 }
LuaRef ToLuaTable (std::vector< float > data, int width, int height, LuaContextHandle contextHandle)
Converts vector of floats to 2D lua table
Parameters
data Vector of float.
width Desired width.
height Desired height.
contextHandle The context handle.
Returns
LuaRef
Definition at line 24 of file MathAPI.cpp.
 {
     LuaRef table = newTable(LuaManager::GetInstance().GetContext(contextHandle)->GetLuaState());
     LuaRef tempTable = newTable(LuaManager::GetInstance().GetContext(contextHandle)->GetLuaState());
     for (int i = 1; i <= width; i++)
     {
         tempTable = newTable(LuaManager::GetInstance().GetContext(contextHandle)->GetLuaState());
         for (int k = 1; k <= height; k++)
         {
             tempTable[k] = data.at(((i - 1) * width) + k - 1);
         }
         table[i] = tempTable;
     }
     return table;
 }
LuaRef ToLuaTable (mat4 value, LuaContextHandle contextHandle)
Converts mat4 to lua table
Parameters
value The value.
contextHandle The context handle.
Returns
LuaRef
Definition at line 42 of file MathAPI.cpp.
Referenced by ObjectInstanceAPI::GetScale(), ObjectInstanceAPI::GetTranslation(), LuaVectorUtility::mat4_CreateIdentity(), IslandCollisionAPI::Resolve(), LuaVectorUtility::vec3_CreateEmpty(), LuaVectorUtility::vec3_Multiply(), LuaVectorUtility::vec3_Normalize(), LuaVectorUtility::vec3_ScalarMultiply(), LuaVectorUtility::vec3_Subtract(), and LuaVectorUtility::vec3_Sum().
 {
   LuaRef table = newTable(LuaManager::GetInstance().GetContext(contextHandle)->GetLuaState());
   const float *pSource = (const float*)glm::value_ptr(value);
   for (int i = 0; i < 16; i++)
   {
      table[i + 1] = pSource[i];
   }
   return table;
 }