ICT397 Game Engine: C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/PrimitiveCollisions.h File Reference
PrimitiveCollisions.h File Reference
Collisions tests for geometric primitives.
#include "GeometricPrimitives.h"
Functions
bool Intersects (mAABB const &a, mAABB const &b)
AABB collision by Nathan.
bool Intersects (mAABB const &aabb, mOBB const &obb)
bool Intersects (mAABB const &aabb, mTriangle const &tri)
bool Intersects (mAABB const &aabb, mSphere const &sphere)
bool Intersects (mAABB const &aabb, mRay const &ray, float *rayEnterDist=nullptr, float *rayExitDist=nullptr)
bool Intersects (mOBB const &a, mOBB const &b)
bool Intersects (mOBB const &obb, mTriangle const &tri)
bool Intersects (mOBB const &obb, mSphere const &sphere)
bool Intersects (mOBB const &obb, mRay const &ray)
bool Intersects (mTriangle const &a, mTriangle const &b)
bool Intersects (mTriangle const &tri, mSphere const &sphere)
bool Intersects (mSphere const &a, mSphere const &b)
bool Intersects (mSphere const &sphere, mRay const &ray)
Detailed Description
Collisions tests for geometric primitives.
Maddisen Topaz
Date
S2, 2016 The various methods for testing collisions among geometric primitives.
Definition in file PrimitiveCollisions.h.
Function Documentation
bool Intersects (mAABB const & a, mAABB const & b)
AABB collision by Nathan.
Definition at line 123 of file PrimitiveCollisions.cpp.
Referenced by IslandCollision::Check().
 {
     //vec3 cornersA[8];
     //vec3 cornersB[8];
     if (a.max.x > b.min.x &&
         a.min.x < b.max.x &&
         a.max.y > b.min.y &&
         a.min.y < b.max.y &&
         a.max.z > b.min.z &&
         a.min.z < b.max.z)
         {
         return true;
 }
     return false;
     /*
     if (a.min.x <= b.max.x &&
         a.max.x >= b.min.x &&
         a.min.y <= b.max.y &&
         a.max.y >= b.min.y &&
         a.min.z <= b.max.z &&
         a.max.z >= b.min.z)
     {
         return true;
     }
     else {
         return false;
     }
     */
     /*
     cornersA[0] = vec3(a.min.x, a.min.y, a.min.z);
     cornersA[1] = vec3(a.min.x, a.min.y, a.max.z);
     cornersA[2] = vec3(a.min.x, a.max.y, a.min.z);
     cornersA[3] = vec3(a.min.x, a.max.y, a.max.z);
     cornersA[4] = vec3(a.max.x, a.min.y, a.min.z);
     cornersA[5] = vec3(a.max.x, a.min.y, a.max.z);
     cornersA[6] = vec3(a.max.x, a.max.y, a.min.z);
     cornersA[7] = vec3(a.max.x, a.max.y, a.max.z);
     cornersB[0] = vec3(a.min.x, a.min.y, a.min.z);
     cornersB[1] = vec3(a.min.x, a.min.y, a.max.z);
     cornersB[2] = vec3(a.min.x, a.max.y, a.min.z);
     cornersB[3] = vec3(a.min.x, a.max.y, a.max.z);
     cornersB[4] = vec3(a.max.x, a.min.y, a.min.z);
     cornersB[5] = vec3(a.max.x, a.min.y, a.max.z);
     cornersB[6] = vec3(a.max.x, a.max.y, a.min.z);
     cornersB[7] = vec3(a.max.x, a.max.y, a.max.z);
     vec3 normals[3];
     normals[0] = vec3(1, 0, 0);
     normals[1] = vec3(0, 1, 0);
     normals[2] = vec3(0, 0, 1);
     return SeperatingAxisTest(cornersA, 8, cornersB, 8, normals, 3);*/
 }
bool Intersects (mAABB const & aabb, mOBB const & obb)
Definition at line 182 of file PrimitiveCollisions.cpp.
References mOBB::axes, mOBB::corners, and SeperatingAxisTest().
 {
     vec3 aabbCorners[8];
     vec3 normals[6];
     aabbCorners[0] = vec3(aabb.min.x, aabb.min.y, aabb.min.z);
     aabbCorners[1] = vec3(aabb.min.x, aabb.min.y, aabb.max.z);
     aabbCorners[2] = vec3(aabb.min.x, aabb.max.y, aabb.min.z);
     aabbCorners[3] = vec3(aabb.min.x, aabb.max.y, aabb.max.z);
     aabbCorners[4] = vec3(aabb.max.x, aabb.min.y, aabb.min.z);
     aabbCorners[5] = vec3(aabb.max.x, aabb.min.y, aabb.max.z);
     aabbCorners[6] = vec3(aabb.max.x, aabb.max.y, aabb.min.z);
     aabbCorners[7] = vec3(aabb.max.x, aabb.max.y, aabb.max.z);
     normals[0] = vec3(1, 0, 0);
     normals[1] = vec3(0, 1, 0);
     normals[2] = vec3(0, 0, 1);
     normals[4] = obb.axes[0];
     normals[5] = obb.axes[1];
     normals[6] = obb.axes[2];
     return SeperatingAxisTest(aabbCorners, 8, obb.corners, 8, normals, 6);
 }
bool Intersects (mAABB const & aabb, mTriangle const & tri)
Definition at line 206 of file PrimitiveCollisions.cpp.
References mTriangle::corners, getmTriangleNormals(), mAABBtomOBB(), and SeperatingAxisTest().
 {
     vec3 aabbCorners[8];
     vec3 normals[7];
     mAABBtomOBB(aabbCorners, normals, aabb);
     getmTriangleNormals(normals + 3,tri);
     return SeperatingAxisTest(aabbCorners, 8, tri.corners, 3, normals, 7);
 }
bool Intersects (mAABB const & aabb, mSphere const & sphere)
Definition at line 217 of file PrimitiveCollisions.cpp.
References mSphere::centre, getProjection1D(), Intersects(), and mAABBtomOBB().
 {
     vec3 aabbCorners[8];
     vec3 normals[11];
     mAABBtomOBB(aabbCorners, normals, aabb);
     for (int i = 0; i < 8; i++)
         normals[i+3] = aabbCorners[i] - sphere.centre;
     for (int j = 0; j < 11; j++)
     {
         LineSegment1D boxShadow;
         LineSegment1D sphereShadow;
         boxShadow = getProjection1D(aabbCorners, normals[j], 8);
         sphereShadow = getProjection1D(sphere, normals[j]);
         if (!Intersects(boxShadow, sphereShadow))
             return false;
     }
     return true;
 }
bool Intersects (mAABB const & aabb, mRay const & ray, float * rayEnterDist = nullptr, float * rayExitDist = nullptr)
Definition at line 240 of file PrimitiveCollisions.cpp.
 {
     //TODO
     return false;
 }
bool Intersects (mOBB const & a, mOBB const & b)
Definition at line 246 of file PrimitiveCollisions.cpp.
References mOBB::axes, mOBB::corners, and SeperatingAxisTest().
 {
     vec3 normals[6];
     normals[0] = a.axes[0];
     normals[1] = a.axes[1];
     normals[2] = a.axes[2];
     normals[3] = b.axes[0];
     normals[4] = b.axes[1];
     normals[5] = b.axes[2];
     return SeperatingAxisTest(a.corners,8,b.corners,8,normals,6);
 }
bool Intersects (mOBB const & obb, mTriangle const & tri)
Definition at line 261 of file PrimitiveCollisions.cpp.
References mOBB::axes, mOBB::corners, mTriangle::corners, getmTriangleNormals(), and SeperatingAxisTest().
 {
     vec3 normals[7];
     normals[0] = obb.axes[0];
     normals[1] = obb.axes[1];
     normals[2] = obb.axes[2];
     getmTriangleNormals(normals + 3, tri);
     return SeperatingAxisTest(obb.corners, 8, tri.corners, 3, normals, 7);
 }
bool Intersects (mOBB const & obb, mSphere const & sphere)
Definition at line 274 of file PrimitiveCollisions.cpp.
References mOBB::axes, mSphere::centre, mOBB::corners, getProjection1D(), and Intersects().
 {
     vec3 normals[11];
     normals[0] = obb.axes[0];
     normals[1] = obb.axes[0];
     normals[2] = obb.axes[0];
     for (int i = 0; i < 8; i++)
         normals[i + 3] = obb.corners[i] - sphere.centre;
     for (int j = 0; j < 11; j++)
     {
         LineSegment1D boxShadow;
         LineSegment1D sphereShadow;
         boxShadow = getProjection1D(obb.corners, normals[j], 8);
         sphereShadow = getProjection1D(sphere, normals[j]);
         if (!Intersects(boxShadow, sphereShadow))
             return false;
     }
     return true;
 }
bool Intersects (mOBB const & obb, mRay const & ray)
Definition at line 298 of file PrimitiveCollisions.cpp.
 {
     //TODO
     return false;
 }
bool Intersects (mTriangle const & a, mTriangle const & b)
Definition at line 304 of file PrimitiveCollisions.cpp.
References mTriangle::corners, getmTriangleNormals(), and SeperatingAxisTest().
 {
     vec3 normals[8];
     getmTriangleNormals(normals, a);
     getmTriangleNormals(normals + 4, b);
     SeperatingAxisTest(a.corners, 3, b.corners, 3, normals, 8);
     return false;
 }
bool Intersects (mTriangle const & tri, mSphere const & sphere)
Definition at line 316 of file PrimitiveCollisions.cpp.
References mSphere::centre, mTriangle::corners, getmTriangleNormals(), getProjection1D(), and Intersects().
 {
     vec3 normals[8];
     getmTriangleNormals(normals, tri);
     for (int i = 0; i < 4; i++)
         normals[i + 4] = tri.corners[i] - sphere.centre;
     for (int j = 0; j < 8; j++)
     {
         LineSegment1D triangleShadow;
         LineSegment1D sphereShadow;
         triangleShadow = getProjection1D(tri.corners, normals[j], 8);
         sphereShadow = getProjection1D(sphere, normals[j]);
         if (!Intersects(triangleShadow, sphereShadow))
             return false;
     }
     return true;
 }
bool Intersects (mSphere const & a, mSphere const & b)
Definition at line 414 of file PrimitiveCollisions.cpp.
References mSphere::centre, getProjection1D(), and Intersects().
 {
     vec3 normal = a.centre - b.centre;
     LineSegment1D sphere1Shadow = getProjection1D(a,normal);
     LineSegment1D sphere2Shadow = getProjection1D(b,normal);
     if (!Intersects(sphere1Shadow, sphere2Shadow))
         return false;
     return true;
 }
bool Intersects (mSphere const & sphere, mRay const & ray)
Definition at line 427 of file PrimitiveCollisions.cpp.
 {
     //TODO
     return false;
 }