ICT397 Game Engine: Shader Class Reference
Shader Class Reference
#include <Shader.h>
Public Member Functions
Shader (string const &name)
Initializes a new instance of the Shader class.
Shader (string const &name, string const &vertFilePath, string const &fragFilePath, std::vector< string > const &attributes, std::vector< string > const &uniforms)
Initializes a new instance of the Shader class.
~Shader ()
Finalizes an instance of the Shader class.
void Load (string const &vertFilePath, string const &fragFilePath, std::vector< string > const &attributes, std::vector< string > const &uniforms)
Loads the specified shader files.
virtual void Bind () const override
Binds this instance.
void Setup ()
Setups this instance.
void SetupLocations (std::vector< string > const &custom_attributes, std::vector< string > const &custom_uniforms)
Setups the locations.
virtual string const & GetName () const override
Gets the name.
virtual unsigned int Attribute (string const &name) const override
Returns the attribute with the specified name.
virtual unsigned int Uniform (string const &name) const override
Returns the uniform with the specified name.
virtual bool HasAttribute (string const &name) const override
Determines whether the specified shader has attribute.
virtual bool HasUniform (string const &name) const override
Determines whether the specified shader has uniform.
virtual void TransmitUniform (string const &uniformID, float const &value) const override
Transmits the uniform.
virtual void TransmitUniform (string const &uniformID, int const &value) const override
Transmits the uniform.
virtual void TransmitUniform (string const &uniformID, mat4 const &matrix) const override
Transmits the uniform.
virtual void TransmitUniform (string const &uniformID, vec3 const &vector) const override
Transmits the uniform.
virtual void TransmitUniform (string const &uniformID, vec2 const &vector) const override
Transmits the uniform.
virtual void TransmitUniformArray (string const &uniformID, mat4 *matrix, int count) const override
Transmits the uniform array.
Private Attributes
string m_name
The m name
unsigned int m_uid
The shaders ID
const char * m_pVertex
The vertex shader
const char * m_pFragment
The fragment shader
std::unordered_map< string, int > m_attributes
The attributes
std::unordered_map< string, int > m_uniforms
The uniforms
Detailed Description
Definition at line 37 of file Shader.h.
Constructor & Destructor Documentation
Shader::Shader (string const & name)
Initializes a new instance of the Shader class.
Parameters
name The name.
Definition at line 8 of file Shader.cpp.
References m_pFragment, m_pVertex, and m_uid.
 {
     m_name = name;
     m_uid = -1;
     m_pVertex = NULL;
     m_pFragment = NULL;
 }
Shader::Shader (string const & name, string const & vertFilePath, string const & fragFilePath, std::vector< string > const & attributes, std::vector< string > const & uniforms)
Initializes a new instance of the Shader class.
Parameters
name The name.
vertFilePath The vert file path.
fragFilePath The frag file path.
attributes The attributes.
uniforms The uniforms.
Definition at line 16 of file Shader.cpp.
 {
     m_name = name;
     Load(vertFilePath, fragFilePath, attributes, uniforms);
 }
Shader::~Shader ()
Finalizes an instance of the Shader class.
Definition at line 22 of file Shader.cpp.
References m_pFragment, and m_pVertex.
 {
     m_attributes.clear();
     m_uniforms.clear();
     delete[] m_pVertex;
     delete[] m_pFragment;
 }
Member Function Documentation
unsigned int Shader::Attribute (string const & name) const override virtual
Returns the attribute with the specified name.
Parameters
name The name.
Returns
int
Implements IShader.
Definition at line 113 of file Shader.cpp.
 {
     return m_attributes.at(name);
 }
void Shader::Bind () const override virtual
Binds this instance.
Implements IShader.
Definition at line 89 of file Shader.cpp.
Referenced by SetupLocations().
 {
     glUseProgram(m_uid);
 }
string const & Shader::GetName () const override virtual
Gets the name.
Returns
Implements IShader.
Definition at line 108 of file Shader.cpp.
 {
     return m_name;
 }
bool Shader::HasAttribute (string const & name) const override virtual
Determines whether the specified shader has attribute.
Parameters
name The name.
Returns
true if the specified name has attribute; otherwise, false.
Implements IShader.
Definition at line 123 of file Shader.cpp.
 {
     std::unordered_map<string, int>::const_iterator got = m_attributes.find(name);
     if (got == m_attributes.end())
     {
         return false;
     }
     return true;
 }
bool Shader::HasUniform (string const & name) const override virtual
Determines whether the specified shader has uniform.
Parameters
name The name.
Returns
true if the specified name has uniform; otherwise, false.
Implements IShader.
Definition at line 134 of file Shader.cpp.
 {
     std::unordered_map<string, int>::const_iterator got = m_uniforms.find(name);
     if (got == m_uniforms.end())
     {
         return false;
     }
     return true;
 }
void Shader::Load (string const & vertFilePath, string const & fragFilePath, std::vector< string > const & attributes, std::vector< string > const & uniforms)
Loads the specified shader files.
Parameters
vertFilePath The vert file path.
fragFilePath The frag file path.
attributes The attributes.
uniforms The uniforms.
Definition at line 30 of file Shader.cpp.
References Setup().
 {
     m_pVertex = LoadShaderFile(vertFilePath);
     m_pFragment = LoadShaderFile(fragFilePath);
     Setup();
     SetupLocations(attributes, uniforms);
 }
void Shader::Setup ()
Setups this instance.
Definition at line 39 of file Shader.cpp.
References m_pFragment, m_pVertex, and m_uid.
Referenced by Load().
 {
     if (m_pVertex == NULL || m_pFragment == NULL)
     {
         printf("Unable to load shader %s", m_name.c_str());
     }
     unsigned int pProgram;
     pProgram = glCreateProgram();
     GLint vShader = glCreateShader(GL_VERTEX_SHADER);
     glShaderSource(vShader, 1, &m_pVertex, NULL);
     glCompileShader(vShader);
     GLint vShaderCompiled = GL_FALSE;
     glGetShaderiv(vShader, GL_COMPILE_STATUS, &vShaderCompiled);
     if (!vShaderCompiled)
     {
         printf("Unable to compile vertex shader.");
         PrintShaderLog(vShader);
         getchar();
     }
     GLint fShader = glCreateShader(GL_FRAGMENT_SHADER);
     glShaderSource(fShader, 1, &m_pFragment, NULL);
     glCompileShader(fShader);
     GLint fShaderCompiled = GL_FALSE;
     glGetShaderiv(fShader, GL_COMPILE_STATUS, &fShaderCompiled);
     if (!fShaderCompiled)
     {
         printf("Unable to compile fragment shader.");
         PrintShaderLog(fShader);
         getchar();
     }
     glAttachShader(pProgram, vShader);
     glAttachShader(pProgram, fShader);
     glLinkProgram(pProgram);
     GLint programSuccess = GL_TRUE;
     glGetProgramiv(pProgram, GL_LINK_STATUS, &programSuccess);
     if (!programSuccess)
     {
         printf("Error linking program %d", pProgram);
         PrintProgramLog(pProgram);
         getchar();
     }
     m_uid = pProgram;
 }
void Shader::SetupLocations (std::vector< string > const & custom_attributes, std::vector< string > const & custom_uniforms)
Setups the locations.
Parameters
custom_attributes The custom attributes.
custom_uniforms The custom uniforms.
Definition at line 94 of file Shader.cpp.
References Bind().
 {
     Bind();
     for (uint32_t i = 0; i < custom_attributes.size(); i++)
     {
         m_attributes.emplace(custom_attributes[i], glGetAttribLocation(m_uid, custom_attributes[i].c_str()));
     }
     for (uint32_t j = 0; j < custom_uniforms.size(); j++)
     {
         m_uniforms.emplace(custom_uniforms[j], glGetUniformLocation(m_uid, custom_uniforms[j].c_str()));
     }
 }
virtual void Shader::TransmitUniform (string const & uniformID, float const & value) const inline override virtual
Transmits the uniform.
Parameters
uniformID The uniform identifier.
value The value.
Implements IShader.
Definition at line 135 of file Shader.h.
References Uniform().
     {
     int uniformIDint = Uniform(uniformID);
         glUniform1f(uniformIDint, value);
     }
virtual void Shader::TransmitUniform (string const & uniformID, int const & value) const inline override virtual
Transmits the uniform.
Parameters
uniformID The uniform identifier.
value The value.
Implements IShader.
Definition at line 141 of file Shader.h.
References Uniform().
     {
     int uniformIDint = Uniform(uniformID);
         glUniform1i(uniformIDint, value);
     }
virtual void Shader::TransmitUniform (string const & uniformID, mat4 const & matrix) const inline override virtual
Transmits the uniform.
Parameters
uniformID The uniform identifier.
matrix The matrix.
Implements IShader.
Definition at line 148 of file Shader.h.
References TransmitUniform().
     {
     int uniformIDint = Uniform(uniformID);
         glUniformMatrix4fv(uniformIDint,1, GL_FALSE, glm::value_ptr(matrix));
     }
virtual void Shader::TransmitUniform (string const & uniformID, vec3 const & vector) const inline override virtual
Transmits the uniform.
Parameters
uniformID The uniform identifier.
vector The vector.
Implements IShader.
Definition at line 155 of file Shader.h.
References TransmitUniform().
     {
     int uniformIDint = Uniform(uniformID);
         glUniform3fv(uniformIDint, 1, glm::value_ptr(vector));
     }
virtual void Shader::TransmitUniform (string const & uniformID, vec2 const & vector) const inline override virtual
Transmits the uniform.
Parameters
uniformID The uniform identifier.
vector The vector.
Implements IShader.
Definition at line 161 of file Shader.h.
References TransmitUniform().
Referenced by TransmitUniform().
   {
     int uniformIDint = Uniform(uniformID);
     glUniform2fv(uniformIDint, 1, glm::value_ptr(vector));
   }
virtual void Shader::TransmitUniformArray (string const & uniformID, mat4 * matrix, int count) const inline override virtual
Transmits the uniform array.
Parameters
uniformID The uniform identifier.
matrix The matrix.
count The count.
Implements IShader.
Definition at line 167 of file Shader.h.
References Uniform().
     {
     int uniformIDint = Uniform(uniformID);
         glUniformMatrix4fv(uniformIDint, count, GL_FALSE, (GLfloat*)matrix);
     }
unsigned int Shader::Uniform (string const & name) const override virtual
Returns the uniform with the specified name.
Parameters
name The name.
Returns
int
Implements IShader.
Definition at line 118 of file Shader.cpp.
Referenced by TransmitUniform(), and TransmitUniformArray().
 {
     return m_uniforms.at(name);
 }
Member Data Documentation
std::unordered_map<string, int> Shader::m_attributes private
The attributes
Definition at line 200 of file Shader.h.
string Shader::m_name private
The m name
Definition at line 180 of file Shader.h.
const char* Shader::m_pFragment private
The fragment shader
Definition at line 195 of file Shader.h.
Referenced by Setup(), Shader(), and ~Shader().
const char* Shader::m_pVertex private
The vertex shader
Definition at line 190 of file Shader.h.
Referenced by Setup(), Shader(), and ~Shader().
unsigned int Shader::m_uid private
The shaders ID
Definition at line 185 of file Shader.h.
Referenced by Setup(), and Shader().
std::unordered_map<string, int> Shader::m_uniforms private
The uniforms
Definition at line 205 of file Shader.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Shader.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Shader.cpp