ICT397 Game Engine: RenderManager Class Reference
RenderManager Class Reference
#include <RenderManager.h>
Public Member Functions
void AddObject (ObjectInstance const *pObject)
Adds the object.
void RemoveObject (ObjectInstance const *pObject)
Removes the object.
virtual void Render (mat4 const &worldMatrix, mat4 const &viewMatrix, mat4 const &projectionMatrix, float time) override
The render method.
float GetFrameRate () const
Gets the frame rate.
Private Member Functions
void UpdateFrameRate (float time)
Updates the frame rate.
Private Attributes
std::unordered_map< IRenderableObject const *, std::vector< ObjectInstance const * > > m_objectMap
The object map
std::vector< float > m_renderTimes
The render times
float m_frameRate
The frame rate
Additional Inherited Members
Static Public Member Functions inherited from Singleton< RenderManager >
static RenderManager & GetInstance ()
Protected Member Functions inherited from Singleton< RenderManager >
Singleton ()
Static Protected Attributes inherited from Singleton< RenderManager >
static RenderManager * p
Detailed Description
Definition at line 21 of file RenderManager.h.
Member Function Documentation
void RenderManager::AddObject (ObjectInstance const * pObject)
Adds the object.
Parameters
pObject The p object.
Definition at line 6 of file RenderManager.cpp.
References ObjectInstance::GetRenderableObject().
 {
  IRenderableObject const* rObject = pObject->GetRenderableObject();
   auto i = m_objectMap.find(rObject);
   if (i == m_objectMap.end())
     m_objectMap.emplace(rObject, CreateVector(pObject));
   else
     i->second.push_back(pObject);
 }
float RenderManager::GetFrameRate () const
Gets the frame rate.
Returns
Definition at line 60 of file RenderManager.cpp.
References m_frameRate.
 {
   return m_frameRate;
 }
void RenderManager::RemoveObject (ObjectInstance const * pObject)
Removes the object.
Parameters
pObject The p object.
Definition at line 16 of file RenderManager.cpp.
References ObjectInstance::GetRenderableObject().
 {
   IRenderableObject const* rObject = pObject->GetRenderableObject();
   auto i = m_objectMap.find(rObject);
   if (i != m_objectMap.end())
   {
     std::vector<ObjectInstance const*>& instances = i->second;
     for (int j = 0; j < instances.size(); j++)
     {
       if (instances[j] == pObject)
       {
         instances.erase(instances.begin() + j);
         break;
       }
     }
   }
 }
void RenderManager::Render (mat4 const & worldMatrix, mat4 const & viewMatrix, mat4 const & projectionMatrix, float time) override virtual
The render method.
Parameters
worldMatrix The world matrix.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
time The time.
Implements IRenderable.
Definition at line 34 of file RenderManager.cpp.
References UpdateFrameRate().
Referenced by RenderManagerAPI::RenderFromCamera().
 {
   int verticesDrawn = 0;
   for (auto i : m_objectMap)
   {
     IRenderableObject const* pObject = i.first;
     std::vector<ObjectInstance const*>& instances = i.second;
     pObject->BindObject();
     for (int meshIndex = 0; meshIndex < pObject->GetMeshCount(); meshIndex++)
     {
       pObject->BindMesh(meshIndex);
       for (int instance = 0; instance < instances.size(); instance++)
       {
         if (instances[instance]->GetVisible())
         {
           verticesDrawn += pObject->GetMesh(meshIndex).GetVertexCount();
           mat4 worldMatrix = instances[instance]->GetTransform();
           int animationIndex = instances[instance]->GetActiveAnimationIndex();
           pObject->Render(worldMatrix, viewMatrix, projectionMatrix, time, animationIndex);
         }
       }
     }
   }
   UpdateFrameRate(time);
 }
void RenderManager::UpdateFrameRate (float time) private
Updates the frame rate.
Parameters
time The time.
Definition at line 65 of file RenderManager.cpp.
Referenced by Render().
 {
   if (m_renderTimes.size() == 60)
     m_renderTimes.erase(m_renderTimes.begin());
   m_renderTimes.push_back(time);
   float totalTime = m_renderTimes[m_renderTimes.size() - 1] - m_renderTimes[0];
   m_frameRate = m_renderTimes.size() / totalTime;
 }
Member Data Documentation
float RenderManager::m_frameRate private
The frame rate
Definition at line 67 of file RenderManager.h.
Referenced by GetFrameRate().
std::unordered_map<IRenderableObject const*, std::vector<ObjectInstance const*> > RenderManager::m_objectMap private
The object map
Definition at line 57 of file RenderManager.h.
std::vector<float> RenderManager::m_renderTimes private
The render times
Definition at line 62 of file RenderManager.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/RenderManager.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/RenderManager.cpp