ICT397 Game Engine: LuaContext Class Reference
LuaContext Class Reference
#include <LuaContext.h>
Public Member Functions
LuaState * GetLuaState ()
LuaContext (LuaContextHandle contextHandle, string const &entryScript)
Initializes a new instance of the LuaContext class.
void Start ()
template<typename R , typename... Args>
void ExposeFunction (string const &functionName, R(*pFunction)(Args...))
template<typename R , typename... Args>
void ExposeFunction (string const &namespaceName, string const &functionName, R(*pFunction)(Args...))
template<typename T >
void AddClass (string const &luaAPIName, string const &className)
template<typename ClassType , typename DataType >
void AddClassDataMember (string const &luaAPIName, string const &className, string const &memberName, DataType dataMember)
template<typename ClassType , typename FunctionType >
void AddClassFunction (string const &luaAPIName, string const &className, string const &functionName, FunctionType *function)
template<typename ClassType , typename ConstructorType >
void AddClassConstructor (string const &luaAPIName, string const &className)
Private Member Functions
void Initialize ()
Private Attributes
LuaState * m_pLuaState
LuaContextHandle m_contextHandle
string m_EntryScriptName
Detailed Description
Definition at line 28 of file LuaContext.h.
Constructor & Destructor Documentation
LuaContext::LuaContext (LuaContextHandle contextHandle, string const & entryScript)
Initializes a new instance of the LuaContext class.
Parameters
contextHandle The context handle.
entryScript The entry script.
Definition at line 17 of file LuaContext.cpp.
References Initialize(), LuaContext(), and m_contextHandle.
Referenced by LuaContext().
   : m_contextHandle(handle)
   , m_EntryScriptName(entryScript)
 {
   m_pLuaState = luabridge::luaL_newstate();
   lua_atpanic(m_pLuaState, &Panic);
   luaL_openlibs(m_pLuaState);
   Initialize();
 }
Member Function Documentation
template<typename T > void LuaContext::AddClass (string const & luaAPIName, string const & className)
Definition at line 82 of file LuaContext.h.
 {
   getGlobalNamespace(m_pLuaState).beginNamespace(luaAPIName.c_str()).beginClass<T>(className.c_str()).endClass().endNamespace();
 }
template<typename ClassType , typename ConstructorType > void LuaContext::AddClassConstructor (string const & luaAPIName, string const & className)
Definition at line 112 of file LuaContext.h.
 {
   getGlobalNamespace(m_pLuaState)
     .beginNamespace(luaAPIName.c_str())
     .beginClass<ClassType>(className.c_str())
     .addConstructor<ConstructorType>()
     .endClass()
     .endNamespace();
 }
template<typename ClassType , typename DataType > void LuaContext::AddClassDataMember (string const & luaAPIName, string const & className, string const & memberName, DataType dataMember)
Definition at line 89 of file LuaContext.h.
 {
   getGlobalNamespace(m_pLuaState)
     .beginNamespace(luaAPIName.c_str())
     .beginClass<ClassType>(className.c_str())
     .addData(memberName.c_str(), dataMember)
     .endClass()
     .endNamespace();
 }
template<typename ClassType , typename FunctionType > void LuaContext::AddClassFunction (string const & luaAPIName, string const & className, string const & functionName, FunctionType * function)
Definition at line 101 of file LuaContext.h.
 {
   getGlobalNamespace(m_pLuaState)
     .beginNamespace(luaAPIName.c_str())
     .beginClass<ClassType>(className.c_str())
     .addFunction(functionName.c_str(), function)
     .endClass()
     .endNamespace();
 }
template<typename R , typename... Args> void LuaContext::ExposeFunction (string const & functionName, R(*)(Args...) pFunction)
Definition at line 76 of file LuaContext.h.
 {
   luabridge::getGlobalNamespace(m_pLuaState).addFunction(functionName.c_str(), pFunction);
 }
template<typename R , typename... Args> void LuaContext::ExposeFunction (string const & namespaceName, string const & functionName, R(*)(Args...) pFunction)
Definition at line 123 of file LuaContext.h.
 {
   luabridge::getGlobalNamespace(m_pLuaState)
     .beginNamespace(namespaceName.c_str())
     .addFunction(functionName.c_str(), pFunction)
     .endNamespace();
 }
LuaState* LuaContext::GetLuaState () inline
Definition at line 32 of file LuaContext.h.
References m_pLuaState.
     {
         return m_pLuaState;
     }
void LuaContext::Initialize () private
Definition at line 33 of file LuaContext.cpp.
Referenced by LuaContext().
 {
   ExposeFunction("GetAPI", GetAPI);
   getGlobalNamespace(m_pLuaState)
     .beginNamespace("context")
     .addVariable("handle", &m_contextHandle, false)
     .endNamespace();
 }
void LuaContext::Start ()
Definition at line 27 of file LuaContext.cpp.
Referenced by LuaManager::CreateContext().
 {
   luaL_dofile(m_pLuaState, m_EntryScriptName.c_str());
 }
Member Data Documentation
LuaContextHandle LuaContext::m_contextHandle private
Definition at line 71 of file LuaContext.h.
Referenced by LuaContext().
string LuaContext::m_EntryScriptName private
Definition at line 72 of file LuaContext.h.
LuaState* LuaContext::m_pLuaState private
Definition at line 68 of file LuaContext.h.
Referenced by GetLuaState().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/LuaContext.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/LuaContext.cpp