ICT397 Game Engine: FXAAEffect Class Reference
FXAAEffect Class Reference
#include <FXAAEffect.h>
Public Member Functions
FXAAEffect ()
Initializes a new instance of the FXAAEffect class.
void Apply (GLuint inputTex, GLuint outputTex, int fxaaSpan)
Applies the FXAA effect.
Private Attributes
FrameBuffer m_fb
The frame buffer
std::unique_ptr< IShader > const & m_pShader
The shader
Detailed Description
Definition at line 17 of file FXAAEffect.h.
Constructor & Destructor Documentation
FXAAEffect::FXAAEffect ()
Initializes a new instance of the FXAAEffect class.
Definition at line 5 of file FXAAEffect.cpp.
References FXAAEffect().
Referenced by FXAAEffect(), and RenderManagerAPI::Initialise().
   : m_pShader(ShaderLibrary::GetInstance().GetShader("FXAAEffect"))
 {
 }
Member Function Documentation
void FXAAEffect::Apply (GLuint inputTex, GLuint outputTex, int fxaaSpan)
Applies the FXAA effect.
Parameters
inputTex The input tex.
outputTex The output tex.
fxaaSpan The fxaa span.
Definition at line 11 of file FXAAEffect.cpp.
 {
   m_pShader->Bind();
   m_fb.Bind();
   m_fb.AttachColour(0, outputTex);
   glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
   m_pShader->TransmitUniform("FXAA_SPAN", fxaaSpan);
   glBindVertexArray(FrameBuffer::FSQuadVAO);
   glActiveTexture(GL_TEXTURE0 + 0);
   glBindTexture(GL_TEXTURE_2D, inputTex);
   m_pShader->TransmitUniform("inputTex0", 0);
   glDrawArrays(GL_QUADS, 0, 4);
   glBindVertexArray(NULL);
   m_fb.Unbind();
 }
Member Data Documentation
FrameBuffer FXAAEffect::m_fb private
The frame buffer
Definition at line 39 of file FXAAEffect.h.
std::unique_ptr<IShader> const& FXAAEffect::m_pShader private
The shader
Definition at line 44 of file FXAAEffect.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/FXAAEffect.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/FXAAEffect.cpp