ICT397 Game Engine: IRenderableObject Class Reference
IRenderableObject Class Reference abstract
#include <IRenderableObject.h>
Public Member Functions
virtual void Initialise ()=0
Initialises this instance.
virtual void Destroy ()=0
Destroys this instance.
virtual void BindObject () const =0
Binds the object.
virtual void BindMesh (int meshIndex) const =0
Binds the mesh.
virtual void Render (mat4 const &worldMatrix, mat4 const &viewMatrix, mat4 const &projectionMatrix, float time, int animationIndex) const =0
The render method.
Public Member Functions inherited from IAnimated
virtual int GetAnimationCount () const =0
virtual string const & GetAnimationName (int animationIndex) const =0
virtual int GetAnimationIndex (string const &animationName) const =0
Public Member Functions inherited from IMeshCollection
std::vector< vec3 > GetVertices () const
Gets the vertices.
std::vector< vec3 > GetNormals () const
Gets the normals.
std::vector< vec3 > GetAABB () const
Gets Axis aligned bounding box - index 0=min, 1=max.
std::vector< int > GetIndices () const
Gets the indices.
int GetVertexCount () const
Gets the vertex count.
int GetNormalCount () const
Gets the normal count.
int GetIndexCount () const
Gets the index count.
virtual IMesh const & GetMesh (int meshIndex) const =0
Gets the mesh at the specified index.
virtual int GetMeshCount () const =0
Gets the mesh count.
Detailed Description
Definition at line 29 of file IRenderableObject.h.
Member Function Documentation
virtual void IRenderableObject::BindMesh (int meshIndex) const pure virtual
Binds the mesh.
Parameters
meshIndex Index of the mesh.
Implemented in RenderableObject.
Referenced by ObjectInstance::Render().
virtual void IRenderableObject::BindObject () const pure virtual
Binds the object.
Implemented in RenderableObject.
Referenced by ObjectInstance::Render().
virtual void IRenderableObject::Destroy () pure virtual
Destroys this instance.
Implemented in RenderableObject.
virtual void IRenderableObject::Initialise () pure virtual
Initialises this instance.
Implemented in RenderableObject.
virtual void IRenderableObject::Render (mat4 const & worldMatrix, mat4 const & viewMatrix, mat4 const & projectionMatrix, float time, int animationIndex) const pure virtual
The render method.
Parameters
worldMatrix The world matrix.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
time The time.
animationIndex Index of the animation.
Implements IAnimatedRenderable.
Implemented in RenderableObject.
Referenced by ObjectInstance::Render().
The documentation for this class was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/IRenderableObject.h