ICT397 Game Engine: SceneDecomposeEffect Class Reference
SceneDecomposeEffect Class Reference
#include <SceneDecomposeEffect.h>
Public Member Functions
SceneDecomposeEffect ()
Initializes a new instance of the SceneDecomposeEffect class.
void Bind (GBuffer const &buffers, int lightingApplied)
Binds the specified buffers.
void Unbind ()
Unbinds this instance.
Private Attributes
FrameBuffer m_fb
The frame buffer
Detailed Description
Definition at line 15 of file SceneDecomposeEffect.h.
Constructor & Destructor Documentation
SceneDecomposeEffect::SceneDecomposeEffect ()
Initializes a new instance of the SceneDecomposeEffect class.
Definition at line 5 of file SceneDecomposeEffect.cpp.
Referenced by RenderManagerAPI::Initialise().
 {
 }
Member Function Documentation
void SceneDecomposeEffect::Bind (GBuffer const & buffers, int lightingApplied)
Binds the specified buffers.
Parameters
buffers The buffers.
lightingApplied The lighting applied.
Definition at line 10 of file SceneDecomposeEffect.cpp.
Referenced by RenderManagerAPI::BeginRender(), RenderManagerAPI::RenderFromCamera(), and RenderManagerAPI::RenderObject().
 {
   m_fb.Bind();
   ShaderLibrary::GetInstance().BindShader("SceneDecomposeEffect");
   ShaderLibrary::GetInstance().CurrentShader()->TransmitUniform("zeroNormals", lightingApplied);
   m_fb.AttachColour(0, buffers.GetColorBuffer());
   m_fb.AttachColour(1, buffers.GetNormalBuffer());
   m_fb.AttachColour(2, buffers.GetWSPositionBuffer());
   m_fb.AttachColour(3, buffers.GetLinearDepthBuffer());
   m_fb.AttachDepth(buffers.GetDepthBuffer());
 }
void SceneDecomposeEffect::Unbind ()
Unbinds this instance.
Definition at line 23 of file SceneDecomposeEffect.cpp.
Referenced by RenderManagerAPI::Present(), and RenderManagerAPI::RenderFromCamera().
 {
   m_fb.Unbind();
 }
Member Data Documentation
FrameBuffer SceneDecomposeEffect::m_fb private
The frame buffer
Definition at line 40 of file SceneDecomposeEffect.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/SceneDecomposeEffect.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/SceneDecomposeEffect.cpp