ICT397 Game Engine: Model Class Reference
Model Class Reference
#include <Model.h>
Public Member Functions
Model (const string &name, const string &filename)
Initializes a new instance of the Model class.
std::vector< vec2 > const & GetTexCoords (TextureType type) const
Gets the texture coords.
std::vector< vec4 > const & GetVertexColours () const
Gets the vertex colours.
std::vector< VertexBoneIDs > const & GetBoneIDs () const
Gets the bone IDs.
std::vector< VertexBoneWeights > const & GetBoneWeights () const
Gets the bone weights.
std::vector< mat4 > GetBoneTransforms (int animationIndex, float time)
Gets the bone transforms.
IndexRange const & GetMeshIndexRange (int meshIndex) const
Gets the mesh index range.
Material const & GetMeshMaterial (int meshIndex) const
Gets the mesh material.
string GetMeshTextureName (int meshIndex, TextureType const &type) const
Gets the name of the mesh texture.
bool HasAnimation () const
Determines whether this instance has animation.
virtual int GetAnimationCount () const override
Gets the animation count.
virtual int GetAnimationIndex (string const &animationName) const override
Gets the index of the animation.
virtual string const & GetAnimationName (int animationIndex) const override
Gets the name of the animation.
virtual IMesh const & GetMesh (int meshIndex) const override
Gets the mesh.
virtual int GetMeshCount () const override
Gets the mesh count.
Public Member Functions inherited from IMeshCollection
std::vector< vec3 > GetVertices () const
Gets the vertices.
std::vector< vec3 > GetNormals () const
Gets the normals.
std::vector< vec3 > GetAABB () const
Gets Axis aligned bounding box - index 0=min, 1=max.
std::vector< int > GetIndices () const
Gets the indices.
int GetVertexCount () const
Gets the vertex count.
int GetNormalCount () const
Gets the normal count.
int GetIndexCount () const
Gets the index count.
Private Member Functions
void LoadAssimpMaterials (const aiScene *pScene, string const &modelDir)
Loads the assimp materials.
void LoadAssimpSkeleton (const aiScene *pScene)
Loads the assimp skeleton.
void LoadAssimpMeshes (const aiScene *pScene)
Loads the assimp meshes.
void LoadVertexAttributes ()
Loads the vertex attributes.
Private Attributes
string m_name
The name
std::vector< Mesh * > m_meshes
The meshes
std::vector< IndexRange > m_meshIndexRanges
The mesh index ranges
std::vector< Material * > m_materials
The materials
Skeleton * pSkeleton
The skeleton
std::vector< vec2 > m_texCoords [2]
The m texture coords
std::vector< vec4 > m_vertexColours
The m vertex colours
std::vector< VertexBoneIDs > m_boneIDs
The m bone IDs
std::vector< VertexBoneWeights > m_boneWeights
The bone weights
bool m_hasAnimation
Whether model has animation
Detailed Description
Definition at line 35 of file Model.h.
Constructor & Destructor Documentation
Model::Model (const string & name, const string & filename)
Initializes a new instance of the Model class.
Parameters
name The name.
filename The filename.
Definition at line 13 of file Model.cpp.
References LoadAssimpMeshes(), LoadAssimpSkeleton(), LoadVertexAttributes(), Model(), and pSkeleton.
Referenced by Model(), and RenderableObject::RenderableObject().
   : m_name(name)
   , pSkeleton(nullptr)
 {
   Assimp::Importer im;
   const aiScene* pScene = im.ReadFile(filename,ASSIMP_LOAD_FLAGS);
   LoadAssimpMaterials(pScene, GetDirectoryFromFileName(filename));
   LoadAssimpSkeleton(pScene);
   LoadAssimpMeshes(pScene);
   LoadVertexAttributes();
 }
Member Function Documentation
int Model::GetAnimationCount () const override virtual
Gets the animation count.
Returns
int
Implements IAnimated.
Definition at line 120 of file Model.cpp.
References Skeleton::GetAnimationCount(), and pSkeleton.
Referenced by RenderableObject::GetAnimationCount().
 {
   if (pSkeleton)
     return pSkeleton->GetAnimationCount();
   else
     return 0;
 }
int Model::GetAnimationIndex (string const & animationName) const override virtual
Gets the index of the animation.
Parameters
animationName Name of the animation.
Returns
int
Implements IAnimated.
Definition at line 128 of file Model.cpp.
References Skeleton::GetAnimationIndex(), and pSkeleton.
Referenced by RenderableObject::GetAnimationIndex().
 {
   return pSkeleton->GetAnimationIndex(animationName);
 }
string const & Model::GetAnimationName (int animationIndex) const override virtual
Gets the name of the animation.
Parameters
animationIndex Index of the animation.
Returns
string
Implements IAnimated.
Definition at line 133 of file Model.cpp.
References Skeleton::GetAnimationName(), and pSkeleton.
Referenced by RenderableObject::GetAnimationName().
 {
   return pSkeleton->GetAnimationName(animationIndex);
 }
std::vector< VertexBoneIDs > const & Model::GetBoneIDs () const
Gets the bone IDs.
Returns
std::vector<VertexBoneIDs>
Definition at line 89 of file Model.cpp.
 {
   return m_boneIDs;
 }
std::vector< mat4 > Model::GetBoneTransforms (int animationIndex, float time)
Gets the bone transforms.
Parameters
animationIndex Index of the animation.
time The time.
Returns
std::vector<mat4>
Definition at line 99 of file Model.cpp.
 {
     return pSkeleton->GetBoneTransforms(animationIndex, time);
 }
std::vector< VertexBoneWeights > const & Model::GetBoneWeights () const
Gets the bone weights.
Returns
std::vector<VertexBoneWeights>
Definition at line 94 of file Model.cpp.
 {
   return m_boneWeights;
 }
IMesh const & Model::GetMesh (int meshIndex) const override virtual
Gets the mesh.
Parameters
meshIndex Index of the mesh.
Returns
IMesh
Implements IMeshCollection.
Definition at line 138 of file Model.cpp.
Referenced by RenderableObject::GetMesh().
 {
   return *(m_meshes[meshIndex]);
 }
int Model::GetMeshCount () const override virtual
Gets the mesh count.
Returns
int
Implements IMeshCollection.
Definition at line 143 of file Model.cpp.
Referenced by RenderableObject::GetMeshCount().
 {
   return int(m_meshes.size());
 }
IndexRange const & Model::GetMeshIndexRange (int meshIndex) const
Gets the mesh index range.
Parameters
meshIndex Index of the mesh.
Returns
IndexRange
Definition at line 104 of file Model.cpp.
Referenced by RenderableObject::Render().
 {
   return m_meshIndexRanges[meshIndex];
 }
Material const & Model::GetMeshMaterial (int meshIndex) const
Gets the mesh material.
Parameters
meshIndex Index of the mesh.
Returns
Material
Definition at line 109 of file Model.cpp.
Referenced by RenderableObject::BindMaterial().
 {
   int materialIndex = m_meshes[meshIndex]->GetMaterialIndex();
   return *(m_materials[materialIndex]);
 }
string Model::GetMeshTextureName (int meshIndex, TextureType const & type) const
Gets the name of the mesh texture.
Parameters
meshIndex Index of the mesh.
type The type.
Returns
string
Definition at line 115 of file Model.cpp.
 {
   return GetMeshMaterial(meshIndex).GetTextureName(type);
 }
std::vector< vec2 > const & Model::GetTexCoords (TextureType type) const
Gets the texture coords.
Parameters
type The type.
Returns
std::vector<vec2>
Definition at line 78 of file Model.cpp.
 {
   return m_texCoords[type];
 }
std::vector< vec4 > const & Model::GetVertexColours () const
Gets the vertex colours.
Returns
std::vector<vec4>
Definition at line 83 of file Model.cpp.
 {
   return m_vertexColours;
 }
bool Model::HasAnimation () const
Determines whether this instance has animation.
Returns
true if this instance has animation; otherwise, false.
Definition at line 148 of file Model.cpp.
References m_hasAnimation.
Referenced by RenderableObject::UpdateAnimation().
 {
   return m_hasAnimation;
 }
void Model::LoadAssimpMaterials (const aiScene * pScene, string const & modelDir) private
Loads the assimp materials.
Parameters
pScene The p scene.
modelDir The model dir.
Definition at line 25 of file Model.cpp.
 {
   char materialName[1024];
   for (uint i = 0; i < pScene->mNumMaterials; i++)
   {
     sprintf_s(materialName, "%s_Material%d", m_name.c_str(), i);
     m_materials.push_back(new Material(materialName, pScene->mMaterials[i], modelDir));
   }
 }
void Model::LoadAssimpMeshes (const aiScene * pScene) private
Loads the assimp meshes.
Parameters
pScene The p scene.
Definition at line 48 of file Model.cpp.
Referenced by Model().
 {
   for (uint i = 0; i < pScene->mNumMeshes; i++)
   {
     m_meshes.push_back(new Mesh(pScene->mMeshes[i], pSkeleton->GetBoneLookup()));
   }
 }
void Model::LoadAssimpSkeleton (const aiScene * pScene) private
Loads the assimp skeleton.
Parameters
pScene The p scene.
Definition at line 35 of file Model.cpp.
Referenced by Model().
 {
   if (pScene->HasAnimations())
   {
     m_hasAnimation = true;
     pSkeleton = new Skeleton(pScene);
   }
   else
   {
     m_hasAnimation = false;
   }
 }
void Model::LoadVertexAttributes () private
Loads the vertex attributes.
Definition at line 56 of file Model.cpp.
References Mesh::m_texCoords.
Referenced by Model().
 {
   int indexCount = 0;
   int vertexCount = 0;
   for (int i = 0; i < m_meshes.size(); i++)
   {
     const Mesh& mesh = *(m_meshes[i]);
     m_meshIndexRanges.push_back(IndexRange{ indexCount, vertexCount, int(mesh.GetIndexCount()) });
     VectorConcatenate(m_texCoords[TT_Diffuse0], mesh.GetTexCoords(TT_Diffuse0));
     VectorConcatenate(m_texCoords[TT_Alpha], mesh.GetTexCoords(TT_Alpha));
     VectorConcatenate(m_vertexColours, mesh.GetVertexColours());
     VectorConcatenate(m_boneIDs, mesh.GetBoneIDs());
     VectorConcatenate(m_boneWeights, mesh.GetBoneWeights());
     indexCount += mesh.GetIndexCount();
     vertexCount += mesh.GetVertexCount();
   }
 }
Member Data Documentation
std::vector<VertexBoneIDs> Model::m_boneIDs private
The m bone IDs
Definition at line 183 of file Model.h.
std::vector<VertexBoneWeights> Model::m_boneWeights private
The bone weights
Definition at line 188 of file Model.h.
bool Model::m_hasAnimation private
Whether model has animation
Definition at line 193 of file Model.h.
Referenced by HasAnimation().
std::vector<Material*> Model::m_materials private
The materials
Definition at line 163 of file Model.h.
std::vector<Mesh*> Model::m_meshes private
The meshes
Definition at line 153 of file Model.h.
std::vector<IndexRange> Model::m_meshIndexRanges private
The mesh index ranges
Definition at line 158 of file Model.h.
string Model::m_name private
The name
Definition at line 148 of file Model.h.
std::vector<vec2> Model::m_texCoords[2] private
The m texture coords
Definition at line 173 of file Model.h.
Referenced by RenderableObject::RenderableObject().
std::vector<vec4> Model::m_vertexColours private
The m vertex colours
Definition at line 178 of file Model.h.
Skeleton* Model::pSkeleton private
The skeleton
Definition at line 168 of file Model.h.
Referenced by GetAnimationCount(), GetAnimationIndex(), GetAnimationName(), and Model().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Model.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Model.cpp