ICT397 Game Engine: ObjectInstanceAPI Class Reference
ObjectInstanceAPI Class Reference
#include <ObjectInstanceAPI.h>
Static Public Member Functions
static void SetOrientation (InstanceHandle instHandle, float in1, float in2, float in3)
Sets affine transformable orientation of object instance.
static void SetScale (InstanceHandle instHandle, float in1, float in2, float in3)
Sets the scale.
static LuaRef GetScale (InstanceHandle instHandle, LuaContextHandle cHandle)
Gets the scale.
static LuaRef GetTranslation (InstanceHandle instHandle, LuaContextHandle cHandle)
Gets the translation.
static void SetAnimation (InstanceHandle instHandle, int isAnimated)
Sets the active animation.
static ObjectInstance * GetInstance (InstanceHandle instHandle)
Gets the object instance.
static void SetTranslation (InstanceHandle instHandle, float x, float y, float z)
Sets the translation.
static void SetRotation (InstanceHandle instHandle, float x, float y, float z)
static void Expose (LuaContextHandle contextHandle, string luaAPIName)
Exposes the API functions.
Detailed Description
Definition at line 23 of file ObjectInstanceAPI.h.
Member Function Documentation
void ObjectInstanceAPI::Expose (LuaContextHandle contextHandle, string luaAPIName) static
Exposes the API functions.
Parameters
contextHandle The context handle.
luaAPIName Name of the lua API.
Definition at line 45 of file ObjectInstanceAPI.cpp.
 {
     LuaContext* pContext = LuaManager::GetInstance().GetContext(contextHandle);
     pContext->ExposeFunction(luaAPIName, "setTranslation", SetTranslation);
     pContext->ExposeFunction(luaAPIName, "setOrientation", SetOrientation);
     pContext->ExposeFunction(luaAPIName, "setScale", SetScale);
     pContext->ExposeFunction(luaAPIName, "getScale", GetScale);
     pContext->ExposeFunction(luaAPIName, "getTranslation", GetTranslation);
     pContext->ExposeFunction(luaAPIName, "setRotation", SetRotation);
     pContext->ExposeFunction(luaAPIName, "setAnimation", SetAnimation);
 }
ObjectInstance * ObjectInstanceAPI::GetInstance (InstanceHandle instHandle) static
Gets the object instance.
Parameters
instHandle The instance handle.
Returns
Object instance
Definition at line 28 of file ObjectInstanceAPI.cpp.
References LuaObjectInstanceManager::GetInstance().
Referenced by SetAnimation(), SetOrientation(), and SetRotation().
 {
     return LuaObjectInstanceManager::GetInstance(instHandle);
 }
LuaRef ObjectInstanceAPI::GetScale (InstanceHandle instHandle, LuaContextHandle cHandle) static
Gets the scale.
Parameters
instHandle The object instance handle.
cHandle The lua context handle.
Returns
LuaRef
Definition at line 33 of file ObjectInstanceAPI.cpp.
References LuaObjectInstanceManager::GetInstance(), AffineTransformable::GetScale(), and ToLuaTable().
 {
     return ToLuaTable(LuaObjectInstanceManager::GetInstance(instHandle)->GetScale(),cHandle);
 }
LuaRef ObjectInstanceAPI::GetTranslation (InstanceHandle instHandle, LuaContextHandle cHandle) static
Gets the translation.
Parameters
instHandle The object instance handle.
cHandle The lua context handle.
Returns
LuaRef
Definition at line 39 of file ObjectInstanceAPI.cpp.
References LuaObjectInstanceManager::GetInstance(), AffineTransformable::GetTranslation(), and ToLuaTable().
 {
     return ToLuaTable(LuaObjectInstanceManager::GetInstance(instHandle)->GetTranslation(), cHandle);
 }
void ObjectInstanceAPI::SetAnimation (InstanceHandle instHandle, int isAnimated) static
Sets the active animation.
Parameters
animationIndex Index of the animation.
Definition at line 23 of file ObjectInstanceAPI.cpp.
References GetInstance(), and ObjectInstance::SetActiveAnimation().
 {
     GetInstance(instHandle)->SetActiveAnimation(isAnimated);
 }
void ObjectInstanceAPI::SetOrientation (InstanceHandle instHandle, float in1, float in2, float in3) static
Sets affine transformable orientation of object instance.
Parameters
instHandle The instance handle.
in1 x value.
in2 The instance handle.
in3 The instance handle.
Definition at line 12 of file ObjectInstanceAPI.cpp.
References GetInstance(), and AffineTransformable::SetOrientation().
 {
     GetInstance(instHandle)->SetOrientation(in1, in2, in3);
 }
void ObjectInstanceAPI::SetRotation (InstanceHandle instHandle, float x, float y, float z) static
Definition at line 58 of file ObjectInstanceAPI.cpp.
References GetInstance(), AffineTransformable::SetPitch(), AffineTransformable::SetRoll(), and AffineTransformable::SetYaw().
 {
     GetInstance(instHandle)->SetRoll(roll);
     GetInstance(instHandle)->SetPitch(pit);
     GetInstance(instHandle)->SetYaw(yaw);
 }
void ObjectInstanceAPI::SetScale (InstanceHandle instHandle, float in1, float in2, float in3) static
Sets the scale.
Parameters
instHandle The instance handle.
in1 Scale x value.
in2 Scale y value.
in3 Scale z value.
Definition at line 17 of file ObjectInstanceAPI.cpp.
 {
     vec3 vec(in1, in2, in3);
     GetInstance(instHandle)->SetScale(vec);
 }
void ObjectInstanceAPI::SetTranslation (InstanceHandle instHandle, float x, float y, float z) static
Sets the translation.
Parameters
instHandle The instance handle.
x The x.
y The y.
z The z.
Definition at line 3 of file ObjectInstanceAPI.cpp.
 {
     vec3 vec(in1, in2, in3);
     GetInstance(instHandle)->SetTranslation(vec);
 }
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/ObjectInstanceAPI.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/ObjectInstanceAPI.cpp