ICT397 Game Engine: IMesh Class Reference
IMesh Class Reference abstract
#include <IMesh.h>
Public Member Functions
virtual std::vector< vec3 > const & GetVertices () const =0
Gets the vertices.
virtual std::vector< vec3 > const & GetNormals () const =0
Gets the normals.
virtual std::vector< int > const & GetIndices () const =0
Gets the indices.
virtual std::vector< vec2 > const & GetTexCoords () const
Gets the texture coords.
int GetTexCoordsCount () const
Gets the texture coords count.
int GetVertexCount () const
Gets the vertex count.
int GetNormalCount () const
Gets the normal count.
int GetIndexCount () const
Gets the index count.
Detailed Description
Definition at line 14 of file IMesh.h.
Member Function Documentation
int IMesh::GetIndexCount () const
Gets the index count.
Returns
int
Definition at line 23 of file IMesh.cpp.
Referenced by IMeshCollection::GetIndexCount(), and OBJWriter::SaveMeshToOBJ().
 {
   return GetIndices().size();
 }
virtual std::vector<int> const& IMesh::GetIndices () const pure virtual
Gets the indices.
Returns
std::vector<vec3>
Implemented in ForestTerrain, Terrain, and Mesh.
int IMesh::GetNormalCount () const
Gets the normal count.
Returns
int
Definition at line 18 of file IMesh.cpp.
Referenced by IMeshCollection::GetNormalCount().
 {
   return GetNormals().size();
 }
virtual std::vector<vec3> const& IMesh::GetNormals () const pure virtual
Gets the normals.
Returns
std::vector<vec3>
Implemented in Terrain, ForestTerrain, and Mesh.
std::vector< vec2 > const & IMesh::GetTexCoords () const virtual
Gets the texture coords.
Returns
std::vector<vec2>
Reimplemented in Terrain.
Definition at line 3 of file IMesh.cpp.
 {
   throw new std::logic_error("Not implemented.");
 }
int IMesh::GetTexCoordsCount () const
Gets the texture coords count.
Returns
int
Definition at line 8 of file IMesh.cpp.
Referenced by OBJWriter::SaveMeshToOBJ().
 {
   return GetTexCoords().size();
 }
int IMesh::GetVertexCount () const
Gets the vertex count.
Returns
int
Definition at line 13 of file IMesh.cpp.
Referenced by IMeshCollection::GetVertexCount(), and OBJWriter::SaveMeshToOBJ().
 {
   return GetVertices().size();
 }
virtual std::vector<vec3> const& IMesh::GetVertices () const pure virtual
Gets the vertices.
Returns
std::vector<vec3>
Implemented in Terrain, ForestTerrain, and Mesh.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/IMesh.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/IMesh.cpp