ICT397 Game Engine: AffineTransformable Class Reference
AffineTransformable Class Reference
#include <AffineTransformable.h>
Public Member Functions
AffineTransformable ()
Initializes a new instance of the AffineTransformable class.
AffineTransformable (vec3 const &translation, float yaw, float pitch, float roll, vec3 const &scale)
Initializes a new instance of the AffineTransformable class.
vec3 const & GetTranslation () const
Gets the translation.
void SetTranslation (vec3 const &translation)
Sets the translation.
void SetTranslation (float x, float y, float z)
Sets the translation.
mat4 const & GetOrientation () const
Gets the orientation.
void SetOrientation (float degYaw, float degPitch, float degRoll)
Sets the orientation.
float GetYaw () const
Gets the yaw.
void SetYaw (float degYaw)
Sets the yaw.
float GetPitch () const
Gets the pitch.
void SetPitch (float degPitch)
Sets the pitch.
float GetRoll () const
Gets the roll.
void SetRoll (float degRoll)
Sets the roll.
vec3 const & GetScale () const
Gets the scale.
void SetScale (vec3 const &scale)
Sets the scale.
mat4 GetTransform () const
Gets the transform.
void SetTransform (mat4 const &transform)
Sets the transform.
void SetTransform (vec3 const &translation, float yaw, float pitch, float roll, vec3 const &scale)
Sets the transform.
Private Attributes
vec3 m_translation
The translation
float m_yaw
The yaw
float m_pitch
The pitch
float m_roll
The roll
vec3 m_scale
The scale
Detailed Description
Definition at line 16 of file AffineTransformable.h.
Constructor & Destructor Documentation
AffineTransformable::AffineTransformable ()
Initializes a new instance of the AffineTransformable class.
Definition at line 12 of file AffineTransformable.cpp.
References AffineTransformable(), m_translation, and SetOrientation().
Referenced by AffineTransformable(), and MCamera::MCamera().
   : m_translation(0)
   , m_scale(1, 1, 1)
 {
   SetOrientation(0, 0, 0);
 }
AffineTransformable::AffineTransformable (vec3 const & translation, float yaw, float pitch, float roll, vec3 const & scale)
Initializes a new instance of the AffineTransformable class.
Parameters
translation The translation.
yaw The yaw.
pitch The pitch.
roll The roll.
scale The scale.
Definition at line 5 of file AffineTransformable.cpp.
References SetOrientation(), SetScale(), and SetTranslation().
 {
   SetTranslation(translation);
   SetOrientation(yaw, pitch, roll);
   SetScale(scale);
 }
Member Function Documentation
mat4 const & AffineTransformable::GetOrientation () const
Gets the orientation.
Returns
mat4
Definition at line 34 of file AffineTransformable.cpp.
Referenced by GetTransform().
 {
   return mat4(quat(vec3(m_pitch, m_yaw, m_roll)));
 }
float AffineTransformable::GetPitch () const
Gets the pitch.
Returns
float
Definition at line 56 of file AffineTransformable.cpp.
References m_pitch.
 {
   return RadToDeg(m_pitch);
 }
float AffineTransformable::GetRoll () const
Gets the roll.
Returns
float
Definition at line 66 of file AffineTransformable.cpp.
References m_roll.
 {
   return RadToDeg(m_roll);
 }
vec3 const & AffineTransformable::GetScale () const
Gets the scale.
Returns
vec3
Definition at line 76 of file AffineTransformable.cpp.
References m_scale.
Referenced by ObjectInstanceAPI::GetScale().
 {
   return m_scale;
 }
mat4 AffineTransformable::GetTransform () const
Gets the transform.
Returns
Definition at line 86 of file AffineTransformable.cpp.
References GetOrientation().
Referenced by ObjectInstance::GetWorldMatrix().
 {
   mat4 translationMatrix = translate(m_translation);
   mat4 rotationMatrix = GetOrientation();
   mat4 scaleMatrix = scale(m_scale);
   return translationMatrix * scaleMatrix * rotationMatrix;
 }
vec3 const & AffineTransformable::GetTranslation () const
Gets the translation.
Returns
vec3
Definition at line 19 of file AffineTransformable.cpp.
References m_translation.
Referenced by MCamera::GetPosition(), and ObjectInstanceAPI::GetTranslation().
 {
   return m_translation;
 }
float AffineTransformable::GetYaw () const
Gets the yaw.
Returns
float
Definition at line 46 of file AffineTransformable.cpp.
References m_yaw.
 {
   return RadToDeg(m_yaw);
 }
void AffineTransformable::SetOrientation (float degYaw, float degPitch, float degRoll)
Sets the orientation.
Parameters
degYaw The yaw in degrees.
degPitch The pitch in degrees.
degRoll The roll in degrees.
Definition at line 39 of file AffineTransformable.cpp.
References SetPitch(), SetRoll(), and SetYaw().
Referenced by AffineTransformable(), ObjectInstanceAPI::SetOrientation(), and SetTransform().
 {
   SetYaw(yaw);
   SetPitch(pitch);
   SetRoll(roll);
 }
void AffineTransformable::SetPitch (float degPitch)
Sets the pitch.
Parameters
degPitch The pitch in degrees.
Definition at line 61 of file AffineTransformable.cpp.
References m_pitch.
Referenced by SetOrientation(), and ObjectInstanceAPI::SetRotation().
 {
   m_pitch = DegToRad(pitch);
 }
void AffineTransformable::SetRoll (float degRoll)
Sets the roll.
Parameters
degRoll The deg roll.
Definition at line 71 of file AffineTransformable.cpp.
References m_roll.
Referenced by SetOrientation(), and ObjectInstanceAPI::SetRotation().
 {
   m_roll = DegToRad(roll);
 }
void AffineTransformable::SetScale (vec3 const & scale)
Sets the scale.
Parameters
scale The scale.
Definition at line 81 of file AffineTransformable.cpp.
References m_scale.
Referenced by AffineTransformable(), and SetTransform().
 {
   m_scale = scale;
 }
void AffineTransformable::SetTransform (mat4 const & transform)
Sets the transform.
Parameters
transform The transform.
Definition at line 94 of file AffineTransformable.cpp.
 {
   quat temp;
   vec3 skew;
   vec4 perspective;
   glm::decompose(transform, m_scale, temp, m_translation, skew, perspective);
   vec3 eulers = RadToDeg(eulerAngles(temp));
   SetOrientation(eulers.y, eulers.x, eulers.z);
 }
void AffineTransformable::SetTransform (vec3 const & translation, float yaw, float pitch, float roll, vec3 const & scale)
Sets the transform.
Parameters
translation The translation.
yaw The yaw.
pitch The pitch.
roll The roll.
scale The scale.
Definition at line 105 of file AffineTransformable.cpp.
References SetOrientation(), SetScale(), and SetTranslation().
Referenced by ObjectInstance::ObjectInstance().
 {
   SetTranslation(translation);
   SetOrientation(yaw, pitch, roll);
   SetScale(scale);
 }
void AffineTransformable::SetTranslation (vec3 const & translation)
Sets the translation.
Parameters
translation The translation.
Definition at line 24 of file AffineTransformable.cpp.
References m_translation.
Referenced by AffineTransformable(), MCamera::SetPosition(), and SetTransform().
 {
   m_translation = translation;
 }
void AffineTransformable::SetTranslation (float x, float y, float z)
Sets the translation.
Parameters
x The x.
y The y.
z The z.
Definition at line 29 of file AffineTransformable.cpp.
 {
   SetTranslation(vec3{ x, y, z });
 }
void AffineTransformable::SetYaw (float degYaw)
Sets the yaw.
Parameters
degYaw The yaw in degrees.
Definition at line 51 of file AffineTransformable.cpp.
References m_yaw.
Referenced by ForestTerrain::GenerateForest(), SetOrientation(), and ObjectInstanceAPI::SetRotation().
 {
   m_yaw = DegToRad(yaw);
 }
Member Data Documentation
float AffineTransformable::m_pitch private
The pitch
Definition at line 33 of file AffineTransformable.h.
Referenced by GetPitch(), and SetPitch().
float AffineTransformable::m_roll private
The roll
Definition at line 38 of file AffineTransformable.h.
Referenced by GetRoll(), and SetRoll().
vec3 AffineTransformable::m_scale private
The scale
Definition at line 43 of file AffineTransformable.h.
Referenced by GetScale(), and SetScale().
vec3 AffineTransformable::m_translation private
The translation
Definition at line 23 of file AffineTransformable.h.
Referenced by AffineTransformable(), GetTranslation(), and SetTranslation().
float AffineTransformable::m_yaw private
The yaw
Definition at line 28 of file AffineTransformable.h.
Referenced by GetYaw(), and SetYaw().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/AffineTransformable.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/AffineTransformable.cpp