ICT397 Game Engine: Skeleton Class Reference
Skeleton Class Reference
#include <Skeleton.h>
Public Member Functions
Skeleton (aiScene const *pScene)
Initializes a new instance of the Skeleton class. Uses the Assimp library. For more information on the Assimp aiScene data structure See: http://www.assimp.org/lib_html/structai_scene.html
std::vector< mat4 > GetBoneTransforms (int animationIndex, float time) const
Gets the bone transforms.
std::vector< mat4 > GetBoneTransforms (string const &animationName, float time) const
Gets the bone transforms.
Bimap< string, int > const & GetBoneLookup () const
Gets the bone lookup.
virtual int GetAnimationCount () const override
Gets the animation count.
virtual int GetAnimationIndex (string const &animationName) const override
Gets the index of the animation.
virtual string const & GetAnimationName (int animationIndex) const override
Gets the name of the animation.
Private Member Functions
void CalculateBoneTransforms (int animationIndex, float time, std::vector< mat4 > &finalTransforms, mat4 parentTransform=mat4(), int boneIndex=0) const
Calculates the bone transforms.
void CreateBoneLookup (aiNode const *pNode)
Creates the bone lookup.
void LoadBones (aiScene const *pScene)
Loads the bones.
void LoadAnimations (aiScene const *pScene)
Loads the animations.
Private Attributes
std::vector< Bone > m_bones
The bones
std::vector< std::unique_ptr< Animation > > m_animations
The animations
Bimap< string, int > m_boneLookup
The bone lookup
Bimap< string, int > m_animationLookup
The animation lookup
mat4 m_globalInverseTransform
The global inverse transform
Detailed Description
Definition at line 31 of file Skeleton.h.
Constructor & Destructor Documentation
Skeleton::Skeleton (aiScene const * pScene)
Initializes a new instance of the Skeleton class. Uses the Assimp library. For more information on the Assimp aiScene data structure See: http://www.assimp.org/lib_html/structai_scene.html
Parameters
pScene The pointer to the scene.
Definition at line 6 of file Skeleton.cpp.
References LoadAnimations(), and LoadBones().
 {
   m_globalInverseTransform = glm::inverse(ASToGLM(pScene->mRootNode->mTransformation));
   LoadBones(pScene);
   LoadAnimations(pScene);
 }
Member Function Documentation
void Skeleton::CalculateBoneTransforms (int animationIndex, float time, std::vector< mat4 > & finalTransforms, mat4 parentTransform = mat4(), int boneIndex = 0) const private
Calculates the bone transforms.
Parameters
animationIndex Index of the animation.
time The time.
finalTransforms The final transforms.
parentTransform The parent transform.
boneIndex Index of the bone.
Definition at line 30 of file Skeleton.cpp.
References Bone::transform.
 {
   const Bone& bone = m_bones[boneIndex];
   const std::unique_ptr<Animation> &pAnimation = m_animations[animationIndex];
   mat4 boneTransform = bone.transform;
   if (pAnimation && pAnimation->HasBoneTransform(boneIndex))
     boneTransform = pAnimation->GetBoneTransform(boneIndex, time);
   mat4 globalTransform = parentTransform * boneTransform;
   finalTransforms[boneIndex] = m_globalInverseTransform * globalTransform * m_bones[boneIndex].offsetMatrix;
   for (int i = 0; i < m_bones[boneIndex].m_childBoneIDs.size(); i++)
     CalculateBoneTransforms(animationIndex, time, finalTransforms, globalTransform, m_bones[boneIndex].m_childBoneIDs[i]);
 }
void Skeleton::CreateBoneLookup (aiNode const * pNode) private
Creates the bone lookup.
Parameters
pNode The p node.
Definition at line 46 of file Skeleton.cpp.
 {
   int boneIndex = m_boneLookup.Count();
   string boneName = pNode->mName.data;
   if (!m_boneLookup.HasKey(boneName))
   {
     m_boneLookup.Add(pNode->mName.data, boneIndex);
     m_bones.emplace_back();
     m_bones[boneIndex].m_ID = boneIndex;
     m_bones[boneIndex].transform = ASToGLM(pNode->mTransformation);
     for (uint i = 0; i < pNode->mNumChildren; i++)
     {
       CreateBoneLookup(pNode->mChildren[i]);
       m_bones[boneIndex].m_childBoneIDs.push_back(m_boneLookup.GetValue(pNode->mChildren[i]->mName.data));
     }
   }
 }
int Skeleton::GetAnimationCount () const override virtual
Gets the animation count.
Returns
int
Implements IAnimated.
Definition at line 101 of file Skeleton.cpp.
Referenced by Model::GetAnimationCount().
 {
   return m_animations.size();
 }
int Skeleton::GetAnimationIndex (string const & animationName) const override virtual
Gets the index of the animation.
Parameters
animationName Name of the animation.
Returns
int
Implements IAnimated.
Definition at line 106 of file Skeleton.cpp.
Referenced by Model::GetAnimationIndex().
 {
   return m_animationLookup.GetValue(animationName);
 }
string const & Skeleton::GetAnimationName (int animationIndex) const override virtual
Gets the name of the animation.
Parameters
animationIndex Index of the animation.
Returns
string
Implements IAnimated.
Definition at line 111 of file Skeleton.cpp.
Referenced by Model::GetAnimationName().
 {
   return m_animationLookup.GetKey(animationIndex);
 }
Bimap< string, int > const & Skeleton::GetBoneLookup () const
Gets the bone lookup.
Returns
A reference to the bone lookup Bimap. Bimap<string,int>
Definition at line 96 of file Skeleton.cpp.
 {
   return m_boneLookup;
 }
std::vector< mat4 > Skeleton::GetBoneTransforms (int animationIndex, float time) const
Gets the bone transforms.
Parameters
animationIndex Index of the animation.
time The time.
Returns
std::vector<mat4>
Definition at line 13 of file Skeleton.cpp.
 {
   std::vector<mat4> finalTransforms;
   finalTransforms.resize(m_bones.size());
   if(animationIndex >= 0)
     CalculateBoneTransforms(animationIndex, time, finalTransforms);
   return finalTransforms;
 }
std::vector< mat4 > Skeleton::GetBoneTransforms (string const & animationName, float time) const
Gets the bone transforms.
Parameters
animationName Name of the animation.
time The time.
Returns
std::vector<mat4>
Definition at line 22 of file Skeleton.cpp.
 {
   int animationIndex = m_animationLookup.GetValue(animationName);
   std::vector<mat4> finalTransforms;
   CalculateBoneTransforms(animationIndex, time, finalTransforms);
   return finalTransforms;
 }
void Skeleton::LoadAnimations (aiScene const * pScene) private
Loads the animations.
Parameters
pScene The pointer to the scene.
Definition at line 81 of file Skeleton.cpp.
Referenced by Skeleton().
 {
   for (uint i = 0; i < pScene->mNumAnimations; i++)
   {
     //Use emplace_back to construct an item in place with this as arguments.
     //Cannot create one and push_back since it tries to copy and push in to the vector
     m_animations.emplace_back(new Animation(pScene->mAnimations[i], m_boneLookup));
   }
   for (int i = 0; i < m_animations.size(); i++)
   {
     m_animationLookup.Add(m_animations[i]->GetName(), i);
   }
 }
void Skeleton::LoadBones (aiScene const * pScene) private
Loads the bones.
Parameters
pScene The pointer to the scene.
Definition at line 67 of file Skeleton.cpp.
Referenced by Skeleton().
 {
   CreateBoneLookup(pScene->mRootNode);
   for (uint meshIndex = 0; meshIndex < pScene->mNumMeshes; meshIndex++)
   {
     const aiMesh* m = pScene->mMeshes[meshIndex];
     for (uint b = 0; b < m->mNumBones; b++)
     {
       int boneIndex = m_boneLookup.GetValue(m->mBones[b]->mName.data);
       m_bones[boneIndex].offsetMatrix = ASToGLM(m->mBones[b]->mOffsetMatrix);
     }
   }
 }
Member Data Documentation
Bimap<string, int> Skeleton::m_animationLookup private
The animation lookup
Definition at line 106 of file Skeleton.h.
std::vector<std::unique_ptr<Animation> > Skeleton::m_animations private
The animations
Definition at line 96 of file Skeleton.h.
Bimap<string, int> Skeleton::m_boneLookup private
The bone lookup
Definition at line 101 of file Skeleton.h.
std::vector<Bone> Skeleton::m_bones private
The bones
Definition at line 91 of file Skeleton.h.
mat4 Skeleton::m_globalInverseTransform private
The global inverse transform
Definition at line 111 of file Skeleton.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Skeleton.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Skeleton.cpp