ICT397 Game Engine: ObjectInstance Class Reference
ObjectInstance Class Reference
#include <ObjectInstance.h>
Public Member Functions
ObjectInstance (IRenderableObject *object, vec3 const &coords=glm::vec3(0, 0, 0), vec3 const &scaleFactor=vec3(1, 1, 1), float yaw=0, float pitch=0)
Initializes a new instance of the ObjectInstance struct.
std::vector< vec3 > GetVertices (mat4 const &parentModelMatrix=mat4()) const
Gets the vertices.
mat4 GetWorldMatrix () const
Gets the world matrix.
virtual void Render (mat4 const &worldMatrix, mat4 const &viewMatrix, mat4 const &projectionMatrix, float time=0) override
The render method.
virtual void SetActiveAnimation (int animationIndex) override
Sets the active animation.
virtual int GetActiveAnimationIndex () const override
Gets the index of the active animation.
virtual int GetAnimationCount () const override
Gets the animation count.
virtual string const & GetAnimationName (int animationIndex) const override
Gets the name of the animation.
virtual int GetAnimationIndex (string const &animationName) const override
Gets the index of the animation.
IRenderableObject const * GetRenderableObject () const
Gets the renderable object.
void SetVisible (bool vis)
Sets whether the instance is visible.
bool GetVisible () const
Gets whether the object is visible.
Public Member Functions inherited from IAnimatable
void SetActiveAnimation (string const &animationName)
Sets the active animation.
string const & GetActiveAnimationName () const
Gets the name of the active animation.
Public Member Functions inherited from AffineTransformable
AffineTransformable ()
Initializes a new instance of the AffineTransformable class.
AffineTransformable (vec3 const &translation, float yaw, float pitch, float roll, vec3 const &scale)
Initializes a new instance of the AffineTransformable class.
vec3 const & GetTranslation () const
Gets the translation.
void SetTranslation (vec3 const &translation)
Sets the translation.
void SetTranslation (float x, float y, float z)
Sets the translation.
mat4 const & GetOrientation () const
Gets the orientation.
void SetOrientation (float degYaw, float degPitch, float degRoll)
Sets the orientation.
float GetYaw () const
Gets the yaw.
void SetYaw (float degYaw)
Sets the yaw.
float GetPitch () const
Gets the pitch.
void SetPitch (float degPitch)
Sets the pitch.
float GetRoll () const
Gets the roll.
void SetRoll (float degRoll)
Sets the roll.
vec3 const & GetScale () const
Gets the scale.
void SetScale (vec3 const &scale)
Sets the scale.
mat4 GetTransform () const
Gets the transform.
void SetTransform (mat4 const &transform)
Sets the transform.
void SetTransform (vec3 const &translation, float yaw, float pitch, float roll, vec3 const &scale)
Sets the transform.
Private Attributes
IRenderableObject * m_pRenderableObject
The renderable object
int m_activeAnimation
The active animation
bool m_visible = true
Whether the instance is visible
Detailed Description
Definition at line 19 of file ObjectInstance.h.
Constructor & Destructor Documentation
ObjectInstance::ObjectInstance (IRenderableObject * object, vec3 const & coords = glm::vec3(0, 0, 0), vec3 const & scaleFactor = vec3(1, 1, 1), float yaw = 0, float pitch = 0)
Initializes a new instance of the ObjectInstance struct.
Parameters
object The object.
coords The coords.
scaleFactor The scale factor.
yaw The yaw.
pitch The pitch.
Definition at line 5 of file ObjectInstance.cpp.
References m_activeAnimation, m_pRenderableObject, and AffineTransformable::SetTransform().
   : m_pRenderableObject(object)
   , m_activeAnimation(-1)
 {
   SetTransform(coords, yaw, pitch, 0, scaleFactor);
   RenderManager::GetInstance().AddObject(this);
 }
Member Function Documentation
int ObjectInstance::GetActiveAnimationIndex () const override virtual
Gets the index of the active animation.
Returns
int
Implements IAnimatable.
Definition at line 65 of file ObjectInstance.cpp.
References m_activeAnimation.
 {
   return m_activeAnimation;
 }
int ObjectInstance::GetAnimationCount () const override virtual
Gets the animation count.
Returns
int
Implements IAnimated.
Definition at line 70 of file ObjectInstance.cpp.
References IAnimated::GetAnimationCount(), and m_pRenderableObject.
 {
   return m_pRenderableObject->GetAnimationCount();
 }
int ObjectInstance::GetAnimationIndex (string const & animationName) const override virtual
Gets the index of the animation.
Parameters
animationName Name of the animation.
Returns
int
Implements IAnimated.
Definition at line 80 of file ObjectInstance.cpp.
References IAnimated::GetAnimationIndex(), and m_pRenderableObject.
 {
   return m_pRenderableObject->GetAnimationIndex(animationName);
 }
string const & ObjectInstance::GetAnimationName (int animationIndex) const override virtual
Gets the name of the animation.
Parameters
animationIndex Index of the animation.
Returns
string
Implements IAnimated.
Definition at line 75 of file ObjectInstance.cpp.
References IAnimated::GetAnimationName(), and m_pRenderableObject.
 {
   return m_pRenderableObject->GetAnimationName(animationIndex);
 }
IRenderableObject const * ObjectInstance::GetRenderableObject () const
Gets the renderable object.
Returns
IRenderableObject
Definition at line 85 of file ObjectInstance.cpp.
References m_pRenderableObject.
Referenced by RenderManager::AddObject(), and RenderManager::RemoveObject().
 {
   return m_pRenderableObject;
 }
std::vector< vec3 > ObjectInstance::GetVertices (mat4 const & parentModelMatrix = mat4()) const
Gets the vertices.
Parameters
parentModelMatrix The parent model matrix.
Returns
std::vector<vec3>
Definition at line 40 of file ObjectInstance.cpp.
References GetWorldMatrix().
 {
   std::vector<vec3> verts;
   verts = m_pRenderableObject->GetVertices();
   mat4 worldMatrix = parentWorldMatrix * GetWorldMatrix();
   vec4 temp;
   for (uint32_t i = 0; i < verts.size(); i++)
   {
     temp = vec4(verts[i], 1);
     temp = worldMatrix * temp;
     verts[i].x = temp.x;
     verts[i].y = temp.y;
     verts[i].z = temp.z;
   }
   return verts;
 }
bool ObjectInstance::GetVisible () const
Gets whether the object is visible.
Returns
bool
Definition at line 18 of file ObjectInstance.cpp.
References m_visible.
 {
   return m_visible;
 }
mat4 ObjectInstance::GetWorldMatrix () const
Gets the world matrix.
Returns
mat4
Definition at line 35 of file ObjectInstance.cpp.
References AffineTransformable::GetTransform().
Referenced by GetVertices(), and Render().
 {
   return GetTransform();
 }
void ObjectInstance::Render (mat4 const & worldMatrix, mat4 const & viewMatrix, mat4 const & projectionMatrix, float time = 0) override virtual
The render method.
Parameters
worldMatrix The world matrix.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
time The time.
Implements IRenderable.
Definition at line 23 of file ObjectInstance.cpp.
References IRenderableObject::BindMesh(), IRenderableObject::BindObject(), IMeshCollection::GetMeshCount(), GetWorldMatrix(), m_activeAnimation, m_pRenderableObject, and IRenderableObject::Render().
Referenced by RenderManagerAPI::RenderObject().
 {
   m_pRenderableObject->BindObject();
   for (int meshIndex = 0; meshIndex < m_pRenderableObject->GetMeshCount(); meshIndex++)
   {
     m_pRenderableObject->BindMesh(meshIndex);
     m_pRenderableObject->Render(parentWorldMatrix * GetWorldMatrix(), viewMatrix, projectionMatrix, time, m_activeAnimation);
   }
 }
void ObjectInstance::SetActiveAnimation (int animationIndex) override virtual
Sets the active animation.
Parameters
animationIndex Index of the animation.
Implements IAnimatable.
Definition at line 60 of file ObjectInstance.cpp.
References m_activeAnimation.
Referenced by ObjectInstanceAPI::SetAnimation().
 {
   m_activeAnimation = animationIndex;
 }
void ObjectInstance::SetVisible (bool vis)
Sets whether the instance is visible.
Parameters
vis if set to true [vis].
Definition at line 13 of file ObjectInstance.cpp.
References m_visible.
 {
   m_visible = vis;
 }
Member Data Documentation
int ObjectInstance::m_activeAnimation private
The active animation
Definition at line 117 of file ObjectInstance.h.
Referenced by GetActiveAnimationIndex(), ObjectInstance(), Render(), and SetActiveAnimation().
IRenderableObject* ObjectInstance::m_pRenderableObject private
The renderable object
Definition at line 112 of file ObjectInstance.h.
Referenced by GetAnimationCount(), GetAnimationIndex(), GetAnimationName(), GetRenderableObject(), ObjectInstance(), and Render().
bool ObjectInstance::m_visible = true private
Whether the instance is visible
Definition at line 122 of file ObjectInstance.h.
Referenced by GetVisible(), and SetVisible().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/ObjectInstance.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/ObjectInstance.cpp