ICT397 Game Engine: RenderManagerAPI Class Reference
RenderManagerAPI Class Reference
#include <RenderManagerAPI.h>
Static Public Member Functions
static void Initialise ()
Initialises this instance.
static void Render (LuaRef worldMatrix, LuaRef viewMatrix, LuaRef projectionMatrix, float time)
Renders the specified world matrix.
static void RenderObject (int camID, float time, int instanceHandle, int lightingApplied)
Renders the object.
static void RenderFromCamera (int camID, float time)
Renders from camera.
static void AddObject (int object)
Adds the object.
static void RemoveObject (int object)
Removes the object.
static void BeginRender ()
Begins the render.
static void EndRender ()
Ends the render.
static void SetFillMode (int fillMode)
Sets the fill mode (wireframe = 0, fill = 1).
static void Present ()
Applies post processing and displays resulting texture on screen
static void Expose (LuaContextHandle contextHandle, string luaAPIName)
Exposes the lua API
Detailed Description
Definition at line 57 of file RenderManagerAPI.h.
Member Function Documentation
void RenderManagerAPI::AddObject (int object) static
Adds the object.
Parameters
object The object.
Definition at line 29 of file RenderManagerAPI.cpp.
References LuaObjectInstanceManager::GetInstance().
 {
     ObjectInstance * obj = LuaObjectInstanceManager::GetInstance(object);
     RenderManager::GetInstance().AddObject(obj);
 }
void RenderManagerAPI::BeginRender () static
Begins the render.
Definition at line 75 of file RenderManagerAPI.cpp.
References IEngine::BeginRender(), SceneDecomposeEffect::Bind(), buffers, EngineAPI::GetEngine(), and pDecomposeEffect.
 {
   pDecomposeEffect->Bind(*buffers, 1);
   EngineAPI::GetEngine()->BeginRender();
 }
void RenderManagerAPI::EndRender () static
Ends the render.
Definition at line 81 of file RenderManagerAPI.cpp.
References IEngine::EndRender(), and EngineAPI::GetEngine().
 {
   EngineAPI::GetEngine()->EndRender();
 }
void RenderManagerAPI::Expose (LuaContextHandle contextHandle, string luaAPIName) static
Exposes the lua API
Parameters
contextHandle The context handle.
luaAPIName Name of the lua API.
Definition at line 144 of file RenderManagerAPI.cpp.
 {
   LuaContext* pContext = LuaManager::GetInstance().GetContext(contextHandle);
   pContext->ExposeFunction(luaAPIName, "render", Render);
   pContext->ExposeFunction(luaAPIName, "renderFromCamera", RenderFromCamera);
   pContext->ExposeFunction(luaAPIName, "renderObject", RenderObject);
   pContext->ExposeFunction(luaAPIName, "removeObject", RemoveObject);
   pContext->ExposeFunction(luaAPIName, "addObject", AddObject);
   pContext->ExposeFunction(luaAPIName, "initialise", Initialise);
   pContext->ExposeFunction(luaAPIName, "present", Present);
   pContext->ExposeFunction(luaAPIName, "beginRender", BeginRender);
   pContext->ExposeFunction(luaAPIName, "endRender", EndRender);
   pContext->ExposeFunction(luaAPIName, "setFillMode", SetFillMode);
 }
void RenderManagerAPI::Initialise () static
Initialises this instance.
Definition at line 41 of file RenderManagerAPI.cpp.
References BloomEffect::BloomEffect(), buffers, DepthThresholdEffect::DepthThresholdEffect(), DirectionalLightingEffect::DirectionalLightingEffect(), FXAAEffect::FXAAEffect(), GBuffer::GBuffer(), GodRaysEffect::GodRaysEffect(), FrameBuffer::Initialize(), MultiplicativeBlendEffect::MultiplicativeBlendEffect(), pBlendEffect, pBloomEffect, pDecomposeEffect, pFXAAEffect, pLightingEffect, pRayEffect, pThresholdEffect, SceneDecomposeEffect::SceneDecomposeEffect(), and BloomEffect::tempTex.
 {
     TextureLibrary::GetInstance().InitTextureLibrary();
   FrameBuffer::Initialize();
     pDecomposeEffect = new SceneDecomposeEffect();
     pThresholdEffect = new DepthThresholdEffect();
     pRayEffect = new GodRaysEffect();
     pBloomEffect = new BloomEffect();
     pFXAAEffect = new FXAAEffect();
     pBlendEffect = new MultiplicativeBlendEffect();
     pLightingEffect = new DirectionalLightingEffect();
   buffers = new GBuffer();
     godRayMaskTexture = CreateVec3Texture();
     finalTex = CreateVec3Texture();
   tempTex = CreateVec3Texture();
   tempTex2 = CreateVec3Texture();
 }
void RenderManagerAPI::Present () static
Applies post processing and displays resulting texture on screen
Definition at line 87 of file RenderManagerAPI.cpp.
References fillmode, pDecomposeEffect, and SceneDecomposeEffect::Unbind().
 {
   if (fillmode == 0)
   {
     FrameBuffer::Display(buffers->GetColorBuffer());
   }
   else
   {
     pDecomposeEffect->Unbind();
     pLightingEffect->Apply(buffers->GetNormalBuffer(), tempTex, vec3(0.5, 0.5, 0.5), vec3(1, -1, 1));
     pBlendEffect->Apply(tempTex, buffers->GetColorBuffer(), tempTex2);
     pBloomEffect->Apply(tempTex2,finalTex, 1);
     FrameBuffer::Display(tempTex2);
   }
 }
void RenderManagerAPI::RemoveObject (int object) static
Removes the object.
Parameters
object The object.
Definition at line 35 of file RenderManagerAPI.cpp.
References LuaObjectInstanceManager::GetInstance().
 {
     ObjectInstance * obj = LuaObjectInstanceManager::GetInstance(object);
     RenderManager::GetInstance().RemoveObject(obj);
 }
void RenderManagerAPI::Render (LuaRef worldMatrix, LuaRef viewMatrix, LuaRef projectionMatrix, float time) static
Renders the specified world matrix.
Parameters
worldMatrix The world matrix.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
time The time.
todo fix broken
Definition at line 20 of file RenderManagerAPI.cpp.
 {
     mat4 world = FromLuaTable<mat4>(worldMatrix);
     mat4 view = FromLuaTable<mat4>(viewMatrix);
     mat4 proj = FromLuaTable<mat4>(projectionMatrix);
     RenderManager::GetInstance().Render(world,view,proj, time);
 }
void RenderManagerAPI::RenderFromCamera (int camID, float time) static
Renders from camera.
Parameters
camID The cam identifier.
time The time.
Definition at line 118 of file RenderManagerAPI.cpp.
References SceneDecomposeEffect::Bind(), buffers, MCamera::getProjectionMatrix(), MCamera::getViewMatrix(), pDecomposeEffect, RenderManager::Render(), and SceneDecomposeEffect::Unbind().
 {
     MCamera *cam = InstanceManager<MCamera>().GetInstance().GetInst(camID);
     mat4 world;
     RenderManager rend = RenderManager::GetInstance();
     static bool renderDepth = true;
     vec3 lightPos;
     lightPos.x = -cos(PI * time / 60) * 10000;
     lightPos.y = sin(PI * time / 60) * 10000;
     pDecomposeEffect->Bind(*buffers, 1);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     rend.Render(world, cam->getViewMatrix(), cam->getProjectionMatrix(), time);
     pDecomposeEffect->Unbind();
     FrameBuffer::Display(buffers->GetColorBuffer());
 }
void RenderManagerAPI::RenderObject (int camID, float time, int instanceHandle, int lightingApplied) static
Renders the object.
Parameters
camID The cam identifier.
time The time.
instanceHandle The instance handle.
lightingApplied The lighting applied.
Definition at line 64 of file RenderManagerAPI.cpp.
References SceneDecomposeEffect::Bind(), buffers, LuaObjectInstanceManager::GetInstance(), MCamera::getProjectionMatrix(), MCamera::getViewMatrix(), pDecomposeEffect, and ObjectInstance::Render().
 {
   MCamera *cam = InstanceManager<MCamera>().GetInstance().GetInst(camID);
   mat4 world;
   pDecomposeEffect->Bind(*buffers, lightingApplied);
   LuaObjectInstanceManager::GetInstance(instanceHandle)->Render(mat4(), cam->getViewMatrix(), cam->getProjectionMatrix(), time);
 }
void RenderManagerAPI::SetFillMode (int fillMode) static
Sets the fill mode (wireframe = 0, fill = 1).
Parameters
fillMode The fill mode.
Definition at line 103 of file RenderManagerAPI.cpp.
References fillmode.
 {
   fillmode = fillMode;
   switch (fillMode)
   {
     case FM_Line:
       glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
       break;
     case FM_Fill:
       glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
       break;
   }
 }
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/RenderManagerAPI.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/RenderManagerAPI.cpp