ICT397 Game Engine: MPlayer Class Reference
MPlayer Class Reference
#include <MPlayer.h>
Public Member Functions
MPlayer ()
Default constructor for MPlayer.
MCamera * GetCamera () const
Get the player camera.
vec3 GetPosition () const
Returns vec3 of the player's position.
void SetPosition (vec3 const &position)
Sets player's position.
mRay GetPickingRay () const
Get's the player's Ray.
float GetHeight () const
Get height of camera.
void SetHeight (float Height)
Set height of camera.
Protected Attributes
MCamera * camera
the players camera
float height = 150
the players height
Detailed Description
Definition at line 31 of file MPlayer.h.
Constructor & Destructor Documentation
MPlayer::MPlayer ()
Default constructor for MPlayer.
Definition at line 4 of file MPlayer.cpp.
References camera, and MCamera::MCamera().
 {
     camera = new MCamera();
 }
Member Function Documentation
MCamera * MPlayer::GetCamera () const
Get the player camera.
Definition at line 9 of file MPlayer.cpp.
References camera.
 {
     return camera;
 }
float MPlayer::GetHeight () const
Get height of camera.
Returns
float
Definition at line 38 of file MPlayer.cpp.
References height.
 {
     return height;
 }
mRay MPlayer::GetPickingRay () const
Get's the player's Ray.
Returns
mRay
Definition at line 33 of file MPlayer.cpp.
References camera, MCamera::Forward(), and MCamera::GetPosition().
 {
     return mRay{ camera->GetPosition(),camera->Forward() };
 }
vec3 MPlayer::GetPosition () const
Returns vec3 of the player's position.
Returns
vec3
Definition at line 14 of file MPlayer.cpp.
Referenced by SetHeight().
 {
     return camera->GetPosition() - vec3{ 0, height, 0 };
 }
void MPlayer::SetHeight (float Height)
Set height of camera.
Parameters
Height - the height of the camera
Returns
void
Definition at line 24 of file MPlayer.cpp.
References GetPosition(), and height.
 {
     vec3 pos = GetPosition();
     height = Height;
     camera->SetPosition(pos + vec3(0, height, 0));
 }
void MPlayer::SetPosition (vec3 const & position)
Sets player's position.
Parameters
position - the position of the camera
Returns
void
Definition at line 19 of file MPlayer.cpp.
 {
     camera->SetPosition(position + vec3{ 0, height, 0 });
 }
Member Data Documentation
MCamera* MPlayer::camera protected
the players camera
Definition at line 35 of file MPlayer.h.
Referenced by GetCamera(), GetPickingRay(), and MPlayer().
float MPlayer::height = 150 protected
the players height
Definition at line 36 of file MPlayer.h.
Referenced by GetHeight(), and SetHeight().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/MPlayer.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/MPlayer.cpp