ICT397 Game Engine: LuaVectorUtility Class Reference
LuaVectorUtility Class Reference
#include <LuaVectorUtility.h>
Static Public Member Functions
static LuaRef vec3_Normalize (LuaRef value, LuaContextHandle contextHandle)
Vec3 normalize.
static LuaRef vec3_Sum (LuaRef a, LuaRef b, LuaContextHandle contextHandle)
Vec3 sum.
static LuaRef vec3_Subtract (LuaRef a, LuaRef b, LuaContextHandle contextHandle)
Vec3 subtract.
static LuaRef vec3_ScalarMultiply (LuaRef value, float scalar, LuaContextHandle contextHandle)
Vec3 scalar multiply.
static LuaRef vec3_Multiply (LuaRef vec1, LuaRef vec2, LuaContextHandle contextHandle)
Vec3 multiply.
static LuaRef vec3_CreateEmpty (LuaContextHandle contextHandle)
Vec3 create empty.
static bool vec3_Equals (LuaRef a, LuaRef b)
Vec3 equals.
static LuaRef mat4_CreateIdentity (LuaContextHandle contextHandle)
Mat4 create identity.
static void Expose (LuaContextHandle contextHandle, string luaAPIName)
Exposes the API to lua.
Detailed Description
Definition at line 19 of file LuaVectorUtility.h.
Member Function Documentation
void LuaVectorUtility::Expose (LuaContextHandle contextHandle, string luaAPIName) static
Exposes the API to lua.
Parameters
contextHandle The context handle.
luaAPIName Name of the lua API.
Definition at line 73 of file LuaVectorUtility.cpp.
 {
     LuaContext* pContext = LuaManager::GetInstance().GetContext(contextHandle);
     pContext->ExposeFunction(luaAPIName, "vec3_Equals", vec3_Equals);
     pContext->ExposeFunction(luaAPIName, "vec3_CreateEmpty", vec3_CreateEmpty);
     pContext->ExposeFunction(luaAPIName, "vec3_Normalize", vec3_Normalize);
     pContext->ExposeFunction(luaAPIName, "vec3_Sum", vec3_Sum);
     pContext->ExposeFunction(luaAPIName, "vec3_Subtract", vec3_Subtract);
     pContext->ExposeFunction(luaAPIName, "mat4_CreateIdentity", mat4_CreateIdentity);
     pContext->ExposeFunction(luaAPIName, "vec3_ScalarMultiply", vec3_ScalarMultiply);
     pContext->ExposeFunction(luaAPIName, "vec3_Multiply", vec3_Multiply);
 }
LuaRef LuaVectorUtility::mat4_CreateIdentity (LuaContextHandle contextHandle) static
Mat4 create identity.
Parameters
contextHandle The context handle.
Returns
Definition at line 44 of file LuaVectorUtility.cpp.
References ToLuaTable().
 {
     mat4 empty;
     return ToLuaTable(empty, contextHandle);
 }
LuaRef LuaVectorUtility::vec3_CreateEmpty (LuaContextHandle contextHandle) static
Vec3 create empty.
Parameters
contextHandle The context handle.
Returns
LuaRef
Definition at line 65 of file LuaVectorUtility.cpp.
References ToLuaTable().
 {
     vec3 empty;
     return ToLuaTable(empty, contextHandle);
 }
bool LuaVectorUtility::vec3_Equals (LuaRef a, LuaRef b) static
Vec3 equals.
Parameters
a a.
b The b.
Returns
bool
Definition at line 58 of file LuaVectorUtility.cpp.
 {
     if (FromLuaTable<vec3>(a) == FromLuaTable<vec3>(b))
       return true;
     return false;
 }
LuaRef LuaVectorUtility::vec3_Multiply (LuaRef vec1, LuaRef vec2, LuaContextHandle contextHandle) static
Vec3 multiply.
Parameters
vec1 A vec3 to multiply.
vec2 Second vec3 to multiply.
contextHandle The context handle.
Returns
LuaRef
Definition at line 24 of file LuaVectorUtility.cpp.
References ToLuaTable().
 {
     vec3 veca = FromLuaTable<vec3>(vec1);
     vec3 vecb = FromLuaTable<vec3>(vec2);
     vec3 finalVec = veca * vecb;
     return ToLuaTable(finalVec, contextHandle);
 }
LuaRef LuaVectorUtility::vec3_Normalize (LuaRef value, LuaContextHandle contextHandle) static
Vec3 normalize.
Parameters
value The value to normaliz.
contextHandle The context handle.
Returns
LuaRef
Definition at line 6 of file LuaVectorUtility.cpp.
References ToLuaTable().
 {
   vec3 vec = FromLuaTable<vec3>(value);
     vec = normalize(vec);
     return ToLuaTable(vec, contextHandle);
 }
LuaRef LuaVectorUtility::vec3_ScalarMultiply (LuaRef value, float scalar, LuaContextHandle contextHandle) static
Vec3 scalar multiply.
Parameters
value The vec3 to multiply.
scalar The scalar to multiply.
contextHandle The context handle.
Returns
LuaRef
Definition at line 51 of file LuaVectorUtility.cpp.
References ToLuaTable().
 {
     vec3 vec = FromLuaTable<vec3>(value);
   vec3 finalVec = vec * scalar;
     return ToLuaTable(finalVec, contextHandle);
 }
LuaRef LuaVectorUtility::vec3_Subtract (LuaRef a, LuaRef b, LuaContextHandle contextHandle) static
Vec3 subtract.
Parameters
a Value 1 to subtract.
b Value 2 to subtract.
contextHandle The context handle.
Returns
LuaRef
Definition at line 35 of file LuaVectorUtility.cpp.
References ToLuaTable().
 {
     vec3 vec1 = FromLuaTable<vec3>(a);
     vec3 vec2 = FromLuaTable<vec3>(b);
     vec3 finalVec = vec1 - vec2;
   return ToLuaTable(finalVec, contextHandle);
 }
LuaRef LuaVectorUtility::vec3_Sum (LuaRef a, LuaRef b, LuaContextHandle contextHandle) static
Vec3 sum.
Parameters
a Value 1 to sum.
b Value 2 to sum.
contextHandle The context handle.
Returns
LuaRef
Definition at line 14 of file LuaVectorUtility.cpp.
References ToLuaTable().
 {
     vec3 vec1 = FromLuaTable<vec3>(a);
     vec3 vec2 = FromLuaTable<vec3>(b);
     vec3 finalVec = vec1 + vec2;
     return ToLuaTable(finalVec, contextHandle);
 }
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/LuaVectorUtility.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/LuaVectorUtility.cpp