ICT397 Game Engine: IAnimatable Class Reference
IAnimatable Class Reference abstract
#include <IAnimatable.h>
Public Member Functions
void SetActiveAnimation (string const &animationName)
Sets the active animation.
string const & GetActiveAnimationName () const
Gets the name of the active animation.
virtual void SetActiveAnimation (int animationIndex)=0
Sets the active animation.
virtual int GetActiveAnimationIndex () const =0
Gets the index of the active animation.
Public Member Functions inherited from IAnimated
virtual int GetAnimationCount () const =0
virtual string const & GetAnimationName (int animationIndex) const =0
virtual int GetAnimationIndex (string const &animationName) const =0
Detailed Description
Definition at line 15 of file IAnimatable.h.
Member Function Documentation
virtual int IAnimatable::GetActiveAnimationIndex () const pure virtual
Gets the index of the active animation.
Returns
Implemented in ObjectInstance.
Referenced by GetActiveAnimationName().
string const & IAnimatable::GetActiveAnimationName () const
Gets the name of the active animation.
Returns
Definition at line 10 of file Animatable.cpp.
References GetActiveAnimationIndex(), and IAnimated::GetAnimationName().
 {
   return GetAnimationName(GetActiveAnimationIndex());
 }
void IAnimatable::SetActiveAnimation (string const & animationName)
Sets the active animation.
Parameters
animationName Name of the animation.
Definition at line 5 of file Animatable.cpp.
References IAnimated::GetAnimationIndex(), and SetActiveAnimation().
 {
   return SetActiveAnimation(GetAnimationIndex(animationName));
 }
virtual void IAnimatable::SetActiveAnimation (int animationIndex) pure virtual
Sets the active animation.
Parameters
animationIndex Index of the animation.
Implemented in ObjectInstance.
Referenced by SetActiveAnimation().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/IAnimatable.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Animatable.cpp