ICT397 Game Engine: IAnimated Class Reference
IAnimated Class Reference abstract
#include <IAnimated.h>
Public Member Functions
virtual int GetAnimationCount () const =0
virtual string const & GetAnimationName (int animationIndex) const =0
virtual int GetAnimationIndex (string const &animationName) const =0
Detailed Description
Definition at line 5 of file IAnimated.h.
Member Function Documentation
virtual int IAnimated::GetAnimationCount () const pure virtual
Implemented in Model, RenderableObject, ObjectInstance, and Skeleton.
Referenced by ObjectInstance::GetAnimationCount().
virtual int IAnimated::GetAnimationIndex (string const & animationName) const pure virtual
Implemented in Model, RenderableObject, ObjectInstance, and Skeleton.
Referenced by ObjectInstance::GetAnimationIndex(), and IAnimatable::SetActiveAnimation().
virtual string const& IAnimated::GetAnimationName (int animationIndex) const pure virtual
Implemented in Model, RenderableObject, Skeleton, and ObjectInstance.
Referenced by IAnimatable::GetActiveAnimationName(), and ObjectInstance::GetAnimationName().
The documentation for this class was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/IAnimated.h