ICT397 Game Engine: ForestTerrain Class Reference
ForestTerrain Class Reference
#include <ForestTerrain.h>
Public Member Functions
ForestTerrain (uint terrainWidth, uint terrainHeight, float heightScale, float textureTileCount, string const &filepath, int density)
Initializes a new instance of the ForestTerrain class.
void GenerateForest ()
Generates the forest.
void SaveTerrainToOBJ (const string &filepath) const
Saves the terrain to object.
virtual void Render (mat4 const &worldMatrix, mat4 const &viewMatrix, mat4 const &projectionMatrix, float time) override
Renders the specified world matrix.
virtual std::vector< vec3 > const & GetVertices () const override
Gets the vertices.
virtual std::vector< vec3 > const & GetNormals () const override
Gets the normals.
virtual std::vector< int > const & GetIndices () const override
Gets the indices.
Public Member Functions inherited from IMesh
virtual std::vector< vec2 > const & GetTexCoords () const
Gets the texture coords.
int GetTexCoordsCount () const
Gets the texture coords count.
int GetVertexCount () const
Gets the vertex count.
int GetNormalCount () const
Gets the normal count.
int GetIndexCount () const
Gets the index count.
Private Attributes
std::vector< ObjectInstance * > m_trees
The m trees
Terrain * m_pLand
The m p land
Detailed Description
Definition at line 19 of file ForestTerrain.h.
Constructor & Destructor Documentation
ForestTerrain::ForestTerrain (uint terrainWidth, uint terrainHeight, float heightScale, float textureTileCount, string const & filepath, int density)
Initializes a new instance of the ForestTerrain class.
Parameters
terrainWidth Width of the terrain.
terrainHeight Height of the terrain.
heightScale The height scale.
textureTileCount The texture tile count.
filepath The filepath.
density The density.
Definition at line 10 of file ForestTerrain.cpp.
References GenerateForest(), m_pLand, and Terrain::Terrain().
 {
   m_pLand = new Terrain(terrainWidth, terrainHeight, heightScale, filePath);
   GenerateForest();
 }
Member Function Documentation
void ForestTerrain::GenerateForest ()
Generates the forest.
Definition at line 16 of file ForestTerrain.cpp.
References HeightMap::GetHeight(), Terrain::GetHeightMap(), Terrain::GetHeightScale(), HeightMap::GetWidth(), Terrain::GetXBlockScale(), Terrain::GetYBlockScale(), m_pLand, RandomFloat(), and AffineTransformable::SetYaw().
Referenced by ForestTerrain().
 {
   static const char* treeNames[] = { "PalmTree", "BambooPalm", "GroundPalm", "SmallPlant", "HighTree" };
   int width = m_pLand->GetHeightMap()->GetWidth();
   int height = m_pLand->GetHeightMap()->GetHeight();
   ObjectInstance* pTree;
   float x_bs = m_pLand->GetXBlockScale();
   float y_bs = m_pLand->GetYBlockScale();
   float hs = m_pLand->GetHeightScale();
   for (int x = 0; x < width; x++)
   {
     for (int y = 0; y < height; y++)
     {
       float heightAtPixel = m_pLand->GetHeightMap()->GetHeightValueAtPixel(vec2(x, y));
       float success = RandomFloat(0, 1);
       if (success < pow(heightAtPixel, 1) * 0.1f)
       {
         string treeName = treeNames[RandomInt(0, sizeof(treeNames) / sizeof(treeNames[0]))];
         pTree = ModelLibrary::GetInstance().GetObjectInstance(treeName);
         pTree->SetTranslation(vec3(x*x_bs, heightAtPixel*hs, y*y_bs));
         float yaw = RandomFloat(0, 360);
         float scale = RandomFloat(0.5f, 1);
         pTree->SetYaw(yaw);
         pTree->SetScale(vec3(scale, scale, scale));
         m_trees.push_back(pTree);
       }
     }
   }
 }
std::vector< int > const & ForestTerrain::GetIndices () const override virtual
Gets the indices.
Returns
Implements IMesh.
Definition at line 67 of file ForestTerrain.cpp.
 {
   return m_pLand->GetIndices();
 }
std::vector< vec3 > const & ForestTerrain::GetNormals () const override virtual
Gets the normals.
Returns
Implements IMesh.
Definition at line 62 of file ForestTerrain.cpp.
 {
   return m_pLand->GetNormals();
 }
std::vector< vec3 > const & ForestTerrain::GetVertices () const override virtual
Gets the vertices.
Returns
Implements IMesh.
Definition at line 57 of file ForestTerrain.cpp.
 {
   return m_pLand->GetVertices();
 }
void ForestTerrain::Render (mat4 const & worldMatrix, mat4 const & viewMatrix, mat4 const & projectionMatrix, float time) override virtual
Renders the specified world matrix.
Parameters
worldMatrix The world matrix.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
time The time.
Implements IRenderable.
Definition at line 49 of file ForestTerrain.cpp.
 {
   for (int i = 0; i < m_trees.size(); i++)
   {
     m_trees[i]->Render(worldMatrix, viewMatrix, projectionMatrix);
   }
 }
void ForestTerrain::SaveTerrainToOBJ (const string & filepath) const
Saves the terrain to object.
Parameters
filepath The filepath.
Definition at line 5 of file ForestTerrain.cpp.
 {
   OBJWriter::SaveMeshToOBJ(*this, filepath);
 }
Member Data Documentation
Terrain* ForestTerrain::m_pLand private
The m p land
Definition at line 92 of file ForestTerrain.h.
Referenced by ForestTerrain(), and GenerateForest().
std::vector<ObjectInstance*> ForestTerrain::m_trees private
The m trees
Definition at line 87 of file ForestTerrain.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/ForestTerrain.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/ForestTerrain.cpp