ICT397 Game Engine: InputManagerAPI Class Reference
InputManagerAPI Class Reference
#include <InputManagerAPI.h>
Static Public Member Functions
static int MouseDeltaX ()
Get mouse delta X through lua API.
static int MouseDeltaY ()
Get mouse delta Y through lua API.
static bool IsKeyDown (int keyCode)
Checks if key is down in input through lua API.
static bool IsKeyUp (int keyCode)
Checks if key is up in input through lua API.
static bool IsKeyPressed (int keyCode)
Checks if key is pressed in input through lua API.
static bool IsKeyReleased (int keyCode)
Checks if key is released in input through lua API.
static bool IsMousePressedLeft ()
Checks if mouse button is pressed in input through lua API.
static void Expose (LuaContextHandle contextHandle, string luaAPIName)
Exposes class to lua as API
Private Attributes
std::unique_ptr< IInputHandler > input
Detailed Description
Definition at line 16 of file InputManagerAPI.h.
Member Function Documentation
void InputManagerAPI::Expose (LuaContextHandle contextHandle, string luaAPIName) static
Exposes class to lua as API
Parameters
contextHandle Lua context handle</param
Parameters
luaAPIName Name of the API
Returns
int
Definition at line 54 of file InputManagerAPI.cpp.
 {
     LuaContext* pContext = LuaManager::GetInstance().GetContext(contextHandle);
     pContext->ExposeFunction(luaAPIName, "isKeyDown", IsKeyDown);
     pContext->ExposeFunction(luaAPIName, "isKeyUp", IsKeyUp);
     pContext->ExposeFunction(luaAPIName, "isKeyPressed", IsKeyPressed);
     pContext->ExposeFunction(luaAPIName, "isKeyReleased", IsKeyReleased);
     pContext->ExposeFunction(luaAPIName, "mouseDeltaX", MouseDeltaX);
     pContext->ExposeFunction(luaAPIName, "mouseDeltaY", MouseDeltaY);
     pContext->ExposeFunction(luaAPIName, "isMousePressedLeft", IsMousePressedLeft);
 }
bool InputManagerAPI::IsKeyDown (int keyCode) static
Checks if key is down in input through lua API.
Parameters
keyCode sdl key code
Returns
bool
Definition at line 16 of file InputManagerAPI.cpp.
Referenced by IsKeyPressed(), and IsKeyUp().
 {
   return InputManager::GetInstance().KeyboardState(keyCode);
 }
bool InputManagerAPI::IsKeyPressed (int keyCode) static
Checks if key is pressed in input through lua API.
Parameters
keyCode sdl key code
Returns
int
Definition at line 26 of file InputManagerAPI.cpp.
References IsKeyDown().
 {
     if (IsKeyDown(keyCode))
     {
         if (InputManager::GetInstance().LastKeyboardState(keyCode) == 0)
         {
             return true;
         }
     }
     return false;
 }
bool InputManagerAPI::IsKeyReleased (int keyCode) static
Checks if key is released in input through lua API.
Parameters
keyCode sdl key code
Returns
int
Definition at line 49 of file InputManagerAPI.cpp.
 {
     return IsKeyUp(keyCode) && (InputManager::GetInstance().LastKeyboardState(keyCode) != 0);
 }
bool InputManagerAPI::IsKeyUp (int keyCode) static
Checks if key is up in input through lua API.
Parameters
keyCode sdl key code
Returns
int
Definition at line 21 of file InputManagerAPI.cpp.
References IsKeyDown().
 {
     return !IsKeyDown(keyCode);
 }
bool InputManagerAPI::IsMousePressedLeft () static
Checks if mouse button is pressed in input through lua API.
Parameters
keyCode sdl key code
Returns
int
Definition at line 39 of file InputManagerAPI.cpp.
 {
     if (InputManager::GetInstance().IsMousePressedLeft())
     {
         return true;
     }
     return false;
 }
int InputManagerAPI::MouseDeltaX () static
Get mouse delta X through lua API.
Returns
int
Definition at line 5 of file InputManagerAPI.cpp.
 {
     return InputManager::GetInstance().MouseDeltaX();
 }
int InputManagerAPI::MouseDeltaY () static
Get mouse delta Y through lua API.
Returns
int
Definition at line 10 of file InputManagerAPI.cpp.
 {
     return InputManager::GetInstance().MouseDeltaY();
 }
Member Data Documentation
std::unique_ptr<IInputHandler> InputManagerAPI::input private
Definition at line 79 of file InputManagerAPI.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/InputManagerAPI.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/InputManagerAPI.cpp