ICT397 Game Engine: LuaObjectInstanceManager Class Reference
LuaObjectInstanceManager Class Reference
#include <LuaObjectInstanceManager.h>
Static Public Member Functions
static InstanceHandle AddNewInstance (string const &modelName)
Adds the new object instance.
static ObjectInstance * GetInstance (int instanceHandle)
Gets the object instance.
static void Expose (LuaContextHandle contextHandle, string luaAPIName)
Exposes the API functions.
static void DeleteInstance (int instanceHandle)
Deletes a specified object instance from the map.
Static Public Member Functions inherited from Singleton< LuaObjectInstanceManager >
static LuaObjectInstanceManager & GetInstance ()
Additional Inherited Members
Protected Member Functions inherited from Singleton< LuaObjectInstanceManager >
Singleton ()
Static Protected Attributes inherited from Singleton< LuaObjectInstanceManager >
static LuaObjectInstanceManager * p
Detailed Description
Definition at line 22 of file LuaObjectInstanceManager.h.
Member Function Documentation
InstanceHandle LuaObjectInstanceManager::AddNewInstance (string const & modelName) static
Adds the new object instance.
Returns handle to new object instance of given model name.
Parameters
modelName Name of the model.
Returns
InstanceHandle
.
Definition at line 11 of file LuaObjectInstanceManager.cpp.
References m_lastIndex.
 {
     ObjectInstance* newInstance = ModelLibrary::GetInstance().GetObjectInstance(modelName);
     m_instanceMap.emplace(m_lastIndex, newInstance);
     m_lastIndex += 1;
     return m_lastIndex-1;
 }
void LuaObjectInstanceManager::DeleteInstance (int instanceHandle) static
Deletes a specified object instance from the map.
Parameters
instanceHandle The instance handle of the instance to delete.
Definition at line 21 of file LuaObjectInstanceManager.cpp.
 {
     auto got = m_instanceMap.find(instanceHandle);
     if (got == m_instanceMap.end())
     {
         printf("Instance with name %n not found.", instanceHandle);
     }
     else {
         m_instanceMap.erase(instanceHandle);
     }
 }
void LuaObjectInstanceManager::Expose (LuaContextHandle contextHandle, string luaAPIName) static
Exposes the API functions.
Parameters
contextHandle The context handle.
luaAPIName Name of the lua API.
Definition at line 51 of file LuaObjectInstanceManager.cpp.
 {
     LuaContext* pContext = LuaManager::GetInstance().GetContext(contextHandle);
     pContext->ExposeFunction(luaAPIName, "addNewInstance", AddNewInstance);
     pContext->ExposeFunction(luaAPIName, "deleteInstance", DeleteInstance);
 }
ObjectInstance * LuaObjectInstanceManager::GetInstance (int instanceHandle) static
Gets the object instance.
Parameters
instanceHandle The instance handle.
Returns
Definition at line 36 of file LuaObjectInstanceManager.cpp.
Referenced by RenderManagerAPI::AddObject(), ObjectInstanceAPI::GetInstance(), ObjectInstanceAPI::GetScale(), ObjectInstanceAPI::GetTranslation(), RenderManagerAPI::RemoveObject(), and RenderManagerAPI::RenderObject().
 {
     auto got = m_instanceMap.find(instanceHandle);
     if (got == m_instanceMap.end())
     {
         printf("Instance with name %n not found.", instanceHandle);
         ObjectInstance * nullInst;
         return nullInst;
     }
     return got->second;
 }
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/LuaObjectInstanceManager.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/LuaObjectInstanceManager.cpp