ICT397 Game Engine: GLInputHandler Class Reference
GLInputHandler Class Reference
#include <GLInputHandler.h>
Public Member Functions
GLInputHandler ()
virtual void Update () override
Updates this instance.
virtual bool IsKeyDown (int keyCode) const override
Determines whether [is key down] [the specified key code].
virtual bool IsKeyUp (int keyCode) const override
Determines whether [is key up] [the specified key code].
virtual bool IsKeyPressed (int keyCode) const override
Determines whether [is key pressed] [the specified key code].
virtual bool IsKeyReleased (int keyCode) const override
Determines whether [is key released] [the specified key code].
virtual bool IsMouseDownLeft () const override
Determines whether [is mouse down left].
virtual bool IsMouseUpLeft () const override
Determines whether [is mouse up left].
virtual bool IsMousePressedLeft () const override
Determines whether [is mouse pressed left].
virtual bool IsMouseReleasedLeft () const override
Determines whether [is mouse released left].
virtual bool IsMouseDownRight () const override
Determines whether [is mouse down right].
virtual bool IsMouseUpRight () const override
Determines whether [is mouse up right].
virtual bool IsMousePressedRight () const override
Determines whether [is mouse pressed right].
virtual bool IsMouseReleasedRight () const override
Determines whether [is mouse released right].
virtual int32_t MouseDeltaX () const override
Gets the change in x.
virtual int32_t MouseDeltaY () const override
Gets the change in y.
virtual uint8_t KeyboardState (int keyCode) const override
Current keyboard state.
virtual uint8_t LastKeyboardState (int keyCode) const override
Last keyboard state.
Private Member Functions
void ProcessButtonEvent (SDL_MouseButtonEvent _event)
Processes the button event.
void ProcessMotionEvent (SDL_MouseMotionEvent _event)
Processes the motion event.
void ProcessEventQueue ()
Processes the event queue.
void PushEvent (MouseEvent const &_event)
Pushes the event.
bool HandleEvents ()
Handles the events.
Private Attributes
std::vector< MouseEvent > m_eventQueue
The event queue
int m_keyStateSize = 0
The key state size
uint8_t keyboardState [16384]
The keyboard state
uint8_t lastKeyboardState [16384]
The last keyboard state
MouseButtonState mouseButtonStates [4]
The mouse button states
int32_t mouseDeltaX
The mouse delta x
int32_t mouseDeltaY
The mouse delta y
Detailed Description
Definition at line 64 of file GLInputHandler.h.
Constructor & Destructor Documentation
GLInputHandler::GLInputHandler ()
Definition at line 5 of file GLInputHandler.cpp.
References Update().
 {
   memset(lastKeyboardState, 0, 16384);
   memset(keyboardState, 0, 16384);
   Update();
 }
Member Function Documentation
bool GLInputHandler::HandleEvents () private
Handles the events.
Returns
Definition at line 12 of file GLInputHandler.cpp.
Referenced by Update().
 {
   SDL_Event event;
   while (SDL_PollEvent(&event))
   {
     switch (event.type)
     {
       case SDL_QUIT:
         return false;
       case SDL_MOUSEMOTION:
         PushEvent(MouseEvent(event.motion));
         break;
       case SDL_MOUSEBUTTONDOWN:
         PushEvent(MouseEvent(event.button));
         break;
       case SDL_MOUSEBUTTONUP:
         PushEvent(MouseEvent(event.button));
         break;
     }
   }
   return true;
 }
bool GLInputHandler::IsKeyDown (int keyCode) const override virtual
Determines whether [is key down] [the specified key code].
Parameters
keyCode The key code.
Returns
true if [is key down] [the specified key code]; otherwise, false.
Implements IInputHandler.
Definition at line 106 of file GLInputHandler.cpp.
References keyboardState.
Referenced by IsKeyPressed(), and IsKeyUp().
 {
   return keyboardState[keyCode] != 0;
 }
bool GLInputHandler::IsKeyPressed (int keyCode) const override virtual
Determines whether [is key pressed] [the specified key code].
Parameters
keyCode The key code.
Returns
true if [is key pressed] [the specified key code]; otherwise, false.
Implements IInputHandler.
Definition at line 116 of file GLInputHandler.cpp.
References IsKeyDown(), and lastKeyboardState.
 {
   if (IsKeyDown(keyCode))
   {
     if (lastKeyboardState[keyCode] == 0)
     {
       return true;
     }
   }
   return false;
 }
bool GLInputHandler::IsKeyReleased (int keyCode) const override virtual
Determines whether [is key released] [the specified key code].
Parameters
keyCode The key code.
Returns
true if [is key released] [the specified key code]; otherwise, false.
Implements IInputHandler.
Definition at line 129 of file GLInputHandler.cpp.
References IsKeyUp(), and lastKeyboardState.
 {
   return IsKeyUp(keyCode) && (lastKeyboardState[keyCode] != 0);
 }
bool GLInputHandler::IsKeyUp (int keyCode) const override virtual
Determines whether [is key up] [the specified key code].
Parameters
keyCode The key code.
Returns
true if [is key up] [the specified key code]; otherwise, false.
Implements IInputHandler.
Definition at line 111 of file GLInputHandler.cpp.
References IsKeyDown().
Referenced by IsKeyReleased().
 {
   return !IsKeyDown(keyCode);
 }
bool GLInputHandler::IsMouseDownLeft () const override virtual
Determines whether [is mouse down left].
Returns
true if [is mouse down left]; otherwise, false.
Implements IInputHandler.
Definition at line 134 of file GLInputHandler.cpp.
Referenced by IsMouseUpLeft().
 {
   return mouseButtonStates[SDL_BUTTON_LEFT].down;
 }
bool GLInputHandler::IsMouseDownRight () const override virtual
Determines whether [is mouse down right].
Returns
true if [is mouse down right]; otherwise, false.
Implements IInputHandler.
Definition at line 154 of file GLInputHandler.cpp.
Referenced by IsMouseUpRight().
 {
   return mouseButtonStates[SDL_BUTTON_RIGHT].down;
 }
bool GLInputHandler::IsMousePressedLeft () const override virtual
Determines whether [is mouse pressed left].
Returns
true if [is mouse pressed left]; otherwise, false.
Implements IInputHandler.
Definition at line 144 of file GLInputHandler.cpp.
 {
   return mouseButtonStates[SDL_BUTTON_LEFT].pressed;
 }
bool GLInputHandler::IsMousePressedRight () const override virtual
Determines whether [is mouse pressed right].
Returns
true if [is mouse pressed right]; otherwise, false.
Implements IInputHandler.
Definition at line 164 of file GLInputHandler.cpp.
 {
   return mouseButtonStates[SDL_BUTTON_RIGHT].pressed;
 }
bool GLInputHandler::IsMouseReleasedLeft () const override virtual
Determines whether [is mouse released left].
Returns
true if [is mouse released left]; otherwise, false.
Implements IInputHandler.
Definition at line 149 of file GLInputHandler.cpp.
 {
   return mouseButtonStates[SDL_BUTTON_LEFT].released;
 }
bool GLInputHandler::IsMouseReleasedRight () const override virtual
Determines whether [is mouse released right].
Returns
true if [is mouse released right]; otherwise, false.
Implements IInputHandler.
Definition at line 169 of file GLInputHandler.cpp.
 {
   return mouseButtonStates[SDL_BUTTON_RIGHT].released;
 }
bool GLInputHandler::IsMouseUpLeft () const override virtual
Determines whether [is mouse up left].
Returns
true if [is mouse up left]; otherwise, false.
Implements IInputHandler.
Definition at line 139 of file GLInputHandler.cpp.
References IsMouseDownLeft().
 {
   return !IsMouseDownLeft();
 }
bool GLInputHandler::IsMouseUpRight () const override virtual
Determines whether [is mouse up right].
Returns
true if [is mouse up right]; otherwise, false.
Implements IInputHandler.
Definition at line 159 of file GLInputHandler.cpp.
References IsMouseDownRight().
 {
   return !IsMouseDownRight();
 }
uint8_t GLInputHandler::KeyboardState (int keyCode) const override virtual
Current keyboard state.
Parameters
keyCode The key code.
Returns
Implements IInputHandler.
Definition at line 184 of file GLInputHandler.cpp.
References keyboardState.
 {
   return keyboardState[keyCode];
 }
uint8_t GLInputHandler::LastKeyboardState (int keyCode) const override virtual
Last keyboard state.
Parameters
keyCode The key code.
Returns
Implements IInputHandler.
Definition at line 189 of file GLInputHandler.cpp.
References lastKeyboardState.
 {
   return lastKeyboardState[keyCode];
 }
int32_t GLInputHandler::MouseDeltaX () const override virtual
Gets the change in x.
Returns
int32_t
Implements IInputHandler.
Definition at line 174 of file GLInputHandler.cpp.
References mouseDeltaX.
 {
   return mouseDeltaX;
 }
int32_t GLInputHandler::MouseDeltaY () const override virtual
Gets the change in y.
Returns
int32_t
Implements IInputHandler.
Definition at line 179 of file GLInputHandler.cpp.
References mouseDeltaY.
 {
   return mouseDeltaY;
 }
void GLInputHandler::ProcessButtonEvent (SDL_MouseButtonEvent _event) private
Processes the button event.
Parameters
_event The event.
Definition at line 35 of file GLInputHandler.cpp.
 {
   MouseButtonState& buttonState = mouseButtonStates[_event.button];
   switch (_event.state)
   {
     case SDL_PRESSED:
       buttonState.pressed = true;
       buttonState.down = true;
       break;
     case SDL_RELEASED:
       buttonState.released = true;
       buttonState.down = false;
   }
 }
void GLInputHandler::ProcessEventQueue () private
Processes the event queue.
Definition at line 56 of file GLInputHandler.cpp.
References MouseEvent::eventType, mouseButtonStates, mouseDeltaX, mouseDeltaY, MouseEvent::MouseEvent(), MouseButtonState::pressed, and MouseButtonState::released.
Referenced by Update().
 {
   mouseDeltaX = 0;
   mouseDeltaY = 0;
   for (int i = 0; i < 4; i++)
   {
     mouseButtonStates[i].pressed = false;
     mouseButtonStates[i].released = false;
   }
   for (size_t i = 0; i < m_eventQueue.size(); i++)
   {
     MouseEvent& nextEvent = m_eventQueue[i];
     switch (nextEvent.eventType)
     {
       case ME_BUTTON:
         ProcessButtonEvent(nextEvent.mouseEvent.buttonEvent);
         break;
       case ME_MOTION:
         ProcessMotionEvent(nextEvent.mouseEvent.motionEvent);
     }
   }
   m_eventQueue.clear();
 }
void GLInputHandler::ProcessMotionEvent (SDL_MouseMotionEvent _event) private
Processes the motion event.
Parameters
_event The event.
Definition at line 50 of file GLInputHandler.cpp.
 {
   mouseDeltaX = _event.xrel;
   mouseDeltaY = _event.yrel;
 }
void GLInputHandler::PushEvent (MouseEvent const & _event) private
Pushes the event.
Parameters
_event The event.
Definition at line 101 of file GLInputHandler.cpp.
 {
   m_eventQueue.push_back(_event);
 }
void GLInputHandler::Update () override virtual
Updates this instance.
Implements IInputHandler.
Definition at line 80 of file GLInputHandler.cpp.
References HandleEvents(), keyboardState, m_keyStateSize, and ProcessEventQueue().
Referenced by GLInputHandler().
 {
   HandleEvents();
   static int counter = 0;
   ProcessEventQueue();
   SDL_PumpEvents();
   memset(lastKeyboardState, 0, 16384);
   for (int i = 0; i < m_keyStateSize; i++)
   {
     if (keyboardState[i] != 0)
     {
       break;
     }
   }
   memcpy(lastKeyboardState, keyboardState, m_keyStateSize);
   const uint8_t* temp = SDL_GetKeyboardState(&m_keyStateSize);
   memcpy(keyboardState, temp, m_keyStateSize);
 }
Member Data Documentation
uint8_t GLInputHandler::keyboardState[16384] private
The keyboard state
Definition at line 262 of file GLInputHandler.h.
Referenced by IsKeyDown(), KeyboardState(), and Update().
uint8_t GLInputHandler::lastKeyboardState[16384] private
The last keyboard state
Definition at line 267 of file GLInputHandler.h.
Referenced by IsKeyPressed(), IsKeyReleased(), and LastKeyboardState().
std::vector<MouseEvent> GLInputHandler::m_eventQueue private
The event queue
Definition at line 222 of file GLInputHandler.h.
int GLInputHandler::m_keyStateSize = 0 private
The key state size
Definition at line 227 of file GLInputHandler.h.
Referenced by Update().
MouseButtonState GLInputHandler::mouseButtonStates[4] private
The mouse button states
Definition at line 272 of file GLInputHandler.h.
Referenced by ProcessEventQueue().
int32_t GLInputHandler::mouseDeltaX private
The mouse delta x
Definition at line 277 of file GLInputHandler.h.
Referenced by MouseDeltaX(), and ProcessEventQueue().
int32_t GLInputHandler::mouseDeltaY private
The mouse delta y
Definition at line 282 of file GLInputHandler.h.
Referenced by MouseDeltaY(), and ProcessEventQueue().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/GLInputHandler.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/GLInputHandler.cpp