ICT397 Game Engine: IMeshCollection Class Reference
IMeshCollection Class Reference abstract
#include <IMeshCollection.h>
Public Member Functions
std::vector< vec3 > GetVertices () const
Gets the vertices.
std::vector< vec3 > GetNormals () const
Gets the normals.
std::vector< vec3 > GetAABB () const
Gets Axis aligned bounding box - index 0=min, 1=max.
std::vector< int > GetIndices () const
Gets the indices.
int GetVertexCount () const
Gets the vertex count.
int GetNormalCount () const
Gets the normal count.
int GetIndexCount () const
Gets the index count.
virtual IMesh const & GetMesh (int meshIndex) const =0
Gets the mesh at the specified index.
virtual int GetMeshCount () const =0
Gets the mesh count.
Detailed Description
Definition at line 16 of file IMeshCollection.h.
Member Function Documentation
std::vector< vec3 > IMeshCollection::GetAABB () const
Gets Axis aligned bounding box - index 0=min, 1=max.
Returns
Definition at line 84 of file IMeshCollection.cpp.
References GetMeshCount().
 {
     std::vector<vec3> aabb;
     int meshCount = GetMeshCount();
     for (int i = 0; i < meshCount; i++)
     {
         std::vector<vec3> verts = GetMesh(i).GetVertices();
         for (int a = 0; a < verts.size(); a++)
         {
             // Set up min and max to the first values to initialise
             if (i == 0 && a == 0)
             {
                 aabb.push_back(verts[a]);
                 aabb.push_back(verts[a]);
             }
             // Check for new min and max values
             if (verts[a].x < aabb[0].x)
             {
                 aabb[0].x = verts[a].x;
             }
             if (verts[a].y < aabb[0].y)
             {
                 aabb[0].y = verts[a].y;
             }
             if (verts[a].z < aabb[0].z)
             {
                 aabb[0].z = verts[a].z;
             }
             if (verts[a].x > aabb[1].x)
             {
                 aabb[1].x = verts[a].x;
             }
             if (verts[a].y > aabb[1].y)
             {
                 aabb[1].y = verts[a].y;
             }
             if (verts[a].z > aabb[1].z)
             {
                 aabb[1].z = verts[a].z;
             }
         }
     }
     return aabb;
 }
int IMeshCollection::GetIndexCount () const
Gets the index count.
Returns
Definition at line 71 of file IMeshCollection.cpp.
References IMesh::GetIndexCount(), GetMesh(), and GetMeshCount().
 {
   int count = 0;
   int meshCount = GetMeshCount();
   for (int i = 0; i < meshCount; i++)
   {
     count += GetMesh(i).GetIndexCount();
   }
   return count;
 }
std::vector< int > IMeshCollection::GetIndices () const
Gets the indices.
Returns
Definition at line 32 of file IMeshCollection.cpp.
References GetMeshCount().
 {
   std::vector<int> indices;
   int meshCount = GetMeshCount();
   indices.reserve(GetNormalCount());
   for (int i = 0; i < meshCount; i++)
   {
     VectorConcatenate(indices, GetMesh(i).GetIndices());
   }
   return indices;
 }
virtual IMesh const& IMeshCollection::GetMesh (int meshIndex) const pure virtual
Gets the mesh at the specified index.
Parameters
meshIndex Index of the mesh.
Returns
Implemented in Model, and RenderableObject.
Referenced by GetIndexCount(), GetNormalCount(), and GetVertexCount().
virtual int IMeshCollection::GetMeshCount () const pure virtual
Gets the mesh count.
Returns
Implemented in Model, and RenderableObject.
Referenced by GetAABB(), GetIndexCount(), GetIndices(), GetNormalCount(), GetNormals(), GetVertexCount(), GetVertices(), and ObjectInstance::Render().
int IMeshCollection::GetNormalCount () const
Gets the normal count.
Returns
Definition at line 58 of file IMeshCollection.cpp.
References GetMesh(), GetMeshCount(), and IMesh::GetNormalCount().
 {
   int count = 0;
   int meshCount = GetMeshCount();
   for (int i = 0; i < meshCount; i++)
   {
     count += GetMesh(i).GetNormalCount();
   }
   return count;
 }
std::vector< vec3 > IMeshCollection::GetNormals () const
Gets the normals.
Returns
Definition at line 19 of file IMeshCollection.cpp.
References GetMeshCount().
 {
   std::vector<vec3> normals;
   int meshCount = GetMeshCount();
   normals.reserve(GetNormalCount());
   for (int i = 0; i < meshCount; i++)
   {
     VectorConcatenate(normals, GetMesh(i).GetNormals());
   }
   return normals;
 }
int IMeshCollection::GetVertexCount () const
Gets the vertex count.
Returns
Definition at line 45 of file IMeshCollection.cpp.
References GetMesh(), GetMeshCount(), and IMesh::GetVertexCount().
 {
   int count = 0;
   int meshCount = GetMeshCount();
   for (int i = 0; i < meshCount; i++)
   {
     count += GetMesh(i).GetVertexCount();
   }
   return count;
 }
std::vector< vec3 > IMeshCollection::GetVertices () const
Gets the vertices.
Returns
Definition at line 6 of file IMeshCollection.cpp.
References GetMeshCount().
 {
   std::vector<vec3> vertices;
   int meshCount = GetMeshCount();
   vertices.reserve(GetVertexCount());
   for (int i = 0; i < meshCount; i++)
   {
     VectorConcatenate(vertices, GetMesh(i).GetVertices());
   }
   return vertices;
 }
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/IMeshCollection.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/IMeshCollection.cpp