ICT397 Game Engine: FrameBuffer Class Reference
FrameBuffer Class Reference
#include <FrameBuffer.h>
Public Member Functions
FrameBuffer ()
Initializes a new instance of the FrameBuffer class.
~FrameBuffer ()
Finalizes an instance of the FrameBuffer class.
void Bind (FrameBufferBindMode bufferMode=FBBM_ReadWrite)
Binds the specified buffer mode.
void Unbind (FrameBufferBindMode bufferMode=FBBM_ReadWrite)
Unbinds the specified buffer mode.
FrameBufferBindMode GetBindMode ()
Gets the bind mode.
FrameBufferStatus GetStatus (FrameBufferBindMode bindMode=FBBM_ReadWrite)
Gets the status of the frame buffer.
void AttachColour (int location, GLuint texID)
Attaches the color buffer.
void AttachDepth (GLuint texID)
Attaches the depth buffer.
void DetachColour (int location)
Detaches the color buffer.
void DetachDepth ()
Detaches the depth buffer.
Static Public Member Functions
static void Initialize ()
Initializes this instance.
static void BindToScreen (FrameBufferBindMode bufferMode=FBBM_ReadWrite)
Binds the frame buffer to the screen.
static void Display (GLuint texture)
Displays the specified texture to the screen.
Static Public Attributes
static GLuint FSQuadVAO
The fs quad vao{CC2D43FA-BBC4-448A-9D0B-7B57ADF2655C}
Private Member Functions
void AddColourAttachment (GLuint location)
Adds the color attachment.
void RemoveColourAttachment (GLuint location)
Removes the color attachment.
Static Private Member Functions
static void BindFrameBuffer (GLuint buffer, FrameBufferBindMode bufferMode=FBBM_ReadWrite)
Binds the frame buffer.
Private Attributes
GLuint m_fb = 0
The frame buffer.
std::vector< GLuint > colourAttachments
The color attachments
Static Private Attributes
static int MAX_COLOUR_ATTACHMENTS = 8
The maximum colour attachments{CC2D43FA-BBC4-448A-9D0B-7B57ADF2655C}
Detailed Description
Definition at line 40 of file FrameBuffer.h.
Constructor & Destructor Documentation
FrameBuffer::FrameBuffer ()
Initializes a new instance of the FrameBuffer class.
Definition at line 74 of file FrameBuffer.cpp.
 {
   glGenFramebuffers(1, &m_fb);
 }
FrameBuffer::~FrameBuffer ()
Finalizes an instance of the FrameBuffer class.
Definition at line 79 of file FrameBuffer.cpp.
 {
   glDeleteFramebuffers(1, &m_fb);
 }
Member Function Documentation
void FrameBuffer::AddColourAttachment (GLuint location) private
Adds the color attachment.
Parameters
location The location.
Definition at line 231 of file FrameBuffer.cpp.
 {
   for (int i = 0; i < colourAttachments.size(); i++)
   {
     if (colourAttachments[i] == GL_COLOR_ATTACHMENT0 + location)
       return;
   }
   colourAttachments.push_back(GL_COLOR_ATTACHMENT0 + location);
 }
void FrameBuffer::AttachColour (int location, GLuint texID)
Attaches the color buffer.
Parameters
location The location.
texID The texture identifier.
Definition at line 148 of file FrameBuffer.cpp.
References FBBM_Unbound, GetBindMode(), and MAX_COLOUR_ATTACHMENTS.
 {
   FrameBufferBindMode bindMode = GetBindMode();
   if (bindMode == FBBM_Unbound)
     throw std::exception("Attempt to attach texture to FrameBuffer that is not bound");
   if (location >= FrameBuffer::MAX_COLOUR_ATTACHMENTS)
     throw std::exception("Attempt to attach texture to color attachment >= MAX_COLOUR_ATTACHMENTS");
   if(bindMode & FBBM_Read)
     glFramebufferTexture(GL_READ_FRAMEBUFFER, GL_COLOR_ATTACHMENT0 + location, texID, 0);
   else
     glFramebufferTexture(GL_DRAW_FRAMEBUFFER, GL_COLOR_ATTACHMENT0 + location, texID, 0);
   AddColourAttachment(location);
   glDrawBuffers(colourAttachments.size(), colourAttachments.data());
 }
void FrameBuffer::AttachDepth (GLuint texID)
Attaches the depth buffer.
Parameters
texID The texture identifier.
Definition at line 167 of file FrameBuffer.cpp.
References FBBM_Unbound, and GetBindMode().
 {
   FrameBufferBindMode bindMode = GetBindMode();
   if (bindMode == FBBM_Unbound)
     throw std::exception("Attempt to attach texture to FrameBuffer that is not bound");
   if (bindMode & FBBM_Read)
     glFramebufferTexture(GL_READ_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, texID, 0);
   else
     glFramebufferTexture(GL_DRAW_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, texID, 0);
 }
void FrameBuffer::Bind (FrameBufferBindMode bufferMode = FBBM_ReadWrite)
Binds the specified buffer mode.
Parameters
bufferMode The buffer mode.
Definition at line 84 of file FrameBuffer.cpp.
 {
   BindFrameBuffer(m_fb, bufferMode);
 }
void FrameBuffer::BindFrameBuffer (GLuint buffer, FrameBufferBindMode bufferMode = FBBM_ReadWrite) static private
Binds the frame buffer.
Parameters
buffer The buffer.
bufferMode The buffer mode.
Definition at line 214 of file FrameBuffer.cpp.
 {
   switch (bufferMode)
   {
     case FBBM_Read:
       glBindFramebuffer(GL_READ_FRAMEBUFFER, buffer);
       break;
     case FBBM_Write:
       glBindFramebuffer(GL_DRAW_FRAMEBUFFER, buffer);
       break;
     case FBBM_ReadWrite:
       glBindFramebuffer(GL_DRAW_FRAMEBUFFER, buffer);
       glBindFramebuffer(GL_READ_FRAMEBUFFER, buffer);
       break;
   }
 }
void FrameBuffer::BindToScreen (FrameBufferBindMode bufferMode = FBBM_ReadWrite) static
Binds the frame buffer to the screen.
Parameters
bufferMode The buffer mode.
Definition at line 53 of file FrameBuffer.cpp.
Referenced by Display(), and Unbind().
 {
   BindFrameBuffer(0, bufferMode);
 }
void FrameBuffer::DetachColour (int location)
Detaches the color buffer.
Parameters
location The location.
Definition at line 180 of file FrameBuffer.cpp.
References FBBM_Unbound, and GetBindMode().
 {
   FrameBufferBindMode bindMode = GetBindMode();
   if (bindMode == FBBM_Unbound)
     throw std::exception("Attempt to detach texture from FrameBuffer that is not bound");
   if (bindMode & FBBM_Read)
     glFramebufferTexture(GL_READ_FRAMEBUFFER, GL_COLOR_ATTACHMENT0 + location, 0, 0);
   else
     glFramebufferTexture(GL_DRAW_FRAMEBUFFER, GL_COLOR_ATTACHMENT0 + location, 0, 0);
   RemoveColourAttachment(location);
   glDrawBuffers(colourAttachments.size(), colourAttachments.data());
 }
void FrameBuffer::DetachDepth ()
Detaches the depth buffer.
Definition at line 196 of file FrameBuffer.cpp.
References FBBM_Unbound, and GetBindMode().
 {
   FrameBufferBindMode bindMode = GetBindMode();
   if (bindMode == FBBM_Unbound)
     throw std::exception("Attempt to attach texture to FrameBuffer that is not bound");
   if (bindMode & FBBM_Read)
     glFramebufferTexture(GL_READ_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, 0, 0);
   else
     glFramebufferTexture(GL_DRAW_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, 0, 0);
 }
void FrameBuffer::Display (GLuint texture) static
Displays the specified texture to the screen.
Parameters
texture The texture.
Definition at line 58 of file FrameBuffer.cpp.
References BindToScreen().
 {
   std::unique_ptr<IShader> const& shader = ShaderLibrary::GetInstance().GetShader("TextureDisplay");
   glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
   FrameBuffer::BindToScreen();
   shader->Bind();
   glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
   glBindVertexArray(FrameBuffer::FSQuadVAO);
   glActiveTexture(GL_TEXTURE0 + 0);
   glBindTexture(GL_TEXTURE_2D, texture);
   shader->TransmitUniform("inputTex0", 0);
   glDrawArrays(GL_QUADS, 0, 4);
   glBindVertexArray(NULL);
 }
FrameBufferBindMode FrameBuffer::GetBindMode ()
Gets the bind mode.
Returns
FrameBufferBindMode
Definition at line 94 of file FrameBuffer.cpp.
Referenced by AttachColour(), AttachDepth(), DetachColour(), DetachDepth(), and GetStatus().
 {
   GLint drawBuffer;
   GLint readBuffer;
   glGetIntegerv(GL_DRAW_FRAMEBUFFER_BINDING, &drawBuffer);
   glGetIntegerv(GL_READ_FRAMEBUFFER_BINDING, &readBuffer);
   if (drawBuffer == m_fb && readBuffer == m_fb)
     return FBBM_ReadWrite;
   else if (drawBuffer == m_fb)
     return FBBM_Write;
   else if (readBuffer == m_fb)
     return FBBM_Read;
   else
     return FBBM_Unbound;
 }
FrameBufferStatus FrameBuffer::GetStatus (FrameBufferBindMode bindMode = FBBM_ReadWrite)
Gets the status of the frame buffer.
Parameters
bindMode The bind mode.
Returns
Definition at line 111 of file FrameBuffer.cpp.
References FBBM_Unbound, FBS_Unbound, and GetBindMode().
 {
   FrameBufferBindMode currentBindMode = GetBindMode();
   FrameBufferBindMode checkMode = FrameBufferBindMode(currentBindMode & bindMode);
   if (checkMode == FBBM_Unbound)
     return FBS_Unbound;
   GLenum status;
   switch (checkMode)
   {
     case FBBM_Read:
       status = glCheckFramebufferStatus(GL_READ_FRAMEBUFFER);
       break;
     case FBBM_Write:
       status = glCheckFramebufferStatus(GL_DRAW_FRAMEBUFFER);
       break;
     case FBBM_ReadWrite:
       status = glCheckFramebufferStatus(GL_DRAW_FRAMEBUFFER);
       if(status == GL_FRAMEBUFFER_COMPLETE)
         glCheckFramebufferStatus(GL_READ_FRAMEBUFFER);
       break;
   }
   switch(status)
   {
     case GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT:
     case GL_FRAMEBUFFER_UNSUPPORTED:
       return FBS_InvalidAttachment;
     case GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT:
       return FBS_MissingAttachment;
     case GL_FRAMEBUFFER_COMPLETE:
       return FBS_Complete;
     default:
       return FBS_UnknownError;
   }
 }
void FrameBuffer::Initialize () static
Initializes this instance.
Definition at line 14 of file FrameBuffer.cpp.
Referenced by RenderManagerAPI::Initialise().
 {
   glGetIntegerv(GL_MAX_COLOR_ATTACHMENTS, &FrameBuffer::MAX_COLOUR_ATTACHMENTS);
   static float offsetX = 0.5f / GetScreenDimensions().x;
   static float offsetY = 0.5f / GetScreenDimensions().y;
   static vec2 verts[4] =
   {
     vec2(-1, 1), vec2(1, 1),
     vec2(1, -1), vec2(-1, -1)
   };
   static vec2 uvs[4] =
   {
     vec2(offsetX, 1 - offsetY), vec2(1 - offsetX, 1 - offsetY),
     vec2(1 - offsetX, offsetY), vec2(offsetX, offsetY)
   };
   GLuint quadBuffers[2];
   glGenVertexArrays(1, &FSQuadVAO);
   glGenBuffers(2, quadBuffers);
   glBindVertexArray(FSQuadVAO);
   glBindBuffer(GL_ARRAY_BUFFER, quadBuffers[0]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(vec2)*4, verts, GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_Vertices);
   glVertexAttribPointer(AL_Vertices, 2, GL_FLOAT, GL_FALSE, 0, 0);
   glBindBuffer(GL_ARRAY_BUFFER, quadBuffers[1]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(vec2)*4, uvs, GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_DiffuseTexCoords);
   glVertexAttribPointer(AL_DiffuseTexCoords, 2, GL_FLOAT, GL_FALSE, 0, 0);
   glBindVertexArray(NULL);
 }
void FrameBuffer::RemoveColourAttachment (GLuint location) private
Removes the color attachment.
Parameters
location The location.
Definition at line 241 of file FrameBuffer.cpp.
 {
   for (int i = 0; i < colourAttachments.size(); i++)
   {
     if (colourAttachments[i] == GL_COLOR_ATTACHMENT0 + location)
       colourAttachments.erase(colourAttachments.begin() + i);
   }
 }
void FrameBuffer::Unbind (FrameBufferBindMode bufferMode = FBBM_ReadWrite)
Unbinds the specified buffer mode.
Parameters
bufferMode The buffer mode.
Definition at line 89 of file FrameBuffer.cpp.
References BindToScreen().
 {
   BindToScreen(bufferMode);
 }
Member Data Documentation
std::vector<GLuint> FrameBuffer::colourAttachments private
The color attachments
Definition at line 135 of file FrameBuffer.h.
GLuint FrameBuffer::FSQuadVAO static
The fs quad vao{CC2D43FA-BBC4-448A-9D0B-7B57ADF2655C}
Definition at line 44 of file FrameBuffer.h.
GLuint FrameBuffer::m_fb = 0 private
The frame buffer.
Definition at line 130 of file FrameBuffer.h.
int FrameBuffer::MAX_COLOUR_ATTACHMENTS = 8 static private
The maximum colour attachments{CC2D43FA-BBC4-448A-9D0B-7B57ADF2655C}
Definition at line 137 of file FrameBuffer.h.
Referenced by AttachColour().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/FrameBuffer.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/FrameBuffer.cpp