ICT397 Game Engine: MultiplicativeBlendEffect Class Reference
MultiplicativeBlendEffect Class Reference
#include <MultiplicativeBlendEffect.h>
Public Member Functions
MultiplicativeBlendEffect ()
Initializes a new instance of the MultiplicativeBlendEffect class.
void Apply (GLuint inputTex0, GLuint inputTex1, GLuint outputTex)
Applies the blend effect.
Private Attributes
FrameBuffer m_fb
The frame buffer
std::unique_ptr< IShader > const & m_pShader
The shader
Detailed Description
Definition at line 13 of file MultiplicativeBlendEffect.h.
Constructor & Destructor Documentation
MultiplicativeBlendEffect::MultiplicativeBlendEffect ()
Initializes a new instance of the MultiplicativeBlendEffect class.
Definition at line 5 of file MultiplicativeBlendEffect.cpp.
References MultiplicativeBlendEffect().
Referenced by RenderManagerAPI::Initialise(), and MultiplicativeBlendEffect().
   : m_pShader(ShaderLibrary::GetInstance().GetShader("MultiplicativeBlendEffect"))
 {
 }
Member Function Documentation
void MultiplicativeBlendEffect::Apply (GLuint inputTex0, GLuint inputTex1, GLuint outputTex)
Applies the blend effect.
Parameters
inputTex0 The input tex0.
inputTex1 The input tex1.
outputTex The output tex.
Definition at line 11 of file MultiplicativeBlendEffect.cpp.
 {
   m_fb.Bind();
   m_fb.AttachColour(0, outputTex);
   glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
   m_pShader->Bind();
   glBindVertexArray(FrameBuffer::FSQuadVAO);
   glActiveTexture(GL_TEXTURE0 + 0);
   glBindTexture(GL_TEXTURE_2D, inputTex0);
   m_pShader->TransmitUniform("inputTex0", 0);
   glActiveTexture(GL_TEXTURE0 + 1);
   glBindTexture(GL_TEXTURE_2D, inputTex1);
   m_pShader->TransmitUniform("inputTex1", 1);
   glDrawArrays(GL_QUADS, 0, 4);
   glBindVertexArray(NULL);
   m_fb.Unbind();
 }
Member Data Documentation
FrameBuffer MultiplicativeBlendEffect::m_fb private
The frame buffer
Definition at line 35 of file MultiplicativeBlendEffect.h.
std::unique_ptr<IShader> const& MultiplicativeBlendEffect::m_pShader private
The shader
Definition at line 40 of file MultiplicativeBlendEffect.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/MultiplicativeBlendEffect.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/MultiplicativeBlendEffect.cpp