ICT397 Game Engine: EngineAPI Class Reference
EngineAPI Class Reference
#include <EngineAPI.h>
Static Public Member Functions
static void Create (int api)
Exposes the functions in the API.
static void Expose (LuaContextHandle contextHandle, string luaAPIName)
Exposes the specified functions.
static IEngine * GetEngine ()
Gets the engine.
Static Private Attributes
static std::unique_ptr< IEngine > s_engine
The s engine{CC2D43FA-BBC4-448A-9D0B-7B57ADF2655C}
Detailed Description
Definition at line 24 of file EngineAPI.h.
Member Function Documentation
void EngineAPI::Create (int api) static
Exposes the functions in the API.
Parameters
contextHandle The context handle.
luaAPIName Name of the lua API.
Creates the engine of specified API.
Parameters
api The API.
Definition at line 13 of file EngineAPI.cpp.
References API_DIRECT_X, API_OPEN_GL, and API_VULKAN.
 {
   if (api == API_OPEN_GL)
     s_engine = std::unique_ptr<IEngine>(GLEngine::Create());
   else if (api == API_DIRECT_X)
     throw std::exception("API not supported.");
   else if (api == API_VULKAN)
     throw std::exception("API not supported.");
   else
     throw std::exception("API not supported.");
 }
void EngineAPI::Expose (LuaContextHandle contextHandle, string luaAPIName) static
Exposes the specified functions.
Parameters
contextHandle The context handle.
luaAPIName Name of the lua API.
Definition at line 50 of file EngineAPI.cpp.
 {
   LuaContext* pContext = LuaManager::GetInstance().GetContext(contextHandle);
   pContext->ExposeFunction(luaAPIName, "Create", Create);
   pContext->ExposeFunction(luaAPIName, "Initialise", Initialise);
   pContext->ExposeFunction(luaAPIName, "BeginUpdate", BeginUpdate);
   pContext->ExposeFunction(luaAPIName, "EndUpdate", EndUpdate);
 }
IEngine * EngineAPI::GetEngine () static
Gets the engine.
Returns
Definition at line 60 of file EngineAPI.cpp.
Referenced by RenderManagerAPI::BeginRender(), BeginUpdate(), RenderManagerAPI::EndRender(), EndUpdate(), and Initialise().
 {
   return s_engine.get();
 }
Member Data Documentation
std::unique_ptr< IEngine > EngineAPI::s_engine static private
The s engine{CC2D43FA-BBC4-448A-9D0B-7B57ADF2655C}
Definition at line 56 of file EngineAPI.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/EngineAPI.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/EngineAPI.cpp