ICT397 Game Engine: GLEngine Class Reference
GLEngine Class Reference
#include <GLEngine.h>
Public Member Functions
virtual void Initialise (int screenWidth, int screenHeight) override
Initialises the engine.
virtual void BeginRender () override
Begins the render.
virtual void EndRender () override
Ends the render.
virtual bool BeginUpdate () override
Begins the update.
virtual void EndUpdate () override
Ends the update.
Public Member Functions inherited from IEngine
virtual ~IEngine ()=0
Finalizes an instance of the IEngine class.
Static Public Member Functions
static IEngine * Create ()
Creates this instance.
Private Member Functions
GLEngine ()
Prevents a default instance of the GLEngine class from being created.
~GLEngine ()
Finalizes an instance of the GLEngine class.
void CreateWindow ()
Creates the window.
bool InitSDL ()
Initializes the SDL API.
bool HandleEvents ()
Handles the input events.
void InitGlew ()
Initializes GLEW
virtual IShader * CreateShader (string const &name, string const &vertFilePath, string const &fragFilePath, std::vector< string > const &attributes, std::vector< string > const &uniforms) const override
Creates the shader.
virtual IRenderableObject * CreateRenderableObject (string const &name, string const &filename) const override
Creates the renderable object.
virtual IInputHandler * CreateInputHandler ()
Creates the input handler.
Private Attributes
SDL_Window * m_screen
The m screen
int m_screenWidth
The screen width
int m_screenHeight
The screen height
LuaObjectInstanceManager * m_instanceManager
The instance manager
Detailed Description
Definition at line 32 of file GLEngine.h.
Constructor & Destructor Documentation
GLEngine::GLEngine () private
Prevents a default instance of the GLEngine class from being created.
Definition at line 69 of file GLEngine.cpp.
Referenced by Create().
 {
 }
GLEngine::~GLEngine () private
Finalizes an instance of the GLEngine class.
Definition at line 164 of file GLEngine.cpp.
 {
 }
Member Function Documentation
void GLEngine::BeginRender () override virtual
Begins the render.
Implements IEngine.
Definition at line 137 of file GLEngine.cpp.
 {
   glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
   glCullFace(GL_BACK);
   glEnable(GL_DEPTH_TEST);
 }
bool GLEngine::BeginUpdate () override virtual
Begins the update.
Returns
Implements IEngine.
Definition at line 150 of file GLEngine.cpp.
 {
   //if (!HandleEvents())
   //  return false;
   InputManager::GetInstance().Update();
   return true;
 }
IEngine * GLEngine::Create () static
Creates this instance.
Returns
IEngine*
Definition at line 13 of file GLEngine.cpp.
References GLEngine().
 {
   return new GLEngine();
 }
IInputHandler * GLEngine::CreateInputHandler () private virtual
Creates the input handler.
Returns
Implements IEngine.
Definition at line 64 of file GLEngine.cpp.
 {
   return new GLInputHandler();
 }
IRenderableObject * GLEngine::CreateRenderableObject (string const & name, string const & filename) const override private virtual
Creates the renderable object.
Parameters
name The name.
filename The filename.
Returns
Implements IEngine.
Definition at line 59 of file GLEngine.cpp.
 {
   return new RenderableObject(name, filename);
 }
IShader * GLEngine::CreateShader (string const & name, string const & vertFilePath, string const & fragFilePath, std::vector< string > const & attributes, std::vector< string > const & uniforms) const override private virtual
Creates the shader.
Parameters
name The name.
vertFilePath The vert file path.
fragFilePath The frag file path.
attributes The attributes.
uniforms The uniforms.
Returns
Implements IEngine.
Definition at line 54 of file GLEngine.cpp.
 {
   return new Shader(name, vertFilePath, fragFilePath, attributes, uniforms);
 }
void GLEngine::CreateWindow () private
Creates the window.
Definition at line 73 of file GLEngine.cpp.
Referenced by Initialise().
 {
   m_screen = SDL_CreateWindow("Arch Engine", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, m_screenWidth, m_screenHeight, SDL_WINDOW_OPENGL);
   SDL_GL_CreateContext(m_screen);
 }
void GLEngine::EndRender () override virtual
Ends the render.
Implements IEngine.
Definition at line 144 of file GLEngine.cpp.
 {
   glFlush();
   SDL_GL_SwapWindow(m_screen);
 }
void GLEngine::EndUpdate () override virtual
Ends the update.
Implements IEngine.
Definition at line 160 of file GLEngine.cpp.
 {
 }
bool GLEngine::HandleEvents () private
Handles the input events.
Returns
void GLEngine::InitGlew () private
Initializes GLEW
Definition at line 41 of file GLEngine.cpp.
Referenced by Initialise().
 {
   //Initialize GLEW
   glewExperimental = GL_TRUE;
   GLenum glewError = glewInit();
   if (glewError != GLEW_OK)
   {
     printf("Error initializing GLEW! %s\n", glewGetErrorString(glewError));
     getchar();
   }
 }
void GLEngine::Initialise (int screenWidth, int screenHeight) override virtual
Initialises the engine.
Parameters
screenWidth Width of the screen.
screenHeight Height of the screen.
Implements IEngine.
Definition at line 107 of file GLEngine.cpp.
References CreateWindow(), InitGlew(), LuaManager::Initialize(), InitSDL(), m_screenHeight, m_screenWidth, and SetScreenDimensions().
 {
   m_screenWidth = screenWidth;
   m_screenHeight = screenHeight;
   vec2i xy = vec2i(screenWidth, screenHeight);
   SetScreenDimensions(xy);
   //Init SDL & create a window
   InitSDL();
   CreateWindow();
   //Init glew
   InitGlew();
   //Seed random generator
   srand(uint(time(NULL)));
   //Init Lua manager so we can start ordering the engine to do stuff
   LuaManager::Initialize();
   //Clear screen for rendering
   glClearColor(0, 0, 0, 1.f);
 }
bool GLEngine::InitSDL () private
Initializes the SDL API.
Returns
Definition at line 79 of file GLEngine.cpp.
Referenced by Initialise().
 {
   if (SDL_Init(SDL_INIT_EVERYTHING) < 0)
   {
     printf("SDL could not initialize! SDL Error: %s\n", SDL_GetError());
     getchar();
     return false;
   }
   if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 2048) == -1)
   {
     printf("SDL sound could not initialize! SDL Error: %s\n", SDL_GetError());
     getchar();
     return false;
   }
   if (TTF_Init() == -1)
   {
     printf("SDL_ttf could not initialize! SDL_ttf Error: %s\n", TTF_GetError());
     return false;
   }
   int result = SDL_GL_SetSwapInterval(0);
   SDL_SetRelativeMouseMode(SDL_TRUE);
   return true;
 }
Member Data Documentation
LuaObjectInstanceManager* GLEngine::m_instanceManager private
The instance manager
Definition at line 128 of file GLEngine.h.
SDL_Window* GLEngine::m_screen private
The m screen
Definition at line 113 of file GLEngine.h.
int GLEngine::m_screenHeight private
The screen height
Definition at line 123 of file GLEngine.h.
Referenced by Initialise().
int GLEngine::m_screenWidth private
The screen width
Definition at line 118 of file GLEngine.h.
Referenced by Initialise().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/GLEngine.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/GLEngine.cpp