ICT397 Game Engine: Mesh Class Reference
Mesh Class Reference
#include <Mesh.h>
Public Member Functions
Mesh ()
Mesh (aiMesh const *pMesh, Bimap< string, int > const &boneLookup)
string const & GetName () const
std::vector< vec2 > const & GetTexCoords (TextureType const &texType) const
std::vector< vec4 > const & GetVertexColours () const
std::vector< VertexBoneIDs > const & GetBoneIDs () const
std::vector< VertexBoneWeights > const & GetBoneWeights () const
int const & GetMaterialIndex () const
mAABB const & GetBounds () const
int GetVertexColoursCount () const
int GetBoneIDCount () const
int GetBoneWeightCount () const
virtual std::vector< vec3 > const & GetVertices () const override
Gets the vertices.
virtual std::vector< vec3 > const & GetNormals () const override
Gets the normals.
virtual std::vector< int > const & GetIndices () const override
Gets the indices.
Public Member Functions inherited from IMesh
virtual std::vector< vec2 > const & GetTexCoords () const
Gets the texture coords.
int GetTexCoordsCount () const
Gets the texture coords count.
int GetVertexCount () const
Gets the vertex count.
int GetNormalCount () const
Gets the normal count.
int GetIndexCount () const
Gets the index count.
Private Member Functions
void LoadTexCoords (aiMesh const *pMesh)
void LoadVertices (aiMesh const *pMesh)
void LoadNormals (aiMesh const *pMesh)
void LoadVertexColours (aiMesh const *pMesh)
void LoadIndices (aiMesh const *pMesh)
void LoadBones (aiMesh const *pMesh, Bimap< string, int > const &boneLookup)
void LoadMaterial (aiMesh const *pMesh)
void CalculateBounds ()
int GetNextWeightSlot (int vertexIndex)
Private Attributes
string m_name
std::vector< vec2 > m_texCoords [2]
std::vector< vec3 > m_vertices
std::vector< vec3 > m_normals
std::vector< vec4 > m_vertexColours
std::vector< int > m_indices
std::vector< VertexBoneIDs > m_boneIDs
std::vector< VertexBoneWeights > m_boneWeights
mAABB m_bounds
int materialIndex
bool m_hasVertexColours
Detailed Description
Definition at line 27 of file Mesh.h.
Constructor & Destructor Documentation
Mesh::Mesh ()
Definition at line 6 of file Mesh.cpp.
References Mesh().
Referenced by Mesh().
   : m_name("")
   , m_bounds{ vec3{ 0, 0, 0 }, vec3{0, 0, 0} }
 {
 }
Mesh::Mesh (aiMesh const * pMesh, Bimap< string, int > const & boneLookup)
Definition at line 12 of file Mesh.cpp.
References CalculateBounds(), LoadBones(), LoadIndices(), LoadMaterial(), LoadNormals(), LoadTexCoords(), LoadVertexColours(), LoadVertices(), and Mesh().
Referenced by Mesh().
   : m_name(pMesh->mName.data)
 {
   LoadTexCoords(pMesh);
   LoadVertices(pMesh);
   LoadNormals(pMesh);
   LoadVertexColours(pMesh);
   LoadIndices(pMesh);
   LoadBones(pMesh, boneLookup);
   LoadMaterial(pMesh);
   CalculateBounds();
 }
Member Function Documentation
void Mesh::CalculateBounds () private
Definition at line 165 of file Mesh.cpp.
Referenced by Mesh().
 {
   m_bounds.min = vec3(FLT_MAX, FLT_MAX, FLT_MAX);
   m_bounds.max = vec3(-FLT_MAX, -FLT_MAX, -FLT_MAX);
   for (int i = 0; i < m_vertices.size(); i++)
   {
     m_bounds.min.x = mMin(m_bounds.min.x, m_vertices[i].x);
     m_bounds.min.y = mMin(m_bounds.min.y, m_vertices[i].y);
     m_bounds.min.z = mMin(m_bounds.min.z, m_vertices[i].z);
     m_bounds.max.x = mMax(m_bounds.max.x, m_vertices[i].x);
     m_bounds.max.y = mMax(m_bounds.max.y, m_vertices[i].y);
     m_bounds.max.z = mMax(m_bounds.max.z, m_vertices[i].z);
   }
 }
int Mesh::GetBoneIDCount () const
Definition at line 187 of file Mesh.cpp.
 {
   return m_boneIDs.size();
 }
std::vector< VertexBoneIDs > const & Mesh::GetBoneIDs () const
Definition at line 42 of file Mesh.cpp.
 {
   return m_boneIDs;
 }
int Mesh::GetBoneWeightCount () const
Definition at line 192 of file Mesh.cpp.
 {
   return m_boneWeights.size();
 }
std::vector< VertexBoneWeights > const & Mesh::GetBoneWeights () const
Definition at line 47 of file Mesh.cpp.
 {
   return m_boneWeights;
 }
mAABB const & Mesh::GetBounds () const
Definition at line 57 of file Mesh.cpp.
References m_bounds.
 {
   return m_bounds;
 }
std::vector< int > const & Mesh::GetIndices () const override virtual
Gets the indices.
Returns
std::vector<vec3>
Implements IMesh.
Definition at line 207 of file Mesh.cpp.
 {
   return m_indices;
 }
int const & Mesh::GetMaterialIndex () const
Definition at line 52 of file Mesh.cpp.
References materialIndex.
 {
   return materialIndex;
 }
string const & Mesh::GetName () const
Definition at line 25 of file Mesh.cpp.
 {
   return m_name;
 }
int Mesh::GetNextWeightSlot (int vertexIndex) private
Definition at line 127 of file Mesh.cpp.
Referenced by LoadBones().
 {
   for (int i = 0; i < MAX_BONES_PER_VERTEX; i++)
   {
     if (m_boneWeights[vertexIndex].boneWeights[i] == 0)
     {
       return i;
     }
   }
   throw std::exception("Too many bones for vertex.");
 }
std::vector< vec3 > const & Mesh::GetNormals () const override virtual
Gets the normals.
Returns
std::vector<vec3>
Implements IMesh.
Definition at line 202 of file Mesh.cpp.
 {
   return m_normals;
 }
std::vector< vec2 > const & Mesh::GetTexCoords (TextureType const & texType) const
Definition at line 30 of file Mesh.cpp.
 {
   return m_texCoords[texType];
 }
std::vector< vec4 > const & Mesh::GetVertexColours () const
Definition at line 36 of file Mesh.cpp.
 {
   return m_vertexColours;
 }
int Mesh::GetVertexColoursCount () const
Definition at line 182 of file Mesh.cpp.
 {
   return m_vertexColours.size();
 }
std::vector< vec3 > const & Mesh::GetVertices () const override virtual
Gets the vertices.
Returns
std::vector<vec3>
Implements IMesh.
Definition at line 197 of file Mesh.cpp.
 {
   return m_vertices;
 }
void Mesh::LoadBones (aiMesh const * pMesh, Bimap< string, int > const & boneLookup) private
Definition at line 140 of file Mesh.cpp.
References GetNextWeightSlot().
Referenced by Mesh().
 {
   m_boneIDs.resize(pMesh->mNumVertices);
   m_boneWeights.resize(pMesh->mNumVertices);
   for (uint i = 0; i < pMesh->mNumBones; i++)
   {
     string boneName = pMesh->mBones[i]->mName.data;
     int boneID = boneLookup.GetValue(boneName);
     for (uint j = 0; j < pMesh->mBones[i]->mNumWeights; j++)
     {
       int pos = pMesh->mBones[i]->mWeights[j].mVertexId;
       int nextFree = GetNextWeightSlot(pos);
       m_boneIDs[pos].boneIDs[nextFree] = boneID;
       m_boneWeights[pos].boneWeights[nextFree] = pMesh->mBones[i]->mWeights[j].mWeight;
     }
   }
 }
void Mesh::LoadIndices (aiMesh const * pMesh) private
Definition at line 116 of file Mesh.cpp.
Referenced by Mesh().
 {
   m_indices.resize(pMesh->mNumFaces * 3);
   for (uint i = 0; i < pMesh->mNumFaces; i++)
   {
     m_indices[i * 3 + 0] = pMesh->mFaces[i].mIndices[0];
     m_indices[i * 3 + 1] = pMesh->mFaces[i].mIndices[1];
     m_indices[i * 3 + 2] = pMesh->mFaces[i].mIndices[2];
   }
 }
void Mesh::LoadMaterial (aiMesh const * pMesh) private
Definition at line 160 of file Mesh.cpp.
Referenced by Mesh().
 {
   materialIndex = pMesh->mMaterialIndex;
 }
void Mesh::LoadNormals (aiMesh const * pMesh) private
Definition at line 93 of file Mesh.cpp.
Referenced by Mesh().
 {
   m_normals.resize(pMesh->mNumVertices);
   for (uint i = 0; i < pMesh->mNumVertices; i++)
     m_normals[i] = ASToGLM(pMesh->mNormals[i]);
 }
void Mesh::LoadTexCoords (aiMesh const * pMesh) private
Definition at line 62 of file Mesh.cpp.
Referenced by Mesh().
 {
   for (int i = 0; i < 2; i++)
   {
     m_texCoords[i].resize(pMesh->mNumVertices);
   }
   for (int uvChannel = 0; uvChannel < 2; uvChannel++)
   {
     if (pMesh->HasTextureCoords(uvChannel))
     {
       for (uint i = 0; i < pMesh->mNumVertices; i++)
       {
         vec3 uv = ASToGLM(pMesh->mTextureCoords[uvChannel][i]);
         m_texCoords[uvChannel][i] = vec2(uv.x, uv.y);
       }
     }
     else
     {
       memcpy(m_texCoords[uvChannel].data(), m_texCoords[0].data(), sizeof(vec2) * m_texCoords[0].size());
     }
   }
 }
void Mesh::LoadVertexColours (aiMesh const * pMesh) private
Definition at line 100 of file Mesh.cpp.
Referenced by Mesh().
 {
     if (pMesh->HasVertexColors(0))
     {
         m_vertexColours.resize(pMesh->mNumVertices);
         for (uint i = 0; i < pMesh->mNumVertices; i++)
             m_vertexColours[i] = ASToGLM(pMesh->mColors[0][i]);
     }
   else
   {
     m_vertexColours.resize(pMesh->mNumVertices);
     for (uint i = 0; i < pMesh->mNumVertices; i++)
       m_vertexColours[i] = vec4(0.43, 0.39, 0.25, 1);
   }
 }
void Mesh::LoadVertices (aiMesh const * pMesh) private
Definition at line 86 of file Mesh.cpp.
Referenced by Mesh().
 {
   m_vertices.resize(pMesh->mNumVertices);
   for (uint i = 0; i < pMesh->mNumVertices; i++)
     m_vertices[i] = ASToGLM(pMesh->mVertices[i]);
 }
Member Data Documentation
std::vector<VertexBoneIDs> Mesh::m_boneIDs private
Definition at line 62 of file Mesh.h.
std::vector<VertexBoneWeights> Mesh::m_boneWeights private
Definition at line 63 of file Mesh.h.
mAABB Mesh::m_bounds private
Definition at line 64 of file Mesh.h.
Referenced by GetBounds().
bool Mesh::m_hasVertexColours private
Definition at line 67 of file Mesh.h.
std::vector<int> Mesh::m_indices private
Definition at line 61 of file Mesh.h.
string Mesh::m_name private
Definition at line 56 of file Mesh.h.
std::vector<vec3> Mesh::m_normals private
Definition at line 59 of file Mesh.h.
std::vector<vec2> Mesh::m_texCoords[2] private
Definition at line 57 of file Mesh.h.
Referenced by Model::LoadVertexAttributes().
std::vector<vec4> Mesh::m_vertexColours private
Definition at line 60 of file Mesh.h.
std::vector<vec3> Mesh::m_vertices private
Definition at line 58 of file Mesh.h.
int Mesh::materialIndex private
Definition at line 65 of file Mesh.h.
Referenced by GetMaterialIndex().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Mesh.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Mesh.cpp