ICT397 Game Engine: Terrain Class Reference
Terrain Class Reference
#include <Terrain.h>
Public Member Functions
Terrain (uint terrainWidth, uint terrainHeight, float heightScale, string const &filepath)
Initializes a new instance of the Terrain class.
void CreateMesh ()
Creates the mesh.
HeightMap * GetHeightMap ()
Gets the height map.
float GetXBlockScale () const
Gets the x block scale.
float GetYBlockScale () const
Gets the y block scale.
float GetHeightScale () const
Gets the height scale.
virtual std::vector< vec3 > const & GetVertices () const override
Gets the vertices.
virtual std::vector< vec3 > const & GetNormals () const override
Gets the normals.
virtual std::vector< int > const & GetIndices () const override
Gets the indices.
virtual std::vector< vec2 > const & GetTexCoords () const override
Gets the indices.
Public Member Functions inherited from IMesh
int GetTexCoordsCount () const
Gets the texture coords count.
int GetVertexCount () const
Gets the vertex count.
int GetNormalCount () const
Gets the normal count.
int GetIndexCount () const
Gets the index count.
Private Member Functions
void GenerateTexCoords ()
Generates the texture coords.
void GenerateTerrainIndices ()
Generates the terrain indices.
void GenerateTerrainVertices ()
Generates the terrain vertices.
void GenerateNormals ()
Generates the normals.
Private Attributes
GLuint gVBO
The vertex buffer object
GLuint gNBO
The normals buffer object
GLuint gIBO
The index buffer object
GLuint gUVBO
The uvs buffer object
GLuint m_texture
std::vector< vec3 > m_vertices
The vertices
std::vector< vec3 > m_normals
The normals
std::vector< int > m_indices
The indices
std::vector< vec2 > m_texCoords
The texture coords
HeightMap * m_pHeightMap
The height map
float m_heightScale
The height scale
float m_xBlockScale
The x block scale
float m_yBlockScale
The y block scale
float m_terrainWidth
The terrain width
float m_terrainHeight
The terrain height
float m_textureWidth
The texture width
float m_textureHeight
The texture height
Detailed Description
Definition at line 20 of file Terrain.h.
Constructor & Destructor Documentation
Terrain::Terrain (uint terrainWidth, uint terrainHeight, float heightScale, string const & filepath)
Initializes a new instance of the Terrain class.
Parameters
terrainWidth Width of the terrain.
terrainHeight Height of the terrain.
heightScale The height scale.
filepath The filepath.
Definition at line 6 of file Terrain.cpp.
References CreateMesh(), HeightMap::GetHeight(), HeightMap::GetWidth(), HeightMap::HeightMap(), m_heightScale, m_pHeightMap, m_terrainHeight, m_terrainWidth, m_xBlockScale, and m_yBlockScale.
Referenced by ForestTerrain::ForestTerrain(), and TerrainAPI::GenerateTerrain().
   : m_terrainWidth(terrainWidth)
   , m_terrainHeight(terrainHeight)
   , m_heightScale(heightScale)
 {
   m_pHeightMap = new HeightMap(filepath);
   m_xBlockScale = terrainWidth / (float)(m_pHeightMap->GetWidth() - 1);
   m_yBlockScale = terrainHeight / (float)(m_pHeightMap->GetHeight() - 1);
   CreateMesh();
 }
Member Function Documentation
void Terrain::CreateMesh ()
Creates the mesh.
Definition at line 150 of file Terrain.cpp.
References GenerateTerrainIndices(), GenerateTerrainVertices(), and GenerateTexCoords().
Referenced by Terrain().
 {
   GenerateTerrainVertices();
   GenerateTerrainIndices();
   //GenerateNormals();
   GenerateTexCoords();
   glGenBuffers(1, &gVBO);
   glGenBuffers(1, &gNBO);
   glGenBuffers(1, &gIBO);
   glBindBuffer(GL_ARRAY_BUFFER, gVBO);
   glBufferData(GL_ARRAY_BUFFER, m_vertices.size() * 3 * sizeof(GLfloat), m_vertices.data(), GL_STATIC_DRAW);
   glBindBuffer(GL_ARRAY_BUFFER, 0);
   glBindBuffer(GL_ARRAY_BUFFER, gNBO);
   glBufferData(GL_ARRAY_BUFFER, m_normals.size() * 3 * sizeof(GLfloat), m_normals.data(), GL_STATIC_DRAW);
   glBindBuffer(GL_ARRAY_BUFFER, 0);
   glBindBuffer(GL_ARRAY_BUFFER, gIBO);
   glBufferData(GL_ARRAY_BUFFER, m_indices.size() * sizeof(GLint), m_indices.data(), GL_STATIC_DRAW);
   glBindBuffer(GL_ARRAY_BUFFER, 0);
 }
void Terrain::GenerateNormals () private
Generates the normals.
Definition at line 36 of file Terrain.cpp.
References HeightMap::GetHeight(), GetHeightMap(), and HeightMap::GetWidth().
 {
   int height = GetHeightMap()->GetHeight();
   int width = GetHeightMap()->GetWidth();
   for (int y = 0; y < height; y++)
   {
     for (int x = 0; x < width; x++)
     {
       float y00 = GetHeightMap()->GetHeightValueAtPixel(vec2(x, y));
       float y10 = GetHeightMap()->GetHeightValueAtPixel(vec2(x + 1, y));
       float y11 = GetHeightMap()->GetHeightValueAtPixel(vec2(x + 1, y + 1));
       float y01 = GetHeightMap()->GetHeightValueAtPixel(vec2(x, y + 1));
       glm::vec3 norm = glm::cross(glm::normalize(glm::vec3(x + 1, y10, y) - glm::vec3(x, y00, y)), glm::normalize(glm::vec3(x, y01, y + 1) - glm::vec3(x, y00, y)));
       glm::vec3 norm2 = glm::cross(glm::normalize(glm::vec3(x + 1, y11, (y + 1)) - glm::vec3(x + 1, y10, y)), glm::normalize(glm::vec3(x, y01, y + 1) - glm::vec3(x + 1, y10, y)));
       m_normals.push_back(norm);
       m_normals.push_back(norm);
       m_normals.push_back(norm);
       m_normals.push_back(norm2);
       m_normals.push_back(norm2);
       m_normals.push_back(norm2);
     }
   }
 }
void Terrain::GenerateTerrainIndices () private
Generates the terrain indices.
Definition at line 85 of file Terrain.cpp.
References HeightMap::GetHeight(), HeightMap::GetWidth(), and m_pHeightMap.
Referenced by CreateMesh().
 {
   uint width = m_pHeightMap->GetWidth();
   uint height = m_pHeightMap->GetHeight();
   for (uint i = 0; i < height - 1; i++)
   {
     for (uint j = 0; j < width - 1; j++)
     {
       uint indexValueL = ((i*width) + j);
       uint indexValueR = ((i*width) + (j + 1));
       uint indexValueBL = ((i + 1)*width) + j;
       uint indexValueBR = (((i + 1)*width) + (j + 1));
       m_indices.push_back(indexValueR);
       m_indices.push_back(indexValueL);
       m_indices.push_back(indexValueBL);
       m_indices.push_back(indexValueBL);
       m_indices.push_back(indexValueBR);
       m_indices.push_back(indexValueR);
     }
   }
 }
void Terrain::GenerateTerrainVertices () private
Generates the terrain vertices.
Definition at line 63 of file Terrain.cpp.
References HeightMap::GetHeight(), HeightMap::GetWidth(), and m_pHeightMap.
Referenced by CreateMesh().
 {
   uint width = m_pHeightMap->GetWidth();
   uint height = m_pHeightMap->GetHeight();
   uint numVerts = width * height;
   vec3 vertex = vec3(0);
   m_vertices.resize(numVerts);
   for (uint y = 0; y < height; y++)
   {
     for (uint x = 0; x < width; x++)
     {
       float heightValue = m_pHeightMap->GetHeightValueAtPixel(vec2(x, y));
       vertex.x = x * m_xBlockScale;
       vertex.y = heightValue * m_heightScale;
       vertex.z = y * m_yBlockScale;
       m_vertices[(y*width) + x] = vertex;
     }
   }
 }
void Terrain::GenerateTexCoords () private
Generates the texture coords.
Definition at line 17 of file Terrain.cpp.
References HeightMap::GetHeight(), HeightMap::GetWidth(), and m_pHeightMap.
Referenced by CreateMesh().
 {
   uint width = m_pHeightMap->GetWidth();
   uint height = m_pHeightMap->GetHeight();
   uint numVerts = width * height;
   m_texCoords.resize(numVerts);
   float scaleX = 1.f / (width - 1);
   float scaleY = 1.f / (height - 1);
   for (uint y = 0; y < height; y++)
   {
     for (uint x = 0; x < width; x++)
     {
       m_texCoords[(y*width) + x] = vec2(x*scaleX, y*scaleY);
     }
   }
 }
HeightMap * Terrain::GetHeightMap ()
Gets the height map.
Returns
Heightmap
Definition at line 110 of file Terrain.cpp.
References m_pHeightMap.
Referenced by ForestTerrain::GenerateForest(), and GenerateNormals().
 {
   return m_pHeightMap;
 }
float Terrain::GetHeightScale () const
Gets the height scale.
Returns
float
Definition at line 125 of file Terrain.cpp.
References m_heightScale.
Referenced by ForestTerrain::GenerateForest().
 {
   return m_heightScale;
 }
std::vector< int > const & Terrain::GetIndices () const override virtual
Gets the indices.
Returns
std::vector<int>
Implements IMesh.
Definition at line 140 of file Terrain.cpp.
 {
   return m_indices;
 }
std::vector< vec3 > const & Terrain::GetNormals () const override virtual
Gets the normals.
Returns
std::vector<vec3>
Implements IMesh.
Definition at line 135 of file Terrain.cpp.
 {
   return m_normals;
 }
std::vector< vec2 > const & Terrain::GetTexCoords () const override virtual
Gets the indices.
Returns
std::vector<int>
Reimplemented from IMesh.
Definition at line 145 of file Terrain.cpp.
 {
   return m_texCoords;
 }
std::vector< vec3 > const & Terrain::GetVertices () const override virtual
Gets the vertices.
Returns
std::vector<vec3>
Implements IMesh.
Definition at line 130 of file Terrain.cpp.
 {
   return m_vertices;
 }
float Terrain::GetXBlockScale () const
Gets the x block scale.
Returns
float
Definition at line 115 of file Terrain.cpp.
References m_xBlockScale.
Referenced by ForestTerrain::GenerateForest().
 {
   return m_xBlockScale;
 }
float Terrain::GetYBlockScale () const
Gets the y block scale.
Returns
float
Definition at line 120 of file Terrain.cpp.
References m_yBlockScale.
Referenced by ForestTerrain::GenerateForest().
 {
   return m_yBlockScale;
 }
Member Data Documentation
GLuint Terrain::gIBO private
The index buffer object
Definition at line 101 of file Terrain.h.
GLuint Terrain::gNBO private
The normals buffer object
Definition at line 96 of file Terrain.h.
GLuint Terrain::gUVBO private
The uvs buffer object
Definition at line 106 of file Terrain.h.
GLuint Terrain::gVBO private
The vertex buffer object
Definition at line 91 of file Terrain.h.
float Terrain::m_heightScale private
The height scale
Definition at line 138 of file Terrain.h.
Referenced by GetHeightScale(), and Terrain().
std::vector<int> Terrain::m_indices private
The indices
Definition at line 123 of file Terrain.h.
std::vector<vec3> Terrain::m_normals private
The normals
Definition at line 118 of file Terrain.h.
HeightMap* Terrain::m_pHeightMap private
The height map
Definition at line 133 of file Terrain.h.
Referenced by GenerateTerrainIndices(), GenerateTerrainVertices(), GenerateTexCoords(), GetHeightMap(), and Terrain().
float Terrain::m_terrainHeight private
The terrain height
Definition at line 158 of file Terrain.h.
Referenced by Terrain().
float Terrain::m_terrainWidth private
The terrain width
Definition at line 153 of file Terrain.h.
Referenced by Terrain().
std::vector<vec2> Terrain::m_texCoords private
The texture coords
Definition at line 128 of file Terrain.h.
GLuint Terrain::m_texture private
Definition at line 108 of file Terrain.h.
float Terrain::m_textureHeight private
The texture height
Definition at line 168 of file Terrain.h.
float Terrain::m_textureWidth private
The texture width
Definition at line 163 of file Terrain.h.
std::vector<vec3> Terrain::m_vertices private
The vertices
Definition at line 113 of file Terrain.h.
float Terrain::m_xBlockScale private
The x block scale
Definition at line 143 of file Terrain.h.
Referenced by GetXBlockScale(), and Terrain().
float Terrain::m_yBlockScale private
The y block scale
Definition at line 148 of file Terrain.h.
Referenced by GetYBlockScale(), and Terrain().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Terrain.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Terrain.cpp