ICT397 Game Engine: IEngine Class Reference
IEngine Class Reference abstract
#include <IEngine.h>
Public Member Functions
virtual void Initialise (int screenWidth, int screenHeight)=0
Initialises the engine.
virtual ~IEngine ()=0
Finalizes an instance of the IEngine class.
virtual void BeginRender ()=0
Begins the render.
virtual void EndRender ()=0
Ends the render.
virtual bool BeginUpdate ()=0
Begins the update.
virtual void EndUpdate ()=0
Ends the update.
virtual IShader * CreateShader (string const &name, string const &vertFilePath, string const &fragFilePath, std::vector< string > const &attributes, std::vector< string > const &uniforms) const =0
Creates the shader.
virtual IRenderableObject * CreateRenderableObject (string const &name, string const &filename) const =0
Creates the renderable object.
virtual IInputHandler * CreateInputHandler ()=0
Creates the input handler.
Detailed Description
Definition at line 28 of file IEngine.h.
Constructor & Destructor Documentation
virtual IEngine::~IEngine () inline pure virtual
Finalizes an instance of the IEngine class.
Definition at line 42 of file IEngine.h.
 {}
Member Function Documentation
virtual void IEngine::BeginRender () pure virtual
Begins the render.
Implemented in GLEngine, and DXEngine.
Referenced by RenderManagerAPI::BeginRender().
virtual bool IEngine::BeginUpdate () pure virtual
Begins the update.
Returns
bool
Implemented in GLEngine, and DXEngine.
Referenced by BeginUpdate().
virtual IInputHandler* IEngine::CreateInputHandler () pure virtual
Creates the input handler.
Returns
Implemented in GLEngine, and DXEngine.
virtual IRenderableObject* IEngine::CreateRenderableObject (string const & name, string const & filename) const pure virtual
Creates the renderable object.
Parameters
name The name.
filename The filename.
Returns
Implemented in GLEngine, and DXEngine.
Referenced by ModelLibrary::AddModel().
virtual IShader* IEngine::CreateShader (string const & name, string const & vertFilePath, string const & fragFilePath, std::vector< string > const & attributes, std::vector< string > const & uniforms) const pure virtual
Creates the shader.
Parameters
name The name.
vertFilePath The vert file path.
fragFilePath The frag file path.
attributes The attributes.
uniforms The uniforms.
Returns
Implemented in GLEngine, and DXEngine.
virtual void IEngine::EndRender () pure virtual
Ends the render.
Implemented in GLEngine, and DXEngine.
Referenced by RenderManagerAPI::EndRender().
virtual void IEngine::EndUpdate () pure virtual
Ends the update.
Implemented in GLEngine, and DXEngine.
Referenced by EndUpdate().
virtual void IEngine::Initialise (int screenWidth, int screenHeight) pure virtual
Initialises the engine.
Parameters
screenWidth Width of the screen.
screenHeight Height of the screen.
Implemented in GLEngine, and DXEngine.
Referenced by Initialise().
The documentation for this class was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/IEngine.h