ICT397 Game Engine: LuaManager Class Reference
LuaManager Class Reference
#include <LuaManager.h>
Public Member Functions
LuaContext * GetContext (LuaContextHandle contextHandle)
Gets the context.
LuaContextHandle CreateContext (string scriptPath)
Creates the context.
void ExposeAPI (LuaContextHandle contextHandle, string luaAPIName, string apiName)
Exposes the API.
void AddAPI (string apiName, LuaAPIExposeFunc exposeFunc)
Adds the API.
Static Public Member Functions
static void Initialize ()
Initializes this instance.
Static Public Member Functions inherited from Singleton< LuaManager >
static LuaManager & GetInstance ()
Private Member Functions
LuaContextHandle ReserveContextHandle ()
Reserves the context handle.
Private Attributes
std::unordered_map< LuaContextHandle, LuaContext * > m_contexts
The lua contexts
std::unordered_map< string, LuaAPIExposeFunc > m_apiExposeFunctions
The m API expose functions
LuaContextHandle nextHandle = 0
The next handle
Additional Inherited Members
Protected Member Functions inherited from Singleton< LuaManager >
Singleton ()
Static Protected Attributes inherited from Singleton< LuaManager >
static LuaManager * p
Detailed Description
Definition at line 19 of file LuaManager.h.
Member Function Documentation
void LuaManager::AddAPI (string apiName, LuaAPIExposeFunc exposeFunc)
Adds the API.
Parameters
apiName Name of the API.
exposeFunc The expose function.
Definition at line 61 of file LuaManager.cpp.
 {
   m_apiExposeFunctions.emplace(apiName, exposeFunc);
 }
LuaContextHandle LuaManager::CreateContext (string scriptPath)
Creates the context.
Parameters
scriptPath The script path.
Returns
Definition at line 23 of file LuaManager.cpp.
References ReserveContextHandle(), and LuaContext::Start().
 {
   LuaContextHandle handle = ReserveContextHandle();
   LuaContext* context = new LuaContext(handle, scriptPath);
   m_contexts.emplace(handle, context);
   context->Start();
   return handle;
 }
void LuaManager::ExposeAPI (LuaContextHandle contextHandle, string luaAPIName, string apiName)
Exposes the API.
Parameters
contextHandle The context handle.
luaAPIName Name of the lua API.
apiName Name of the API.
Definition at line 32 of file LuaManager.cpp.
 {
   LuaAPIExposeFunc exposeFunc = m_apiExposeFunctions.at(apiName);
   exposeFunc(contextHandle, luaAPIName);
 }
LuaContext * LuaManager::GetContext (LuaContextHandle contextHandle)
Gets the context.
Parameters
contextHandle The context handle.
Returns
Definition at line 18 of file LuaManager.cpp.
 {
   return m_contexts.at(contextHandle);
 }
void LuaManager::Initialize () static
Initializes this instance.
Definition at line 38 of file LuaManager.cpp.
Referenced by GLEngine::Initialise(), and main().
 {
   LuaManager& luaManager = LuaManager::GetInstance();
   luaManager.AddAPI("printAPI", PrintAPI::Expose);
   luaManager.AddAPI("objectInstanceAPI", ObjectInstanceAPI::Expose);
   luaManager.AddAPI("luaObjectInstanceManager", LuaObjectInstanceManager::Expose);
   luaManager.AddAPI("modelLibraryAPI", ModelLibraryAPI::Expose);
   luaManager.AddAPI("renderManagerAPI", RenderManagerAPI::Expose);
   luaManager.AddAPI("inputManagerAPI", InputManagerAPI::Expose);
   luaManager.AddAPI("luaVectorUtility", LuaVectorUtility::Expose);
   luaManager.AddAPI("engineAPI", EngineAPI::Expose);
   luaManager.AddAPI("cameraAPI", CameraAPI::Expose);
   luaManager.AddAPI("timeAPI", TimeAPI::Expose);
   luaManager.AddAPI("terrainAPI", TerrainAPI::Expose);
   luaManager.AddAPI("AABBAPI", AABBAPI::Expose);
   luaManager.AddAPI("islandCollisionAPI", IslandCollisionAPI::Expose);
   luaManager.AddAPI("display2DAPI", LuaDisplay2DAPI::Expose);
 }
LuaContextHandle LuaManager::ReserveContextHandle () private
Reserves the context handle.
Returns
Definition at line 66 of file LuaManager.cpp.
References nextHandle.
Referenced by CreateContext().
 {
   return nextHandle++;
 }
Member Data Documentation
std::unordered_map<string, LuaAPIExposeFunc> LuaManager::m_apiExposeFunctions private
The m API expose functions
Definition at line 61 of file LuaManager.h.
std::unordered_map<LuaContextHandle, LuaContext*> LuaManager::m_contexts private
The lua contexts
Definition at line 57 of file LuaManager.h.
LuaContextHandle LuaManager::nextHandle = 0 private
The next handle
Definition at line 65 of file LuaManager.h.
Referenced by ReserveContextHandle().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/LuaManager.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/LuaManager.cpp