ICT397 Game Engine: BoneKeySequence Class Reference
BoneKeySequence Class Reference
#include <BoneKeySequence.h>
Public Member Functions
BoneKeySequence (aiNodeAnim const *pAnim, int boneID)
Initializes a new instance of the BoneKeySequence class.
int GetBoneID () const
Gets the bone identifier.
vec3 GetPosition (float time) const
Gets the position.
quat GetRotation (float time) const
Gets the rotation.
vec3 GetScale (float time) const
Gets the scale.
mat4 GetTransform (float time) const
Gets the transform.
Private Member Functions
void LoadPositionKeys (aiNodeAnim const *pAnim)
Loads the position keys.
void LoadRotationKeys (aiNodeAnim const *pAnim)
Loads the rotation keys.
void LoadScaleKeys (aiNodeAnim const *pAnim)
Loads the scale keys.
Private Attributes
int m_boneID
The bone identifier
std::vector< PositionKey > m_positionKeys
The position keys
std::vector< RotationKey > m_rotationKeys
The rotation keys
std::vector< ScaleKey > m_scaleKeys
The scale keys
Detailed Description
Definition at line 36 of file BoneKeySequence.h.
Constructor & Destructor Documentation
BoneKeySequence::BoneKeySequence (aiNodeAnim const * pAnim, int boneID)
Initializes a new instance of the BoneKeySequence class.
Parameters
pAnim The p anim.
boneID The bone identifier.
Definition at line 6 of file BoneKeySequence.cpp.
References LoadPositionKeys(), LoadRotationKeys(), LoadScaleKeys(), and m_boneID.
   : m_boneID(boneID)
 {
   LoadPositionKeys(pAnim);
   LoadRotationKeys(pAnim);
   LoadScaleKeys(pAnim);
 }
Member Function Documentation
int BoneKeySequence::GetBoneID () const
Gets the bone identifier.
Returns
int
Definition at line 14 of file BoneKeySequence.cpp.
References m_boneID.
 {
   return m_boneID;
 }
vec3 BoneKeySequence::GetPosition (float time) const
Gets the position.
Parameters
time The time.
Returns
vec3
Definition at line 19 of file BoneKeySequence.cpp.
References PositionKey::time.
Referenced by GetTransform().
 {
   if (time <= m_positionKeys[0].time)
     return m_positionKeys[0].position;
   if (time >= m_positionKeys[m_positionKeys.size() - 1].time)
     return m_positionKeys[m_positionKeys.size() - 1].position;
   //Find last frame before the current time
   int lastFrameIndex = 0;
   for (int i = 1; i < m_positionKeys.size(); i++)
     if (m_positionKeys[i].time < time)
       lastFrameIndex = i;
     else
       break;
   PositionKey const& lastKey = m_positionKeys[lastFrameIndex];
   PositionKey const& nextKey = m_positionKeys[lastFrameIndex + 1];
   float timeSinceLast = time - lastKey.time;
   float timeBetweenFrames = nextKey.time - lastKey.time;
   float interpolationFactor = timeSinceLast / timeBetweenFrames;
   interpolationFactor = mClamp(interpolationFactor, 0, 1);
   return glm::lerp(lastKey.position, nextKey.position, interpolationFactor);
 }
quat BoneKeySequence::GetRotation (float time) const
Gets the rotation.
Parameters
time The time.
Returns
quat
Definition at line 46 of file BoneKeySequence.cpp.
References RotationKey::time.
Referenced by GetTransform().
 {
   if (time <= m_rotationKeys[0].time)
     return m_rotationKeys[0].rotation;
   if (time >= m_rotationKeys[m_rotationKeys.size() - 1].time)
     return m_rotationKeys[m_rotationKeys.size() - 1].rotation;
   //Find last frame before the current time
   int lastFrameIndex = 0;
   for (int i = 1; i < m_rotationKeys.size(); i++)
     if (m_rotationKeys[i].time < time)
       lastFrameIndex = i;
     else
       break;
   RotationKey const& lastKey = m_rotationKeys[lastFrameIndex];
   RotationKey const& nextKey = m_rotationKeys[lastFrameIndex + 1];
   float timeSinceLast = time - lastKey.time;
   float timeBetweenFrames = nextKey.time - lastKey.time;
   float interpolationFactor = timeSinceLast / timeBetweenFrames;
   interpolationFactor = mClamp(interpolationFactor, 0, 1);
   return glm::lerp(lastKey.rotation, nextKey.rotation, interpolationFactor);
 }
vec3 BoneKeySequence::GetScale (float time) const
Gets the scale.
Parameters
time The time.
Returns
vec3
Definition at line 73 of file BoneKeySequence.cpp.
References ScaleKey::time.
Referenced by GetTransform().
 {
   if (time <= m_scaleKeys[0].time)
     return m_scaleKeys[0].scale;
   if (time >= m_scaleKeys[m_scaleKeys.size() - 1].time)
     return m_scaleKeys[m_scaleKeys.size() - 1].scale;
   //Find last frame before the current time
   int lastFrameIndex = 0;
   for (int i = 1; i < m_scaleKeys.size(); i++)
     if (m_scaleKeys[i].time < time)
       lastFrameIndex = i;
     else
       break;
   ScaleKey const& lastKey = m_scaleKeys[lastFrameIndex];
   ScaleKey const& nextKey = m_scaleKeys[lastFrameIndex + 1];
   float timeSinceLast = time - lastKey.time;
   float timeBetweenFrames = nextKey.time - lastKey.time;
   float interpolationFactor = timeSinceLast / timeBetweenFrames;
   interpolationFactor = mClamp(interpolationFactor, 0, 1);
   return glm::lerp(lastKey.scale, nextKey.scale, interpolationFactor);
 }
mat4 BoneKeySequence::GetTransform (float time) const
Gets the transform.
Parameters
time The time.
Returns
mat4
Definition at line 100 of file BoneKeySequence.cpp.
References GetPosition(), GetRotation(), and GetScale().
 {
   vec3 position = GetPosition(time);
   vec3 scale = GetScale(time);
   quat rotation = GetRotation(time);
   mat4 translationMatrix = glm::translate(position);
   mat4 scalingMatrix = glm::scale(scale);
   mat4 rotationMatrix = mat4(rotation);
   return translationMatrix * rotationMatrix * scalingMatrix;
 }
void BoneKeySequence::LoadPositionKeys (aiNodeAnim const * pAnim) private
Loads the position keys.
Parameters
pAnim The p anim.
Definition at line 113 of file BoneKeySequence.cpp.
Referenced by BoneKeySequence().
 {
   for (uint i = 0; i < pAnim->mNumPositionKeys; i++)
       m_positionKeys.push_back(PositionKey{ float(pAnim->mPositionKeys[i].mTime), ASToGLM(pAnim->mPositionKeys[i].mValue) });
 }
void BoneKeySequence::LoadRotationKeys (aiNodeAnim const * pAnim) private
Loads the rotation keys.
Parameters
pAnim The p anim.
Definition at line 119 of file BoneKeySequence.cpp.
Referenced by BoneKeySequence().
 {
   for (uint i = 0; i < pAnim->mNumRotationKeys; i++)
       m_rotationKeys.push_back(RotationKey{ float(pAnim->mRotationKeys[i].mTime), ASToGLM(pAnim->mRotationKeys[i].mValue) });
 }
void BoneKeySequence::LoadScaleKeys (aiNodeAnim const * pAnim) private
Loads the scale keys.
Parameters
pAnim The p anim.
Definition at line 125 of file BoneKeySequence.cpp.
Referenced by BoneKeySequence().
 {
   for (uint i = 0; i < pAnim->mNumScalingKeys; i++)
       m_scaleKeys.push_back(ScaleKey{ float(pAnim->mScalingKeys[i].mTime), ASToGLM(pAnim->mScalingKeys[i].mValue) });
 }
Member Data Documentation
int BoneKeySequence::m_boneID private
The bone identifier
Definition at line 88 of file BoneKeySequence.h.
Referenced by BoneKeySequence(), and GetBoneID().
std::vector<PositionKey> BoneKeySequence::m_positionKeys private
The position keys
Definition at line 93 of file BoneKeySequence.h.
std::vector<RotationKey> BoneKeySequence::m_rotationKeys private
The rotation keys
Definition at line 98 of file BoneKeySequence.h.
std::vector<ScaleKey> BoneKeySequence::m_scaleKeys private
The scale keys
Definition at line 103 of file BoneKeySequence.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/BoneKeySequence.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/BoneKeySequence.cpp