ICT397 Game Engine: MCamera Class Reference
MCamera Class Reference
#include <MCamera.h>
Public Member Functions
MCamera ()
default constructor
MCamera (float fov, int screenwidth, int screenheight, float nearplane, float farplane)
vec3 Forward () const
Calculates the forward vector of the camera.
vec3 Backward () const
Calculates the backward vector of the camera.
vec3 Up () const
Calculates the up vector of the camera.
vec3 Down () const
Calculates the down vector of the camera.
vec3 Left () const
Calculates the left vector of the camera.
vec3 Right () const
Calculates the right vector of the camera.
void SetPosition (vec3 pos)
Set the position of the camera.
vec3 GetPosition () const
Get the position of the camera.
vec3 ForwardNoPitch () const
Gets the forward direction of the camera, but disregard changes in the pitch of the camera This allows the player to look up while still moving forward instead of up and forward.
mat4 getProjectionMatrix () const
Get the projection matrix of the camera.
vec3 BackwardNoPitch () const
Gets the backwards direction of the camera, but disregard changes in the pitch of the camera.
mat4 getViewMatrix () const
Get the view matrix.
void SetClipPlanes (float near, float far)
Set the near plane and far plane.
Public Member Functions inherited from AffineTransformable
AffineTransformable ()
Initializes a new instance of the AffineTransformable class.
AffineTransformable (vec3 const &translation, float yaw, float pitch, float roll, vec3 const &scale)
Initializes a new instance of the AffineTransformable class.
vec3 const & GetTranslation () const
Gets the translation.
void SetTranslation (vec3 const &translation)
Sets the translation.
void SetTranslation (float x, float y, float z)
Sets the translation.
mat4 const & GetOrientation () const
Gets the orientation.
void SetOrientation (float degYaw, float degPitch, float degRoll)
Sets the orientation.
float GetYaw () const
Gets the yaw.
void SetYaw (float degYaw)
Sets the yaw.
float GetPitch () const
Gets the pitch.
void SetPitch (float degPitch)
Sets the pitch.
float GetRoll () const
Gets the roll.
void SetRoll (float degRoll)
Sets the roll.
vec3 const & GetScale () const
Gets the scale.
void SetScale (vec3 const &scale)
Sets the scale.
mat4 GetTransform () const
Gets the transform.
void SetTransform (mat4 const &transform)
Sets the transform.
void SetTransform (vec3 const &translation, float yaw, float pitch, float roll, vec3 const &scale)
Sets the transform.
Private Attributes
mat4 projectionMatrix
the projection matrix
Detailed Description
Definition at line 23 of file MCamera.h.
Constructor & Destructor Documentation
MCamera::MCamera ()
default constructor
Definition at line 6 of file MCamera.cpp.
References AffineTransformable::AffineTransformable().
Referenced by MPlayer::MPlayer().
   : AffineTransformable()
 {
     projectionMatrix = glm::perspective(DegToRad(60.f), (float)GetScreenDimensions().x / (float)GetScreenDimensions().y, GetNearPlane(), GetFarPlane());
 }
MCamera::MCamera (float fov, int screenwidth, int screenheight, float nearplane, float farplane)
Definition at line 12 of file MCamera.cpp.
 {
     projectionMatrix = glm::perspective(DegToRad(fov), (float)screenwidth / screenheight, nearplane, farplane);
 }
Member Function Documentation
vec3 MCamera::Backward () const
Calculates the backward vector of the camera.
Returns
vec3
Definition at line 29 of file MCamera.cpp.
References Forward().
 {
     return -Forward();
 }
vec3 MCamera::BackwardNoPitch () const
Gets the backwards direction of the camera, but disregard changes in the pitch of the camera.
Returns
vec3
Definition at line 84 of file MCamera.cpp.
References ForwardNoPitch().
 {
     return -ForwardNoPitch();
 }
vec3 MCamera::Down () const
Calculates the down vector of the camera.
Returns
vec3
Definition at line 34 of file MCamera.cpp.
Referenced by Up().
 {
     vec4 vsDown(0, -1, 0, 0);
     vec4 wsDown = GetTransform() * vsDown;
     return normalize(vec3(wsDown.x, wsDown.y, wsDown.z));
 }
vec3 MCamera::Forward () const
Calculates the forward vector of the camera.
Returns
vec3
Definition at line 22 of file MCamera.cpp.
Referenced by Backward(), ForwardNoPitch(), and MPlayer::GetPickingRay().
 {
     vec4 vsForward(0, 0, -1, 0);
     vec4 wsForward = GetTransform() * vsForward;
     return normalize(vec3(wsForward.x,wsForward.y,wsForward.z));
 }
vec3 MCamera::ForwardNoPitch () const
Gets the forward direction of the camera, but disregard changes in the pitch of the camera This allows the player to look up while still moving forward instead of up and forward.
Returns
vec3
Definition at line 76 of file MCamera.cpp.
References Forward().
Referenced by BackwardNoPitch().
 {
     vec3 forward = Forward();
     forward.y = 0;
     return normalize(forward);
 }
vec3 MCamera::GetPosition () const
Get the position of the camera.
Returns
vec3
Definition at line 66 of file MCamera.cpp.
References AffineTransformable::GetTranslation().
Referenced by MPlayer::GetPickingRay().
 {
   return GetTranslation();
 }
mat4 MCamera::getProjectionMatrix () const
Get the projection matrix of the camera.
Returns
mat4
Definition at line 71 of file MCamera.cpp.
References projectionMatrix.
Referenced by RenderManagerAPI::RenderFromCamera(), and RenderManagerAPI::RenderObject().
 {
     return projectionMatrix;
 }
mat4 MCamera::getViewMatrix () const
Get the view matrix.
Returns
mat4
Definition at line 90 of file MCamera.cpp.
Referenced by RenderManagerAPI::RenderFromCamera(), and RenderManagerAPI::RenderObject().
 {
   return inverse(GetTransform());
 }
vec3 MCamera::Left () const
Calculates the left vector of the camera.
Returns
vec3
Definition at line 47 of file MCamera.cpp.
Referenced by Right().
 {
     vec4 vsLeft(-1, 0, 0, 0);
     vec4 wsLeft = GetTransform() * vsLeft;
     return normalize(vec3(wsLeft.x,wsLeft.y,wsLeft.z));
 }
vec3 MCamera::Right () const
Calculates the right vector of the camera.
Returns
vec3
Definition at line 54 of file MCamera.cpp.
References Left().
 {
     return -Left();
 }
void MCamera::SetClipPlanes (float near, float far)
Set the near plane and far plane.
Returns
void
Definition at line 17 of file MCamera.cpp.
 {
   projectionMatrix = glm::perspective(DegToRad(60.f), (float)GetScreenDimensions().x / (float)GetScreenDimensions().y, near, far);
 }
void MCamera::SetPosition (vec3 pos)
Set the position of the camera.
Returns
void
Definition at line 61 of file MCamera.cpp.
References AffineTransformable::SetTranslation().
 {
   SetTranslation(pos);
 }
vec3 MCamera::Up () const
Calculates the up vector of the camera.
Returns
vec3
Definition at line 42 of file MCamera.cpp.
References Down().
 {
     return -Down();
 }
Member Data Documentation
mat4 MCamera::projectionMatrix private
the projection matrix
Definition at line 25 of file MCamera.h.
Referenced by getProjectionMatrix().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/MCamera.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/MCamera.cpp