ICT397 Game Engine: RenderableObject Class Reference
RenderableObject Class Reference
#include <RenderableObject.h>
Public Member Functions
RenderableObject (string const &name, string const &filename)
Initializes a new instance of the RenderableObject class.
~RenderableObject ()
Finalizes an instance of the RenderableObject class.
void Initialise () override
Initialises this instance.
void Render (mat4 const &worldMatrix, mat4 const &viewMatrix, mat4 const &projectionMatrix, float time, int animationIndex) const override
The render method.
void Destroy () override
Destroys this instance.
virtual int GetAnimationCount () const override
Gets the animation count.
virtual int GetAnimationIndex (string const &animationName) const override
Gets the index of the animation.
virtual string const & GetAnimationName (int animationIndex) const override
Gets the name of the animation.
virtual IMesh const & GetMesh (int meshIndex) const override
Gets the mesh.
virtual int GetMeshCount () const override
Gets the mesh count.
void BindObject () const override
Binds the object.
void BindMesh (int meshIndex) const override
Binds the mesh.
Public Member Functions inherited from IMeshCollection
std::vector< vec3 > GetVertices () const
Gets the vertices.
std::vector< vec3 > GetNormals () const
Gets the normals.
std::vector< vec3 > GetAABB () const
Gets Axis aligned bounding box - index 0=min, 1=max.
std::vector< int > GetIndices () const
Gets the indices.
int GetVertexCount () const
Gets the vertex count.
int GetNormalCount () const
Gets the normal count.
int GetIndexCount () const
Gets the index count.
Private Member Functions
void BindMaterial (int meshIndex) const
Binds the material.
void SetFillMode (FillMode fillMode) const
Sets the fill mode.
void UpdateAnimation (float time, int activeAnimation) const
Updates the animation.
void UploadMatrices (mat4 const &worldMatrix, mat4 const &viewMatrix, mat4 const &projectionMatrix) const
Uploads the matrices.
Private Attributes
Model * m_pModel
The model
GLuint m_VAO
The vertex array object
GLuint m_buffers [BT_NUM_BUFFERS]
The buffers
int boundMeshIndex
The bound mesh index
Detailed Description
Definition at line 50 of file RenderableObject.h.
Constructor & Destructor Documentation
RenderableObject::RenderableObject (string const & name, string const & filename)
Initializes a new instance of the RenderableObject class.
Parameters
name The name.
filename The filename.
Definition at line 13 of file RenderableObject.cpp.
References Initialise(), m_pModel, Model::m_texCoords, Model::Model(), and RenderableObject().
Referenced by RenderableObject().
   : m_VAO(0)
 {
   memset(m_buffers, 0, sizeof(GLuint)* BT_NUM_BUFFERS);
   m_pModel = new Model(name, filename);
   Initialise();
 }
RenderableObject::~RenderableObject ()
Finalizes an instance of the RenderableObject class.
Definition at line 21 of file RenderableObject.cpp.
References Destroy().
 {
   Destroy();
 }
Member Function Documentation
void RenderableObject::BindMaterial (int meshIndex) const private
Binds the material.
Parameters
meshIndex Index of the mesh.
Definition at line 209 of file RenderableObject.cpp.
References Material::GetDiffuseTextureCount(), Model::GetMeshMaterial(), and m_pModel.
Referenced by BindMesh().
 {
     std::unique_ptr<IShader> const& shader = ShaderLibrary::GetInstance().CurrentShader();
     Material const& material = m_pModel->GetMeshMaterial(meshIndex);
     shader->TransmitUniform("DIFFUSE_COUNT", (int)material.GetDiffuseTextureCount());
     if (material.GetDiffuseTextureCount() > 1)
     {
       shader->TransmitUniform("DIFFUSE_SOURCE", int(DS_MultiTexture));
     }
     if(material.GetDiffuseTextureCount() == 1)
     {
       shader->TransmitUniform("DIFFUSE_SOURCE", int(DS_Texture));
     }
     for (int i = 0; i < material.GetDiffuseTextureCount(); i++)
     {
       glActiveTexture(GL_TEXTURE0 + TL_Diffuse0 + i);
       glBindTexture(GL_TEXTURE_2D, TextureLibrary::GetInstance().GetTexture(material.GetTextureName(TextureType(TT_Diffuse0 + i))));
       shader->TransmitUniform("DIFFUSE_MAP" + std::to_string(i), int(TL_Diffuse0 + i));
     }
     if(material.GetDiffuseTextureCount() == 0)
     {
       shader->TransmitUniform("DIFFUSE_SOURCE", int(DS_VertexColour));
     }
     string alphaTexture = m_pModel->GetMeshTextureName(meshIndex, TT_Alpha);
     if (alphaTexture != "Texture not supplied.")
     {
       glActiveTexture(GL_TEXTURE0 + int(TL_Alpha));
       glBindTexture(GL_TEXTURE_2D, TextureLibrary::GetInstance().GetTexture(alphaTexture));
       shader->TransmitUniform("ALPHA_MAP", int(TL_Alpha));
       shader->TransmitUniform("USE_ALPHA_MAP", 1);
     }
     else
     {
       shader->TransmitUniform("USE_ALPHA_MAP", 0);
     }
 }
void RenderableObject::BindMesh (int meshIndex) const override virtual
Binds the mesh.
Parameters
meshIndex Index of the mesh.
Implements IRenderableObject.
Definition at line 202 of file RenderableObject.cpp.
References BindMaterial(), and boundMeshIndex.
 {
   boundMeshIndex = meshIndex;
   BindMaterial(meshIndex);
 }
void RenderableObject::BindObject () const override virtual
Binds the object.
Implements IRenderableObject.
Definition at line 197 of file RenderableObject.cpp.
 {
   glBindVertexArray(m_VAO);
 }
void RenderableObject::Destroy () override virtual
Destroys this instance.
Implements IRenderableObject.
Definition at line 158 of file RenderableObject.cpp.
Referenced by ~RenderableObject().
 {
   if (m_buffers[0] != 0)
   {
     glDeleteBuffers(BT_NUM_BUFFERS, m_buffers);
   }
   if (m_VAO != 0)
   {
     glDeleteVertexArrays(1, &m_VAO);
     m_VAO = 0;
   }
 }
int RenderableObject::GetAnimationCount () const override virtual
Gets the animation count.
Returns
Implements IAnimated.
Definition at line 172 of file RenderableObject.cpp.
References Model::GetAnimationCount(), and m_pModel.
 {
   return m_pModel->GetAnimationCount();
 }
int RenderableObject::GetAnimationIndex (string const & animationName) const override virtual
Gets the index of the animation.
Parameters
animationName Name of the animation.
Returns
int
Implements IAnimated.
Definition at line 177 of file RenderableObject.cpp.
References Model::GetAnimationIndex(), and m_pModel.
 {
   return m_pModel->GetAnimationIndex(animationName);
 }
string const & RenderableObject::GetAnimationName (int animationIndex) const override virtual
Gets the name of the animation.
Parameters
animationIndex Index of the animation.
Returns
Implements IAnimated.
Definition at line 182 of file RenderableObject.cpp.
References Model::GetAnimationName(), and m_pModel.
 {
   return m_pModel->GetAnimationName(animationIndex);
 }
IMesh const & RenderableObject::GetMesh (int meshIndex) const override virtual
Gets the mesh.
Parameters
meshIndex Index of the mesh.
Returns
Implements IMeshCollection.
Definition at line 187 of file RenderableObject.cpp.
References Model::GetMesh(), and m_pModel.
 {
   return m_pModel->GetMesh(meshIndex);
 }
int RenderableObject::GetMeshCount () const override virtual
Gets the mesh count.
Returns
Implements IMeshCollection.
Definition at line 192 of file RenderableObject.cpp.
References Model::GetMeshCount(), and m_pModel.
 {
   return m_pModel->GetMeshCount();
 }
void RenderableObject::Initialise () override virtual
Initialises this instance.
Implements IRenderableObject.
Definition at line 91 of file RenderableObject.cpp.
Referenced by RenderableObject().
 {
   std::vector<vec3> const& vertices = m_pModel->GetVertices();
   std::vector<int> const& indices = m_pModel->GetIndices();
   std::vector<vec3> const& normals = m_pModel->GetNormals();
   std::vector<vec2> const& diffuseTexCoords = m_pModel->GetTexCoords(TT_Diffuse0);
   std::vector<vec2> const& alphaTexCoords = m_pModel->GetTexCoords(TT_Alpha);
   std::vector<VertexBoneIDs> const& boneIDs = m_pModel->GetBoneIDs();
   std::vector<VertexBoneWeights> const& boneWeights = m_pModel->GetBoneWeights();
   std::vector<vec4> const& vertexColours = m_pModel->GetVertexColours();
   glGenVertexArrays(1, &m_VAO);
   glBindVertexArray(m_VAO);
   glGenBuffers(BT_NUM_BUFFERS, m_buffers);
   glBindBuffer(GL_ARRAY_BUFFER, m_buffers[BT_VERTEX_BUFFER]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(vertices[0])*vertices.size(), &vertices[0], GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_Vertices);
   glVertexAttribPointer(AL_Vertices, 3, GL_FLOAT, GL_FALSE, 0, 0);
   glBindBuffer(GL_ARRAY_BUFFER, m_buffers[BT_DIFFUSE_TEXCOORD_BUFFER]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(diffuseTexCoords[0])*diffuseTexCoords.size(), &diffuseTexCoords[0], GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_DiffuseTexCoords);
   glVertexAttribPointer(AL_DiffuseTexCoords, 2, GL_FLOAT, GL_FALSE, 0, 0);
   glBindBuffer(GL_ARRAY_BUFFER, m_buffers[BT_ALPHA_TEXCOORD_BUFFER]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(alphaTexCoords[0])*alphaTexCoords.size(), &alphaTexCoords[0], GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_AlphaTexCoords);
   glVertexAttribPointer(AL_AlphaTexCoords, 2, GL_FLOAT, GL_FALSE, 0, 0);
   glBindBuffer(GL_ARRAY_BUFFER, m_buffers[BT_NORMAL_BUFFER]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(normals[0])*normals.size(), &normals[0], GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_Normals);
   glVertexAttribPointer(AL_Normals, 3, GL_FLOAT, GL_FALSE, 0, 0);
   glBindBuffer(GL_ARRAY_BUFFER, m_buffers[BT_BONE_ID_BUFFER]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(boneIDs[0])*boneIDs.size(), &boneIDs[0], GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_BoneIDs);
   glVertexAttribIPointer(AL_BoneIDs, 4, GL_INT, 0, 0);
   glBindBuffer(GL_ARRAY_BUFFER, m_buffers[BT_BONE_WEIGHT_BUFFER]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(boneWeights[0])*boneWeights.size(), &boneWeights[0], GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_BoneWeights);
   glVertexAttribPointer(AL_BoneWeights, 4, GL_FLOAT, GL_FALSE, 0, 0);
   glBindBuffer(GL_ARRAY_BUFFER, m_buffers[BT_VERTEX_COLOUR_BUFFER]);
   glBufferData(GL_ARRAY_BUFFER, sizeof(vertexColours[0])*vertexColours.size(), &vertexColours[0], GL_STATIC_DRAW);
   glEnableVertexAttribArray(AL_VertexColours);
   glVertexAttribPointer(AL_VertexColours, 4, GL_FLOAT, GL_FALSE, 0, 0);
   glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, m_buffers[BT_INDEX_BUFFER]);
   glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(indices[0]) * indices.size(), &indices[0], GL_STATIC_DRAW);
   glBindVertexArray(NULL);
 }
void RenderableObject::Render (mat4 const & worldMatrix, mat4 const & viewMatrix, mat4 const & projectionMatrix, float time, int animationIndex) const override virtual
The render method.
Parameters
worldMatrix The world matrix.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
time The time.
animationIndex Index of the animation.
Implements IRenderableObject.
Definition at line 150 of file RenderableObject.cpp.
References boundMeshIndex, Model::GetMeshIndexRange(), m_pModel, UpdateAnimation(), and UploadMatrices().
 {
   UploadMatrices(worldMatrix, viewMatrix, projectionMatrix);
   UpdateAnimation(time, animationIndex);
   IndexRange const& range = m_pModel->GetMeshIndexRange(boundMeshIndex);
   glDrawElementsBaseVertex(GL_TRIANGLES, range.indexCount, GL_UNSIGNED_INT, (void*)(sizeof(int)*range.firstIndexOffset), range.firstVertex);
 }
void RenderableObject::SetFillMode (FillMode fillMode) const private
Sets the fill mode.
Parameters
fillMode The fill mode.
Definition at line 26 of file RenderableObject.cpp.
 {
   switch (fillMode)
   {
     case FM_Line:
       glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
       break;
     case FM_Fill:
       glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
       break;
   }
 }
void RenderableObject::UpdateAnimation (float time, int activeAnimation) const private
Updates the animation.
Parameters
time The time.
activeAnimation The active animation.
Definition at line 39 of file RenderableObject.cpp.
References Model::HasAnimation(), and m_pModel.
Referenced by Render().
 {
   std::unique_ptr<IShader> const& shader = ShaderLibrary::GetInstance().CurrentShader();
   if (m_pModel->HasAnimation() && activeAnimation >= 0)
   {
     std::vector<glm::mat4> bones = m_pModel->GetBoneTransforms(activeAnimation, time);
     shader->TransmitUniformArray("BONES", bones.data(), bones.size());
     shader->TransmitUniform("ANIMATION_ENABLED", 1);
   }
   else
   {
     shader->TransmitUniform("ANIMATION_ENABLED", 0);
   }
 }
void RenderableObject::UploadMatrices (mat4 const & worldMatrix, mat4 const & viewMatrix, mat4 const & projectionMatrix) const private
Uploads the matrices.
Parameters
worldMatrix The world matrix.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
Definition at line 55 of file RenderableObject.cpp.
Referenced by Render().
 {
   std::unique_ptr<IShader> const& shader = ShaderLibrary::GetInstance().CurrentShader();
   if (shader->HasUniform("WORLD_MATRIX"))
     shader->TransmitUniform("WORLD_MATRIX", worldMatrix);
   if (shader->HasUniform("VIEW_MATRIX"))
     shader->TransmitUniform("VIEW_MATRIX", viewMatrix);
   if (shader->HasUniform("PROJECTION_MATRIX"))
     shader->TransmitUniform("PROJECTION_MATRIX", projectionMatrix);
   if (shader->HasUniform("INVERSE_WORLD_MATRIX"))
     shader->TransmitUniform("INVERSE_WORLD_MATRIX", glm::inverse(worldMatrix));
   if (shader->HasUniform("INVERSE_VIEW_MATRIX"))
     shader->TransmitUniform("INVERSE_VIEW_MATRIX", glm::inverse(viewMatrix));
   if (shader->HasUniform("INVERSE_PROJECTION_MATRIX"))
     shader->TransmitUniform("INVERSE_PROJECTION_MATRIX", glm::inverse(projectionMatrix));
   if (shader->HasUniform("WORLD_VIEW_PROJECTION_MATRIX"))
   {
     glm::mat4 wvp = projectionMatrix * viewMatrix * worldMatrix;
     shader->TransmitUniform("WORLD_VIEW_PROJECTION_MATRIX", wvp);
   }
   if (shader->HasUniform("CAMERA_POSITION"))
   {
       vec4 cam =  inverse(viewMatrix) * glm::vec4(0.0f, 0.0f, 0.0f, 1.0f);
       shader->TransmitUniform("CAMERA_POSITION", vec3(cam.x, cam.y, cam.z));
   }
 }
Member Data Documentation
int RenderableObject::boundMeshIndex mutable private
The bound mesh index
Definition at line 151 of file RenderableObject.h.
Referenced by BindMesh(), and Render().
GLuint RenderableObject::m_buffers[BT_NUM_BUFFERS] private
The buffers
Definition at line 146 of file RenderableObject.h.
Model* RenderableObject::m_pModel private
The model
Definition at line 136 of file RenderableObject.h.
Referenced by BindMaterial(), GetAnimationCount(), GetAnimationIndex(), GetAnimationName(), GetMesh(), GetMeshCount(), Render(), RenderableObject(), and UpdateAnimation().
GLuint RenderableObject::m_VAO private
The vertex array object
Definition at line 141 of file RenderableObject.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/RenderableObject.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/RenderableObject.cpp