ICT397 Game Engine: GodRaysEffect Class Reference
GodRaysEffect Class Reference
#include <GodRaysEffect.h>
Public Member Functions
GodRaysEffect ()
Initializes a new instance of the GodRaysEffect class.
void Apply (GLuint sceneTex, GLuint depthTex, GLuint outputTex, vec3 ssLightPos)
Applies the god rays effect.
Private Attributes
FrameBuffer m_fb
The frame buffer
DepthThresholdEffect m_depthThreshEffect
The depth threshold effect
RayEffect m_rayEffect
The ray effect
AdditiveBlendEffect m_additiveBlendEffect
The additive blend effect
std::unique_ptr< IShader > const & m_pShader
The shader
GLuint depthMaskTex
The depth mask texture
GLuint rayTex
The ray texture
Detailed Description
Definition at line 19 of file GodRaysEffect.h.
Constructor & Destructor Documentation
GodRaysEffect::GodRaysEffect ()
Initializes a new instance of the GodRaysEffect class.
Definition at line 5 of file GodRaysEffect.cpp.
References GodRaysEffect().
Referenced by GodRaysEffect(), and RenderManagerAPI::Initialise().
   : m_pShader(ShaderLibrary::GetInstance().GetShader("RayEffect"))
 {
     depthMaskTex = CreateVec3Texture();
     rayTex = CreateVec3Texture();
 }
Member Function Documentation
void GodRaysEffect::Apply (GLuint sceneTex, GLuint depthTex, GLuint outputTex, vec3 ssLightPos)
Applies the god rays effect.
Parameters
sceneTex The scene tex.
depthTex The depth tex.
outputTex The output tex.
ssLightPos The screen space light position.
Definition at line 12 of file GodRaysEffect.cpp.
 {
     m_depthThreshEffect.Apply(depthTex, depthMaskTex, ssLightPos.z);
     m_rayEffect.Apply(depthMaskTex, rayTex, vec2(ssLightPos.x, ssLightPos.y));
     m_additiveBlendEffect.Apply(rayTex, sceneTex, outputTex);
 }
Member Data Documentation
GLuint GodRaysEffect::depthMaskTex private
The depth mask texture
Definition at line 66 of file GodRaysEffect.h.
AdditiveBlendEffect GodRaysEffect::m_additiveBlendEffect private
The additive blend effect
Definition at line 56 of file GodRaysEffect.h.
DepthThresholdEffect GodRaysEffect::m_depthThreshEffect private
The depth threshold effect
Definition at line 46 of file GodRaysEffect.h.
FrameBuffer GodRaysEffect::m_fb private
The frame buffer
Definition at line 41 of file GodRaysEffect.h.
std::unique_ptr<IShader> const& GodRaysEffect::m_pShader private
The shader
Definition at line 61 of file GodRaysEffect.h.
RayEffect GodRaysEffect::m_rayEffect private
The ray effect
Definition at line 51 of file GodRaysEffect.h.
GLuint GodRaysEffect::rayTex private
The ray texture
Definition at line 71 of file GodRaysEffect.h.
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/GodRaysEffect.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/GodRaysEffect.cpp