ICT397 Game Engine: HeightMap Class Reference
HeightMap Class Reference
#include <HeightMap.h>
Public Member Functions
HeightMap (string const &filePath)
Initializes a new instance of the HeightMap class.
void LoadHeightMap ()
Loads the height map.
float GetHeightValueAtPixel (vec2i const &pixelPos)
Gets the height value at pixel. Assuming 4 bytes per pixel 32 bit image depth.
int GetWidth () const
Gets the width.
int GetHeight () const
Gets the height.
Private Attributes
uint * m_pHeightMap
The height map
vec2 m_heightMapDimensions
The height map dimensions
string m_heightMapFile
The height map file
Detailed Description
Definition at line 7 of file HeightMap.h.
Constructor & Destructor Documentation
HeightMap::HeightMap (string const & filePath)
Initializes a new instance of the HeightMap class.
Parameters
filePath The file path.
Definition at line 5 of file HeightMap.cpp.
References HeightMap(), and LoadHeightMap().
Referenced by HeightMap(), and Terrain::Terrain().
   : m_heightMapFile(filePath)
 {
   LoadHeightMap();
 }
Member Function Documentation
int HeightMap::GetHeight () const
Gets the height.
Returns
Definition at line 43 of file HeightMap.cpp.
Referenced by ForestTerrain::GenerateForest(), Terrain::GenerateNormals(), Terrain::GenerateTerrainIndices(), Terrain::GenerateTerrainVertices(), Terrain::GenerateTexCoords(), and Terrain::Terrain().
 {
   return m_heightMapDimensions.y;
 }
float HeightMap::GetHeightValueAtPixel (vec2i const & pixelPos)
Gets the height value at pixel. Assuming 4 bytes per pixel 32 bit image depth.
Parameters
pixelPos The pixel position.
Returns
Definition at line 19 of file HeightMap.cpp.
References m_pHeightMap.
 {
   uint pos = (m_heightMapDimensions.x * pixelPos.y) + pixelPos.x;
   //Color = 0xRRGGBBAA
   //Color packed in to a four-byte integer with RGBA component
   //We need mask and shift to get back the color channels.
   //todo this line crashes occasionally... run a bunch of tests.
   ubyte redChannel = ubyte((m_pHeightMap[pos] & 0x00FF0000) >> 16);
   ubyte blueChannel = ubyte((m_pHeightMap[pos] & 0x0000FF00) >> 8);
   ubyte greenChannel = ubyte((m_pHeightMap[pos] & 0x000000FF) >> 0);
   float ave = (redChannel + blueChannel + greenChannel) / 3.f;
   return ave / 255;
 }
int HeightMap::GetWidth () const
Gets the width.
Returns
Definition at line 38 of file HeightMap.cpp.
Referenced by ForestTerrain::GenerateForest(), Terrain::GenerateNormals(), Terrain::GenerateTerrainIndices(), Terrain::GenerateTerrainVertices(), Terrain::GenerateTexCoords(), and Terrain::Terrain().
 {
   return m_heightMapDimensions.x;
 }
void HeightMap::LoadHeightMap ()
Loads the height map.
Definition at line 11 of file HeightMap.cpp.
References GetImageDimensions(), GetPixelData(), m_heightMapDimensions, and m_pHeightMap.
Referenced by HeightMap().
 {
   SDL_Surface* pHeightMapSurface = GetSurfaceFromImg(m_heightMapFile);
   m_heightMapDimensions = GetImageDimensions(pHeightMapSurface);
   m_pHeightMap = (uint*)malloc(sizeof(uint) * m_heightMapDimensions.x * m_heightMapDimensions.y);
   m_pHeightMap = GetPixelData(pHeightMapSurface);
 }
Member Data Documentation
vec2 HeightMap::m_heightMapDimensions private
The height map dimensions
Definition at line 50 of file HeightMap.h.
Referenced by LoadHeightMap().
string HeightMap::m_heightMapFile private
The height map file
Definition at line 54 of file HeightMap.h.
uint* HeightMap::m_pHeightMap private
The height map
Definition at line 46 of file HeightMap.h.
Referenced by GetHeightValueAtPixel(), and LoadHeightMap().
The documentation for this class was generated from the following files:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/HeightMap.h
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/HeightMap.cpp