ICT397 Game Engine: Light Struct Reference
Light Struct Reference
#include <Light.h>
Public Member Functions
Light (LightType lightType, bool lightEnabled=true)
Public Attributes
bool enabled
Protected Attributes
LightType type
Detailed Description
Definition at line 25 of file Light.h.
Constructor & Destructor Documentation
Light::Light (LightType lightType, bool lightEnabled = true) inline
Definition at line 27 of file Light.h.
References enabled, and type.
Referenced by AmbientLight::AmbientLight(), DirectionalLight::DirectionalLight(), PointLight::PointLight(), and SpotLight::SpotLight().
     :enabled(lightEnabled)
     , type(lightType)
   {
   }
Member Data Documentation
bool Light::enabled
Definition at line 33 of file Light.h.
Referenced by Light().
LightType Light::type protected
Definition at line 35 of file Light.h.
Referenced by Light().
The documentation for this struct was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Light.h