ICT397 Game Engine: SpotLight Struct Reference
SpotLight Struct Reference
#include <Light.h>
Public Member Functions
SpotLight (vec3 const &lightDirection, vec3 const &lightPosition, float attenuation, float angleInDegrees, vec3 const &lightColor=vec3(1.0f, 1.0f, 1.0f), bool lightEnabled=true)
void SetConeAngle (float angleInDegrees)
Sets the cone angle.
Public Member Functions inherited from Light
Light (LightType lightType, bool lightEnabled=true)
Public Attributes
vec3 color
vec3 position
vec3 direction
float linearAttenuation
Public Attributes inherited from Light
bool enabled
Private Attributes
float coneAngle
float coneCosine
Additional Inherited Members
Protected Attributes inherited from Light
LightType type
Detailed Description
Definition at line 76 of file Light.h.
Constructor & Destructor Documentation
SpotLight::SpotLight (vec3 const & lightDirection, vec3 const & lightPosition, float attenuation, float angleInDegrees, vec3 const & lightColor = vec3(1.0f, 1.0f, 1.0f), bool lightEnabled = true) inline
Definition at line 78 of file Light.h.
References direction, Light::Light(), linearAttenuation, LT_Spot, position, SetConeAngle(), and SpotLight().
Referenced by SpotLight().
     : Light(LT_Spot, lightEnabled)
     , color(lightColor)
     , direction(lightDirection)
     , position(lightPosition)
     , linearAttenuation(attenuation)
   {
     SetConeAngle(angleInDegrees);
   }
Member Function Documentation
void SpotLight::SetConeAngle (float angleInDegrees) inline
Sets the cone angle.
Parameters
angleInDegrees The angle in degrees.
Definition at line 92 of file Light.h.
References coneAngle, and coneCosine.
Referenced by SpotLight().
   {
     coneAngle = angleInDegrees;
     coneCosine = cos(DegToRad(angleInDegrees));
   }
Member Data Documentation
vec3 SpotLight::color
Definition at line 98 of file Light.h.
float SpotLight::coneAngle private
Definition at line 105 of file Light.h.
Referenced by SetConeAngle().
float SpotLight::coneCosine private
Definition at line 106 of file Light.h.
Referenced by SetConeAngle().
vec3 SpotLight::direction
Definition at line 100 of file Light.h.
Referenced by SpotLight().
float SpotLight::linearAttenuation
Definition at line 101 of file Light.h.
Referenced by SpotLight().
vec3 SpotLight::position
Definition at line 99 of file Light.h.
Referenced by SpotLight().
The documentation for this struct was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Light.h