ICT397 Game Engine: PointLight Struct Reference
PointLight Struct Reference
#include <Light.h>
Public Member Functions
PointLight (vec3 const &lightPosition, vec3 const &lightColor=vec3(1.0f, 1.0f, 1.0f), bool lightEnabled=true)
Public Member Functions inherited from Light
Light (LightType lightType, bool lightEnabled=true)
Public Attributes
vec3 color
vec3 position
Public Attributes inherited from Light
bool enabled
Additional Inherited Members
Protected Attributes inherited from Light
LightType type
Detailed Description
Definition at line 62 of file Light.h.
Constructor & Destructor Documentation
PointLight::PointLight (vec3 const & lightPosition, vec3 const & lightColor = vec3(1.0f, 1.0f, 1.0f), bool lightEnabled = true) inline
Definition at line 64 of file Light.h.
References Light::Light(), LT_Point, PointLight(), and position.
Referenced by PointLight().
     : Light(LT_Point, lightEnabled)
     , color(lightColor)
     , position(lightPosition)
   {
   }
Member Data Documentation
vec3 PointLight::color
Definition at line 72 of file Light.h.
vec3 PointLight::position
Definition at line 73 of file Light.h.
Referenced by PointLight().
The documentation for this struct was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Light.h