ICT397 Game Engine: DirectionalLight Struct Reference
DirectionalLight Struct Reference
#include <Light.h>
Public Member Functions
DirectionalLight (vec3 const &lightDirection, vec3 const &lightColor=vec3(1.0f, 1.0f, 1.0f), bool lightEnabled=true)
Public Member Functions inherited from Light
Light (LightType lightType, bool lightEnabled=true)
Public Attributes
vec3 color
vec3 direction
Public Attributes inherited from Light
bool enabled
Additional Inherited Members
Protected Attributes inherited from Light
LightType type
Detailed Description
Definition at line 49 of file Light.h.
Constructor & Destructor Documentation
DirectionalLight::DirectionalLight (vec3 const & lightDirection, vec3 const & lightColor = vec3(1.0f, 1.0f, 1.0f), bool lightEnabled = true) inline
Definition at line 51 of file Light.h.
References direction, DirectionalLight(), Light::Light(), and LT_Directional.
Referenced by DirectionalLight().
     : Light(LT_Directional, lightEnabled)
     , color(lightColor)
     , direction(lightDirection)
   {
   }
Member Data Documentation
vec3 DirectionalLight::color
Definition at line 58 of file Light.h.
vec3 DirectionalLight::direction
Definition at line 59 of file Light.h.
Referenced by DirectionalLight().
The documentation for this struct was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Light.h