ICT397 Game Engine: AmbientLight Struct Reference
AmbientLight Struct Reference
#include <Light.h>
Public Member Functions
AmbientLight (vec3 const &lightColor=vec3(1.0f, 1.0f, 1.0f), bool lightEnabled=true)
Public Member Functions inherited from Light
Light (LightType lightType, bool lightEnabled=true)
Public Attributes
vec3 color
Public Attributes inherited from Light
bool enabled
Additional Inherited Members
Protected Attributes inherited from Light
LightType type
Detailed Description
Definition at line 38 of file Light.h.
Constructor & Destructor Documentation
AmbientLight::AmbientLight (vec3 const & lightColor = vec3(1.0f,1.0f,1.0f), bool lightEnabled = true) inline
Definition at line 40 of file Light.h.
References AmbientLight(), Light::Light(), and LT_Ambient.
Referenced by AmbientLight().
     : Light(LT_Ambient, lightEnabled)
     , color(lightColor)
   {
   }
Member Data Documentation
vec3 AmbientLight::color
Definition at line 46 of file Light.h.
The documentation for this struct was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/Light.h