ICT397 Game Engine: MouseEvent Struct Reference
MouseEvent Struct Reference
#include <GLInputHandler.h>
Public Member Functions
MouseEvent (SDL_MouseButtonEvent _event)
MouseEvent (SDL_MouseMotionEvent _event)
Public Attributes
MouseEventType eventType
SDL_MOUSE_EVENT mouseEvent
Detailed Description
Definition at line 39 of file GLInputHandler.h.
Constructor & Destructor Documentation
MouseEvent::MouseEvent (SDL_MouseButtonEvent _event) inline
Definition at line 44 of file GLInputHandler.h.
References eventType, and ME_BUTTON.
   {
     eventType = ME_BUTTON;
     mouseEvent.buttonEvent = _event;
   }
MouseEvent::MouseEvent (SDL_MouseMotionEvent _event) inline
Definition at line 50 of file GLInputHandler.h.
References MouseEvent().
Referenced by MouseEvent(), and GLInputHandler::ProcessEventQueue().
   {
     eventType = ME_MOTION;
     mouseEvent.motionEvent = _event;
   }
Member Data Documentation
MouseEventType MouseEvent::eventType
Definition at line 41 of file GLInputHandler.h.
Referenced by MouseEvent(), and GLInputHandler::ProcessEventQueue().
SDL_MOUSE_EVENT MouseEvent::mouseEvent
Definition at line 42 of file GLInputHandler.h.
The documentation for this struct was generated from the following file:
C:/Users/elizabeth/Documents/GitHub/Engine/OpenGLEngine/OpenGLEngine/GLInputHandler.h